### ISSUE TITLE
Kanban - e.g. Trello - task list - client dashboard

### ISSUE THREAD

**Issue by theCreativeMind-mrTP** [invoiceninja/admin-portal#214]
**What version of Invoice Ninja are you running? ie v4.5 / v5**
v5
**What environment are you running?**
Shared Hosting
**Have you searched existing issues/requests?**
no
**Screenshots**
If applicable, add screenshots to help explain your request/question.

**Additional context**
When could we see the Kanban back to v5?

How about this?
Let's say I have a Project created - on the client dashboard the kanban is also visible and the client could assign new tasks / tickets ... internally I can move it to progress or done /  time tracking, and various task related infos are generated and displayed on the kanban card as well... 
So what i am saying here is a tightly integrated kanban board with other functionalities of iN v5

**Comment by hillelcoren** [comment]
Hi,

Adding a Kanban is high on our priority list for v5 (along with v4 parity in general).

It's very unlikely we'd make the Kanban available in the client portal though, they're built with different technologies. The admin portal is built with Flutter whereas the client portal is built with Laravel.

**Comment by hillelcoren** [comment]
This has been implemented 

https://demo.invoiceninja.com/#/kanban
