### ISSUE TITLE
scroll bar horizontal on reports

### ISSUE THREAD

**Issue by GurjinderSingh** [invoiceninja/admin-portal#225]
**What version of Invoice Ninja are you running? ie v4.5 / v5**
v5

**What environment are you running?**
Docker

**Have you searched existing issues/requests?**
not some 

**Screenshots**

![image](https://user-images.githubusercontent.com/3470709/113102215-ba9a6000-91cb-11eb-8d8d-ce1c478e6525.png)

**Additional context**

scroll bar horizontal on reports

**Comment by WarMac4964** [comment]
Hey, @hillelcoren Can I work on this?

**Comment by hillelcoren** [comment]
Sure, that would be great!

**Comment by WarMac4964** [comment]
I am having some trouble setting up the app, Can you please help @hillelcoren

**Comment by hillelcoren** [comment]
We generally don't provide developer support but if you share the specific error you're seeing I can try to help

**Comment by hillelcoren** [comment]
This has been added
