### ISSUE TITLE
After sending email doesn't return to index view

### ISSUE THREAD

**Issue by lonix1** [invoiceninja/admin-portal#246]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
5.1.46

**What environment are you running?**
Docker

**Have you checked log files (storage/logs/) Please provide redacted output**
n/a

**Have you searched existing issues?**
no

**Have you reported this to Slack/forum before posting?**
no

**Describe the bug**
After sending email doesn't return to index view

**Steps To Reproduce**
- create quote or invoice
- click "send email"
- click "send"
- spinner finishes, then view remains as is (though email is sent successfully)
- must click "cancel" to return to previous view

**Expected behavior**
As in previous versions, after sending, it would return to previous (index) view

**Screenshots**
no

**Additional context**
I noticed this regression in today's latest version: 5.1.46

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**
yes

**Comment by lonix1** [comment]
PS noticed the repo's name change... nice

**Comment by hillelcoren** [comment]
Thanks for catching this! This part of the code needs some refactoring, I've checked in a fix.
