### ISSUE TITLE
[UX] Clicking row in index view automatically opens corresponding edit view

### ISSUE THREAD

**Issue by lonix1** [invoiceninja/admin-portal#247]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
5.1.46

**What environment are you running?**
Docker

**Have you checked log files (storage/logs/) Please provide redacted output**
n/a

**Have you searched existing issues?**
no

**Have you reported this to Slack/forum before posting?**
no

**Describe the bug**
Clicking a row in an index view automatically opens corresponding edit view

**Steps To Reproduce**
In any index view:
- clicking any cell in that row to select that row
- the corresponding detail view is shown to the right
- click that row again (probably by accident or otherwise... does happen)
- automatically opens the edit view for that record

**Expected behavior**
**UNSURE!!!** :question: 

**Screenshots**
no

**Additional context**
I'd expect a second click to do nothing as in other apps. So I want to call this a bug, but I can't - maybe this is by design??? (I hope it's a bug tho' :wink:)

However in my experience I've never seen this kind of UX on desktop or android - unsure of other platforms?

It's really weird and I open the edit view quite often, always curse the app, then curse myself, then click cancel, promise myself never to do that again... five minutes later I do it again! :laughing:

It also happens to me often due to jumping around between index views - e.g. clone/convert/pay/whatever, then either jumps to a different view or I need to go there manually, and sometimes the correct record is selected and sometimes not, and that's why I click the record again. It's a pure UX issue.

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**
yes

**Comment by hillelcoren** [comment]
Sorry, this is by design. 

If you're on a secondary tab clicking the row will change to the primary tab, clicking it again opens the edit screen.

**Comment by hillelcoren** [comment]
Just to note.. accidental clicks will of course happen but in this case it's non destructive, you can just click cancel.

**Comment by lonix1** [comment]
Is this a flutter-related UX design? (This is the only flutter app I've ever used)

I've used a similar UI in Microsoft Azure which also has an n-pane horizontal view, didn't see this behavior, but then again it's has a different UX / behavior compared to IN.

**Comment by hillelcoren** [comment]
It isn't related to Flutter, it's just how the code is written.

If this is disabled editing a record becomes much more tedious. Editing is the primary action, I prefer making it faster to access even if it means an occasional accidental click.

**Comment by lonix1** [comment]
I don't do many edits after creation, maybe that's why I trip over it - but I guess you can't make every UX possible, just one.

Thanks I'll get used to it!!

**Comment by hillelcoren** [comment]
Just to be clear.. this is very valid feedback, please let me know if you don't adjust to it. If enough people complain we'll of course consider making it an optional setting.

**Comment by lonix1** [comment]
Future readers: show your preference by voting on this comment.

:+1: = I want the second click to open the edit view (current behavior)
:-1: = I wish the second click did nothing

**Comment by hillelcoren** [comment]
Curious to follow up on this issue, do you still find the behavior problematic?

In the latest version we've refined the UX so by default the panel is hidden.

**Comment by hillelcoren** [comment]
We've added an setting to opt-in to this behavior on Settings > Device Settings
