### ISSUE TITLE
[UX] Expanded menu is too wide

### ISSUE THREAD

**Issue by lonix1** [invoiceninja/admin-portal#248]
**What version of Invoice Ninja are you running? ie v4.5 / v5**
5.1.46

**What environment are you running?**
Docker

**Have you searched existing issues/requests?**
yes

**Screenshots**
see below

**Additional context**
The menu on the left is unnecessarily wide, and reduces the amount of usable space on desktops.

## example 1:
- has short company name
- longest item is "Recurring Invoices"
- has unnecessary padding
 
![default](https://user-images.githubusercontent.com/40320097/114842374-132b4900-9dd9-11eb-908a-25933aabde33.png)

## example 2:
- has long company name
- longest item is "Dashboard"
- has unnecessary padding - unless you want the company name to be shown in full (though that's pointless, see discussion below)

![long-name](https://user-images.githubusercontent.com/40320097/114842622-51286d00-9dd9-11eb-818f-8816bba5e7e4.png)

## example 3:
- has short company name
- longest item is "Dashboard"
- has lots of unnecessary padding

![short-name](https://user-images.githubusercontent.com/40320097/114844008-ae70ee00-9dda-11eb-8674-753f7a52a30e.png)

## analysis
- Due to wide menu, I must do lots of horizontal scrolling when index views are shown (in the middle panel) - the table never shows all the columns when the third panel (rightmost) is also open (which is always)
- the menu must be as wide as the widest menu item - "Recurring Invoices" - though if user doesn't sell monthly services he'll disable that feature, and longest menu item becomes "Dashboard"
- Many companies have long names, e.g. "Ninja Cleaning Services Inc." - but to widen menu to show it in full pointless, as user knows the name of his company, it provides no benefit, and eats valuable screen real estate
- obvious criticism to all this is "just collapse the menu"... but that isn't ideal as I need to see the labels for the icons (I don't know which is which)... in fact I'm one of those users who'd be happy to hide the icons instead of the labels

## possible solutions for long company names
1. only show logo
2. only show name
3. clip name to x characters and ellipsis (e.g. "Ninja Cleani..."
4. **BEST:** define "short name" for use in UI, whereas "legal name" used in PDFs, e.g. "Ninja" and "Ninja Cleaning Services Ltd" respectively

My gut feel is 4 is best - I can't think of an example right now, but I have seen that setup in other apps. For backwards compatibility should migrate `Name` to `LegalName` (so as not to break existing installations) and leave `ShortName` field empty.

Sorry for long post, hope this can be considered someday.

**Comment by hillelcoren** [comment]
Hi,

Thanks for the detailed feedback!

Have you considered using the collapsed menubar by clicking the left arrow at the bottom of the sidebar?

**Comment by hillelcoren** [comment]
I see you've tried it, with the menu collapsed the labels should show as tooltips. Does that help?

**Comment by lonix1** [comment]
Yep I mentioned that above ... it's not nearly as useful as it sounds as I never know which is which :)

**Comment by hillelcoren** [comment]
But there are tooltips?

**Comment by lonix1** [comment]
Tooltips: Yes there are tooltips, but you still need to hover over each icon to find the thing you're looking for :)

It's not really a solution - Truth is I keep the menu expanded all the time even though it eats space, its much more useful to see the words

**Comment by lonix1** [comment]
Feel free to close if you think this is a weird one...

But I think maximizing *horizontal space in a horizontally-structure app* is an important consideration

PS I'm using a high-res monitor but the index views still don't show all the columns

**Comment by hillelcoren** [comment]
All good feedback, I'm also curious to know what other people think... 

I assume this is in part because the right preview pane is using up the space?

Have you tried hiding the preview using the option in the bottom buttons? Currently if you hide the preview and then select a record the preview is shown, we could change this so that selecting a record when the preview is hidden shows the edit screen instead and keeps the preview hidden.

**Comment by lonix1** [comment]
> Have you tried hiding the preview using the option in the bottom buttons?

Yes I worked that way for a little while but it also got in the way, most of the time I want to see the detail view immediately

> ...could change this so that selecting a record when the preview is hidden shows the edit screen instead and keeps the preview hidden.

I can only speak for myself, that wouldn't be ideal as it bumps into another UX issue from #247. But I think it's certainly an option and I'm certain many users would like that.

**Comment by lonix1** [comment]
Future readers: please vote on this comment

:+1: = I like it as is, don't change anything
:-1: = Make the menu narrower, maybe using the "short" vs "legal" name idea
:smile: = Keep detail view hidden so index views are shown in full

...or add your own ideas below

**Comment by hillelcoren** [comment]
We've made the menu bar narrower and the font a bit smaller.

Thanks for your feedback!
