### ISSUE TITLE
Cancelled and past due invoices showing in dashboard

### ISSUE THREAD

**Issue by jinjie** [invoiceninja/admin-portal#250]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.1.46-C45

**What environment are you running?**
Docker

**Have you checked log files (storage/logs/) Please provide redacted output**
NA

**Have you searched existing issues?**
Yes

**Have you reported this to Slack/forum before posting?**
No

**Describe the bug**
Canceled and Past due invoices showing in the Dashboard under *Past Due Invoices*

**Steps To Reproduce**
- Create an invoice that is already past due
- Mark the invoice cancelled

**Expected behavior**
Shouldn't be included in Past Due Invoices for cancelled invoices

**Screenshots**
<img width="435" alt="Screenshot 2021-04-16 at 2 53 57 PM" src="https://user-images.githubusercontent.com/2721195/114983817-a3de5380-9ec3-11eb-9750-cb902f89ba8c.png">

**Additional context**
Not sure if it is deliberate but I really find this behaviour unexpected. Since we are not expecting any cancelled invoices to be collected, so it shouldn't be in the dashboard.

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**
Yes. Already done.

**Comment by hillelcoren** [comment]
Thanks for reporting this, to be fixed...
