### ISSUE TITLE
Unexpected date changing in tasks after setting time

### ISSUE THREAD

**Issue by hahyes** [invoiceninja/admin-portal#251]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.1.46

**What environment are you running?**
Shared Hosting

**Have you reported this to Slack/forum before posting?**
No.

**Describe the bug**
In task creation, date is changing to the next day if we choose time earlier than current time. In my opinion, this is not how it should works. It's very confusing and I don't think it should work like this, so I treat it like a bug.

**Steps To Reproduce**
1. Create new task.
2. Fill data with current day.
3. Fill beginning time with hour ago.
4. Data is changing to the next day.

**Expected behavior**
Not doing it, or making this optional/configurable. It can lead to many mistakes.

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**
Yeah.

**Comment by hillelcoren** [comment]
Hi,

Thanks for reporting this, I'll look into it...

**Comment by hillelcoren** [comment]
I'm having trouble reproducing this, are you able to post a video screen recording?
