### ISSUE TITLE
No SAVE button on Settings - Device settings

### ISSUE THREAD

**Issue by adoewa** [invoiceninja/admin-portal#252]
I don't have a save button on the Settings page - Device settings.

When i make some changes, they are lost when log-off / log-on.
![NinjaV5](https://user-images.githubusercontent.com/28945652/115102001-b0f15600-9f48-11eb-8579-286dfe1346ce.JPG)

**Comment by hillelcoren** [comment]
The 'device settings' page has settings which apply to the local device, a save button isn't needed since the changes aren't sent to the server.

**Comment by adoewa** [comment]
Hi Hillel,

 

It don’t save my settings… when i log out and log in it’s back to the original settings…

 

 

 

Met vriendelijke groeten 


 



 <https://www.adoewa.be/>        <https://www.facebook.com/adoewa.be/>        <https://www.instagram.com/adoewa/> 

Koen Rottier 

Webdesign | Drukwerk
Multimedia | Elektrische schema’s

Florent Pauwelslei 2 b12, 2100 Deurne

+32 (0)494 86.13.80
VAT: BE0825.797.226
 <https://www.adoewa.be/> www.adoewa.be

 

 

Van: Hillel Coren ***@***.***> 
Verzonden: zaterdag 17 april 2021 19:25
Aan: invoiceninja/admin-portal ***@***.***>
CC: Koen ***@***.***>; Author ***@***.***>
Onderwerp: Re: [invoiceninja/admin-portal] No SAVE button on Settings - Device settings (#252)

 

The 'device settings' page has settings which apply to the local device, a save button isn't needed since the changes aren't sent to the server.

**Comment by hillelcoren** [comment]
I'm not sure, I can't replicate it

**Comment by hillelcoren** [comment]
Can you post a video?

**Comment by adoewa** [comment]
Hi Hillel,

 

I know what i did wrong…

 

I closed the window… now i logged off and on and it seems tob e ok…

 

 

 

Met vriendelijke groeten 


 



 <https://www.adoewa.be/>        <https://www.facebook.com/adoewa.be/>        <https://www.instagram.com/adoewa/> 

Koen Rottier 

Webdesign | Drukwerk
Multimedia | Elektrische schema’s

Florent Pauwelslei 2 b12, 2100 Deurne

+32 (0)494 86.13.80
VAT: BE0825.797.226
 <https://www.adoewa.be/> www.adoewa.be

 

 

Van: Hillel Coren ***@***.***> 
Verzonden: zaterdag 17 april 2021 21:16
Aan: invoiceninja/admin-portal ***@***.***>
CC: Koen ***@***.***>; Author ***@***.***>
Onderwerp: Re: [invoiceninja/admin-portal] No SAVE button on Settings - Device settings (#252)

 

Can you post a video?

**Comment by hillelcoren** [comment]
Thanks for the update, glad to hear it's working!
