### ISSUE TITLE
Release tags for F-Droid

### ISSUE THREAD

**Issue by jspricke** [invoiceninja/admin-portal#253]
Hi,

can you please add git tags for your releases? That would make it easier for F-Droid to build the app.

Thanks!

**Comment by hillelcoren** [comment]
Hi,

Sure, happy to! We're still getting our CI/CD pipeline reliable but I'll try to remember to at least do it manually for now.

I think I recognise your name from the F-Droid forums, if you're able to change our build to use the stable Flutter channel rather than dev it would be helpful.

**Comment by hillelcoren** [comment]
https://github.com/invoiceninja/admin-portal/releases/tag/v5.0.46

**Comment by jspricke** [comment]
Sure, which version should I add? 2.0.5?

**Comment by hillelcoren** [comment]
If you can track 'stable' it would be best, otherwise 2.0.5 is fine it would just likely need to be updated in the future.

**Comment by jspricke** [comment]
Afaik we need to set it explicitly, I added 2.0.5 now.

**Comment by hillelcoren** [comment]
Ok great, thanks for your help!

**Comment by hillelcoren** [comment]
@jspricke 

I noticed on [f-droid.org](https://f-droid.org/packages/com.invoiceninja.app/) the license for the app is listed as Attribution Assurance License. We recently changed to Elastic License 2.0, could you please help us get it updated. Thanks!

**Comment by jspricke** [comment]
Please open a merge request here: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.invoiceninja.app.yml#L3

**Comment by hillelcoren** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9342

**Comment by hillelcoren** [comment]
@jspricke I'm not seeing the latest version on F-Droid, any ideas why?

**Comment by jspricke** [comment]
***@***.*** I'm not seeing the latest version on F-Droid, any ideas why?

Autoupdates are disabled:

https://gitlab.com/fdroid/fdroiddata/-/commit/1e7ee241e3316ddb810321e7cd27d6bc27c61b31#db9fd558d2f9185b35dafa8cca3c22f33126e719_249_222

@linsui can you comment?

**Comment by linsui** [comment]
Sorry, I forgot to enable autoupdate after https://github.com/invoiceninja/admin-portal/issues/314 was fixes.
