### ISSUE TITLE
Add client dialog while creating invoice V5

### ISSUE THREAD

**Issue by GurjinderSingh** [invoiceninja/admin-portal#254]
**What version of Invoice Ninja are you running? ie v4.5 / v5**
v5.1.46-C45 
**What environment are you running?**
Docker

**Have you searched existing issues/requests?**
yes
**Screenshots**
in V4
![image](https://user-images.githubusercontent.com/3470709/115079406-202a6400-9ecf-11eb-9940-f02eda57ec69.png)

**Additional context**
add dialog to create new client with basic info while invoicing. some client don't need too much information just name is enough

**Comment by hillelcoren** [comment]
Hi,

The same functionality is available in v5 but rather than a dialog the app uses the right sidebar.

The approaches require the same number of clicks but using the sidebar enables setting all of the client fields rather than a subset as in v4.

**Comment by hillelcoren** [comment]
It's worth noting I think it would be better if when the plus is clicked the client pane is showed over the invoice edit page rather than show the client list.

**Comment by GurjinderSingh** [comment]
> Hi,
> 
> The same functionality is available in v5 but rather than a dialog the app uses the right sidebar.
> 
> The approaches require the same number of clicks but using the sidebar enables setting all of the client fields rather than a subset as in v4.

but it reset everything in invoice and increase user step to complete simple invoice's. most invoice's we need are with all client info but some are created just with name and are kept for record only. can we allow like v4 to decrease step and make invoicing little faster.


extra request: add mark sent on new invoice next save and cancel.

**Comment by hillelcoren** [comment]
Have you tried it? That's not correct. When you add a client it doesn't reset the invoice and the number of steps are exactly the same?

I agree it would be useful to add a "save and mark sent" option.

**Comment by GurjinderSingh** [comment]
> Have you tried it? That's not correct. When you add a client it doesn't reset the invoice and the number of steps are exactly the same?
> 
> I agree it would be useful to add a "save and mark sent" option.

my apologizes, you are right.

**Comment by GurjinderSingh** [comment]
> Have you tried it? That's not correct. When you add a client it doesn't reset the invoice and the number of steps are exactly the same?
> 
> I agree it would be useful to add a "save and mark sent" option.

mark sent and mark sent + paid will also help us.

**Comment by hillelcoren** [comment]
Mark paid/sent are good ideas, we'll try to add them.
