### ISSUE TITLE
Group invoices by client Groups and side bar groups

### ISSUE THREAD

**Issue by GurjinderSingh** [invoiceninja/admin-portal#255]
**What version of Invoice Ninja are you running? ie v4.5 / v5**
v5.1.46-C45
**What environment are you running?**
Docker
**Have you searched existing issues/requests?**
yes
**Additional context**
in side bar allow option to list groups and clicking on group allow listing clients
able to search invoices by client group

**Comment by hillelcoren** [comment]
Hi,

To clarify.. if we add the group to the invoice sidebar clicking it would show the invoices filtered by the group not the clients.

**Comment by GurjinderSingh** [comment]
yes it can be sub option in both in clients and invoices. another way can be add groups main options and then allow filter 

left side menu
> Groups  lists all Groups 
select one group open lists in right sidebar with latest inovice/cllient/payment 100% identical to Clients   

or 

> Groups
>>Invoices    << ADD filters on bottom to fillter by different Group or search.  
>>Clients
>>Payment
>> so on

or 

This method will create trouble with 10+ Groups
>Groups
>>Group Name A  << ADD filters on bottom for invoice and clients
>>Group Name B

**Comment by hillelcoren** [comment]
In the next release once you filter by a group (ie, by clicking on the group in the client preview) you'll be able to view the group's invoices, quotes, etc. using the top menu.
