### ISSUE TITLE
allow Serach By payment and invoice value 

### ISSUE THREAD

**Issue by GurjinderSingh** [invoiceninja/admin-portal#256]
What version of Invoice Ninja are you running? ie v4.5 / v5
v5.1.46-C45
What environment are you running?
Docker
Have you searched existing issues/requests?
yes
 Additional context
search payment /invoice by value. It will help locate transaction from bank statement.

**Comment by hillelcoren** [comment]
This is already supported, you can filter the amount field in the reports to find the record.
