### ISSUE TITLE
Saving new client process can creates duplicates based on user reaction

### ISSUE THREAD

**Issue by lonix1** [invoiceninja/admin-portal#257]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
5.1.47

**What environment are you running?**
Docker

**Have you checked log files (storage/logs/) Please provide redacted output**
yes

**Have you searched existing issues?**
yes

**Have you reported this to Slack/forum before posting?**
no

**Describe the bug**
Saving new client process can creates duplicates if process times out

**Steps To Reproduce**

- clients, create
- populate form, click save
- spinner spins, then spins, then stops spinning; no message shown (e.g. "error" or "client created")

I naturally assumed there was an error, because when it works it returns to the index view and selects the newly-created client, so:
- I clicked save again
- spinner spins, then stops
- I clicked save again
- spinner spins, then stops
- I gave up and clicked cancel

And to my surprise there were now three new client entries (identical except for different PKs).

**Expected behavior**
In line with the UX in the rest of the app, if it succeeds to create a new entry then should close the create form and show the index view.

If it stays on the create form then that is a signal that there was an error, so should show an error message.

Not sure if this is possible: if this user journey is somehow unavoidable (create form remains open), then refuse to create the record as it already exists (maybe take a hash of most recent new record and compare to that), or at least alert the user.

**Screenshots**
no

**Additional context**
I assume I can only soft (not hard) delete the dupes? A workaround is to edit and "reuse" them for other clients.

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**
no, as I don't know what caused the underlying error - maybe network latency? So I can't repro predictably.

**Comment by hillelcoren** [comment]
Hi,

Thanks for reporting this! 

Why is the request timing out, are there any errors in the logs?

**Comment by lonix1** [comment]
Nope nothing in logs (on a separate note I've never noticed anything in the `laravel.log` other than the version number).

But it's just my assumption that it was timing out. I'm unsure. It spun for maybe 20 seconds, then just stopped, and I was still on the create form. I didn't realize the new record was actually created successfully.

---
Unsure how to repro this unfortunately. If you can't either then close it and I'll let you know if it ever happens again.

**Comment by lonix1** [comment]
It does remind me of issue #246.

**Comment by hillelcoren** [comment]
Agreed, they probably have the same root problem. We've made further changes since that change.

**Comment by lonix1** [comment]
Actually after a second look, I'm on `v5.1.48-C46` so I should be on "latest"

**Comment by hillelcoren** [comment]
Can you reproduce the problem?

**Comment by lonix1** [comment]
I tried but no. I'm unsure how to simulate latency (assuming that was the problem). It "just happened".

> We've made further changes since that change

Are you saying the fix is in this version? If so then close and I'll update this if I even encounter it again. I'll try pay careful attention to what actions I take in such a scenario.

**Comment by hillelcoren** [comment]
Sounds good, please let us know if you see the problem again.
