### ISSUE TITLE
Recent payments in dashboard not sorted correctly

### ISSUE THREAD

**Issue by jinjie** [invoiceninja/admin-portal#260]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.1.53-C47

**What environment are you running?**
Docker

**Have you checked log files (storage/logs/) Please provide redacted output**
n/a

**Have you searched existing issues?**
Yes

**Have you reported this to Slack/forum before posting?**
No

**Describe the bug**
Payments not sorted by descending date (although it is, see additional context). For example, I have the following payments sorted in this way in Dashboard > Payments > Recent Payments:

- 2229 (Nov 16 2020)
- 2230 (Oct 27 2020)
- P2014-20002 (Apr 20 2021)

**Steps To Reproduce**
1. Import payments
2. Change the payment number format that do not start with number, for example, PNNNN-NNNNN
3. Add payments
4. View the recent payments

**Expected behavior**
It should be sorted in the following way:

- P2014-20002 (Apr 20 2021)
- 2229 (Nov 16 2020)
- 2230 (Oct 27 2020)

**Screenshots**

**Additional context**
I suspect that although it is sorted by date but it is also sorting the payments by the document ID. the document ID should be ignored.

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**
N/a

**Comment by hillelcoren** [comment]
Hi,

Thanks for reporting this!
