### ISSUE TITLE
Cannot update Fee Percent in payment gateway

### ISSUE THREAD

**Issue by jinjie** [invoiceninja/admin-portal#261]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.1.53-C47

**What environment are you running?**
Docker

**Have you checked log files (storage/logs/) Please provide redacted output**
No

**Have you searched existing issues?**
Yes

**Have you reported this to Slack/forum before posting?**
No

**Describe the bug**
In *Settings > Online Payments > Stripe > Limits/Fees*. Cannot remove Fee Percent. It can only accept numbers > 0. Removing the field or entering 0 does not work. The work around is to enter 0.00000001 in the field

**Steps To Reproduce**
1. Setup Stripe payment gateway
2. Enter a number more than 0 and save
3. Try removing the number or setting it to 0

**Comment by turbo124** [comment]
Can reproduce, it appears that the POST does not contain the updated values. When zeros are inserted

**Comment by hillelcoren** [comment]
Thanks for catching this!
