### ISSUE TITLE
Changing line item in quote/invoice form changes underlying product

### ISSUE THREAD

**Issue by lonix1** [invoiceninja/admin-portal#262]
:question: I don't know which repo this belongs in :question:

**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
5.1.53

**What environment are you running?**
Docker

**Have you checked log files (storage/logs/) Please provide redacted output**
n/a

**Have you searched existing issues?**
yes

**Have you reported this to Slack/forum before posting?**
no

**Describe the bug**
Changing a line item in a quote/invoice will change the underlying product.

**Steps To Reproduce**
setup
- create new product
- create new quote and use that product, but change the cost and quantity, save
- convert quote to invoice
- mark invoice as paid

bug
- create new quote and choose that product
- cost and quantity are wrong

I assume the same is true when making the change on a create invoice form.

**Expected behavior**
When a change is made to a product in the create quote/invoice form, it should apply just to that transaction. It should not change the underlying product.

**Screenshots**
no

**Additional context**
*I don't remember for sure, but I don't recall older versions working this way?*

Also, this isn't how other (accounting etc) apps work - the idea is that one can change anything on a quote/invoice and it affects only that transaction (it's a convenience feature). *To make the change "stick" one must edit the actual product.*

If not done that way, then one can very easily make a mistake (as I did). A change is made once-off for a particular customer (in the create quote/invoice form). Later that product is used in a new quote/invoice and the wrong values are there. And one doesn't pay attention to it as it's completely unexpected - so an incorrect quote/invoice would be sent to the customer.

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**
yes

**Comment by hillelcoren** [comment]
Hi,

Can you check if auto-update is enabled in the product settings?

**Comment by lonix1** [comment]
Yep that solves it - Thanks!

I don't recall ever turning on this option! Weird!

**Comment by hillelcoren** [comment]
Great, this setting is on by default
