### ISSUE TITLE
Task’s times should not apply some hidden date values

### ISSUE THREAD

**Issue by itkfm** [invoiceninja/admin-portal#265]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.1.58-C47

**What environment are you running?**
ZIP

**Describe the bug**
Accidentally selected the wrong date? (let’s +1 day)
Wanna change it?
No problem, just let me turn your 0:30 task into -23:30…

> Please correct any overlapping times

**Steps To Reproduce**
1. Edit some task’s times

**Expected behavior**
There are no hidden date values applied to the TIME fields that lead to all kind of weird behavior when editing times. 

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**
yes

**Comment by hillelcoren** [comment]
Duplicate #251
