### ISSUE TITLE
Task Settings > Invoice Task Datelog setting cannot be turned off

### ISSUE THREAD

**Issue by hmnd** [invoiceninja/admin-portal#266]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.1.59-C47

**What environment are you running?**
Docker

**Have you checked log files (storage/logs/) Please provide redacted output**
N/A

**Have you searched existing issues?**
Yes.

**Have you reported this to Slack/forum before posting?**
No.

**Describe the bug**
Whenever the Task Settings > Invoice Task Datelog setting is disabled, and the settings are saved, the setting reverts back to enabled. 

**Steps To Reproduce**
1. Open Task Settings.
2. Disable the Invoice Task Datelog setting.
3. Save settings.

**Expected behavior**
Invoice Task Datelog setting is disabled.

**Screenshots**
[Screen recording](https://user-images.githubusercontent.com/12853597/116969974-07aa9f80-ac6c-11eb-91f0-897c6e245fc4.mp4)

**Additional context**
Looking at network request log, it appears that the API call is setting `invoice_task_datelog: false`, but the response from the API does not contain such an option. It only contains `invoice_task_timelog`. Perhaps `invoice_task_datelog` isn't currently implemented correctly in the API model?

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**
Yes.

**Comment by hmnd** [comment]
Sorry, wasn't sure which repo a possible API issue fit better in.

**Comment by hillelcoren** [comment]
Thanks for catching this, we appreciate the detailed error report!

@turbo124 we must have miscommunicated here, I've added the missing boolean on Slack

**Comment by turbo124** [comment]
I've checked in a fix in the API
