### ISSUE TITLE
Can't save changes to Generated Numbers for individual clients/groups

### ISSUE THREAD

**Issue by hmnd** [invoiceninja/admin-portal#268]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.1.61-C47

**What environment are you running?**
Docker

**Have you checked log files (storage/logs/) Please provide redacted output**
N/A

**Have you searched existing issues?**
Yes.

**Have you reported this to Slack/forum before posting?**
No.

**Describe the bug**
When trying to change Generated Numbers settings for an individual client or group, the save button does not work.

**Steps To Reproduce**
1. Open Settings for any client or group.
2. Make a change in the Generated Number section (eg. change the Invoice Number counter).
3. Click Save button.

**Expected behavior**
The settings are saved correctly.

**Screenshots**
[Screen recording](https://user-images.githubusercontent.com/12853597/117530405-dc88be80-af91-11eb-9da4-6710a9f6af00.mp4)

**Additional context**
Every time I try to save, the following gets logged to the console: `Another exception was thrown: Instance of 'minified:lX<void>'`. No API request is made.

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**
Yes.

Thanks :)

**Comment by hillelcoren** [comment]
Hi,

Thanks for reporting this, I've checked in a fix for the next release.
