### ISSUE TITLE
Provide a way to manually set order of Task Status

### ISSUE THREAD

**Issue by hmnd** [invoiceninja/admin-portal#269]
**What version of Invoice Ninja are you running? ie v4.5 / v5**
v5.1.61-C47

**What environment are you running?**
Docker

**Have you searched existing issues/requests?**
Yes.

**Screenshots**
[Task Status](https://user-images.githubusercontent.com/12853597/117564634-e4b02f00-b061-11eb-95f4-5037f18d1da7.png)

**Additional context**
Currently, there doesn't appear to be a way to manually change the order of task statuses. I can see that some form of sort order is already being stored, so I'm guessing it's just a matter of implementing it in the frontend.

Along with that, it would be great if a default task status could be specified. Currently the latest added task is set as default (from my screenshot above, Awaiting Feedback is now the default which isn't ideal).

**Comment by hillelcoren** [comment]
Hi,

You can drag and drop the statuses on the Kanban board. 

Tasks should use the first task status by default.

**Comment by hmnd** [comment]
@hillelcoren Doesn't seem like I can (on web, at least). Can't drag statuses, nor individual tasks.

As a workaround, I've set the `sort_order` key on my task statuses manually via the API.

**Comment by hillelcoren** [comment]
You need to click for a second and hold to drag

**Comment by hmnd** [comment]
Ah, I see. That works, thanks!

**Comment by hillelcoren** [comment]
Happy to help :)

**Comment by hmnd** [comment]
@hillelcoren Although that works, I think it would still be great to provide a way to do this from the task status list in settings. Perhaps [by dragging](https://user-images.githubusercontent.com/12853597/117565346-85541e00-b065-11eb-9b47-d1c059c02a49.png), and/or [with a menu like in Invoices](https://user-images.githubusercontent.com/12853597/117565348-85541e00-b065-11eb-9959-e056a2fbb941.png).

Dragging in the kanban board isn't easily discoverable, particularly for those who prefer the list view.
