### ISSUE TITLE
Time Tracker time labels are a bit unclear and "too much information" at the same time

### ISSUE THREAD

**Issue by nekohayo** [invoiceninja/admin-portal#270]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
Paid SaaS version (which I suppose is version 4 right now)

**What environment are you running?**
SaaS

**Have you checked log files (storage/logs/) Please provide redacted output**
No

**Have you searched existing issues?**
Yes

**Have you reported this to Slack/forum before posting?**
No

**Describe the bug**

![invoice ninja time tracker visual overload](https://user-images.githubusercontent.com/479401/117867696-b2bbea00-b266-11eb-9d26-7998ca334a15.png)

As you can see in the screenshot above, I find the current information displayed in the leftmost column of the tasks time tracker to be simultaneously visually overloading _and_ not precise enough. My screenshot doesn't demonstrate the worst case because it only shows 4 tasks and they have been started months ago, but the typical worst case is when I have two dozen tasks (across several projects) that have been started a couple days ago, so they all end up showing me their totals in excruciating detail (precise to the second; I don't ever need that kind of precision in an overview) yet not explaining what those timestamp lables are, so when it's all "a day ago" you have no idea what it actually means without "thinking about it".

When it says for example:

```
8:21:24
10 hours ago
```

```
17:03:36
2 days ago
```

etc. (multiply that by twenty such entries), it's visually confusing as heck. "Is the upper row a total? A start time? The endtime? The last time I modified something in the task?" As long as your tasks have totals less than 24 hours, there's no way to tell what those upper strings mean without "thinking" about it and remembering it. Same goes for the lower row for anything lesser than weeks: you can't instantly tell that this means "The time the task was first created", in most cases it visually looks as if this could be a start time, the last time you touched it/ended it, etc.

Most of the time I parse those as "the last time I touched them / worked on them" because that's what I'm actually looking for (i.e. sorting by recency of activity) but it's actually a trap because that's not the information that is actually shown there.

**Expected behavior**
Please be explicit with the _meaning_ of those strings in your UI and simplify the irrelevant details out by using human-readable timestamps. I don't care about seconds (and I'd venture a guess that nobody does), and I'd like to be able to be able to visually scan and distinguish between the various items in the column on the left so that I can find and resume a task within a _split-second_ without needing to _think_ and "parse" them.

The four unlabelled "Times" columns are also a bit visually confusing because the last three are all identical. At least a label at the top of the last column, and/or some color or transparency on that 4th column, might help.

Assume your user is drunk, stupid, confused, and just plain lazy. Don't make me pause and parse the meaning of those strings everytime I look at the time tracker when I _don't have time_ to think as I need to instantly start the task I'm supposed to start because some client just called me out of the blue (and since I'm talking to them on the phone I can't do visual analysis work at the same time anyway, because multitasking is a lie) or because I'm constantly context-switching. Make it idiot-proof please.

**Comment by hillelcoren** [comment]
Awesome, glad to hear it!
