### ISSUE TITLE
It is possible to confuse v5's time tracker start/end times when entering military (24h) hours into an AM/PM system

### ISSUE THREAD

**Issue by nekohayo** [invoiceninja/admin-portal#271]
This is purely something I noticed when testing out something else in https://demo.invoiceninja.com :

If military time is not enabled (it isn't by default, as far as I can see) in the localization settings, and you edit a task in the time tracker, in which you try to type some military start/end times, it parses them upside-down and gets very confused: it thinks "11" always means 11 PM, and it thinks "14" means 2AM. For example:

![Screenshot from 2021-05-11 17-59-47](https://user-images.githubusercontent.com/479401/117890466-3552a280-b283-11eb-99bb-9345a6a8e9ef.png)
![Screenshot from 2021-05-11 17-59-54](https://user-images.githubusercontent.com/479401/117890468-35eb3900-b283-11eb-8ffc-74fac7f90dc5.png)

...but a start time of 11 before a start time of >12 probably means the user intended to type military times, so maybe this situation can be autodetected.

In the worst case scenario I guess you could say that the user would be expected to type "11 am" for it to be parsed as such, but in the case of hours >12 such as "14", "1430", "13h30", "13:30" etc., it certainly shouldn't add/substract 12 hours to them.

**Comment by hillelcoren** [comment]
Hi,

Thanks for the feedback!

We'll look into correcting this...

**Comment by hillelcoren** [comment]
Thanks for reporting this, it was very much broken. For now I've changed it to always understand military time. Note: if am/pm isn't specified the app defaults to pm but you can switch to am by adding an 'a' at the end.
