### ISSUE TITLE
Include Due Date, Taxable, and Tax Rate columns in Invoice Item Report

### ISSUE THREAD

**Issue by lancefogle** [invoiceninja/admin-portal#273]
**What version of Invoice Ninja are you running? ie v4.5 / v5**
v5

**What environment are you running?**
Shared Hosting

**Have you searched existing issues/requests?**
Yes

**Screenshots**
N/A

**Additional context**
The Invoice Item report isn't really useful for export as it lacks basic fields needed to really get the data from the invoice including all line items. In my case, I use bookkeeping software for tax purposes and Invoice Ninja for the invoicing/quoting/payments platform. The Invoice Item report comes the closest but misses critical details to allow export and import for proper accounts tracking. Requesting the below columns be added as selectable columns for this report:

1 - Due Date
2 - Taxable  - meaning Y or N if tax applied to that line item
3 - Tax Rate - would just be the applied tax percentage to that line item

**Comment by lancefogle** [comment]
First let me apologize for not realizing there was already a columns button in the top right. I have updated my request to include the required columns and explanation of what I mean. I will also include again below:

1 - Due Date
2 - Taxable  - meaning Y or N if tax applied to that line item
3 - Tax Rate - would just be the applied tax percentage to that line item

**Comment by hillelcoren** [comment]
Perfect, thanks!
