### ISSUE TITLE
Feature Request :: workflow improvement :: invoice line item creation "Description" auto-select

### ISSUE THREAD

**Issue by ylluminate** [invoiceninja/admin-portal#277]
v5 :: Hosted (invoicing.co)
As per [this forum post](https://forum.invoiceninja.com/t/v5-feature-request-refinements-in-products-items-description-entry-etc/7075).

I use default values that serve as reminders for some fields such as for the “Description” field contents. (Eg, [screenshot](https://p153.p0.n0.cdn.getcloudapp.com/items/d5uAlKeg/16d16249-62e6-4012-9fbd-27ac7df47e1c.jpg?v=553c7a2c0eb9b870dddd313c9de12648))

When an item type is selected for an Item on each invoice line, the “Description” field should be automatically selected so we can simply start typing over our default values for more rapid entry, eg:
![example](https://p153.p0.n0.cdn.getcloudapp.com/items/RBul6Q4E/cf9c3a91-6455-4bb0-8fc0-329ceb45e059.jpg?v=227796183a2757a78d6c0735becf7b7a)

This is particularly important when entering many 10s of lines for an invoice, since the current entry method feels very clunky. 

Thus upon selection / choosing of the Item type, having the system auto-highlight the description field would really help to speed it up. This would then help in the tab movement to the next fields since having no field in each Item selected by default requires the person doing entry to click on into the Description.

**Comment by hillelcoren** [comment]
Agreed, this is important. 

I think part of the problem is the autocomplete component doesn't yet support keyboard controls (https://github.com/flutter/flutter/issues/82783) so you need to use the mouse to select the record. If you could use tab to select the product the focus would move to the next field instead.

**Comment by ylluminate** [comment]
Hmm. this could indeed be part of the issue.  I suppose a workaround is just that it could be possible to implement some logic that when `Item` has been selected, then focus and highlight the `Description` field for that line in context. After this occurs tab works fine in the current situation.

Freshbooks, for example, works like this and it is convenient since it seems that usually the person doing data entry usually uses the mouse to select the `Item` type due to frequently having to look at the options and scroll through (eg, I have 15 or more different `Item` types to select from due to various project contexts).

**Comment by hillelcoren** [comment]
This has been implemented, thanks again for the suggestion!
