### ISSUE TITLE
Feature Request :: customize invoice entry :: allow for customization of invoice line item column order and items

### ISSUE THREAD

**Issue by ylluminate** [invoiceninja/admin-portal#278]
v5 :: Hosted (invoicing.co)
As per [this forum post](https://forum.invoiceninja.com/t/v5-feature-request-refinements-in-products-items-description-entry-etc/7075).

The following columns and order are more convenient for my industry and it would be nice to be able to facilitate customization of the columns and their order for entry:
![example](https://p153.p0.n0.cdn.getcloudapp.com/items/v1uYKwGx/ad3e5bc9-0d73-43d8-bd83-e9a0fc2fd714.jpg?v=cbb7d9e8f4dfb31201317ef217243b92)

The system currently looks like this:
![current](https://p153.p0.n0.cdn.getcloudapp.com/items/Wnuxzjg5/86b70da1-8022-43de-b064-c45305660c82.jpg?v=603d1714b8a25c7c1a671c6e2b720f7e)

Please notice the order and additional columns / attributes.

Could you please allow us to change the order of fields and add appropriate fields for the invoice Item presentation during data entry?  As you can see from my example, I’d like to have these items in the following order: `Quantity`, `Item`, `Description`, `Unit Price`, `Discount`, `Tax` and `Line Total` since it feels more natural and makes work flow better for us.

**Comment by hillelcoren** [comment]
The app supports ordering the columns on the PDF on Settings > Invoice Designs.

Would it be useful to have the invoice edit UI match the PDF fields or does it need its own order?

**Comment by ylluminate** [comment]
Well, I guess you could kind of say yes to your question there, but I would consider this kind of being a "reversed" thought process in that the UI drives the PDF output. For example, in the UI whilst editing the fields, if I insert a discount value then that column would then appear in the PDF, but if all discount values are `0` in the UI data entry, then the PDF would not even show that column... 

I guess you would say the same is true for tax (normally with taxes, for example, I never use a tax value within the individual items due to most things are the same unless I am dealing with an actual part for which I need reimbursement).

I hope I'm being clear and I'm saying you're wrong in your statement - just thinking, in my mind, the business logic is reversed for this in terms of the flow of data.

**Comment by borisbl** [comment]
Upvote!

**Comment by boka003** [comment]
Hello,

This is really needed!
I hope that admins will add this in some of next relases.

Best regards

**Comment by ylluminate** [comment]
@hillelcoren how are we doing here?

**Comment by hillelcoren** [comment]
When we have updates we post them, please refrain from asking as it notifies all people watching the issue.

**Comment by ylluminate** [comment]
Didn't mean to cause you a problem @hillelcoren - was just hoping for a collective update since others are asking and we've been in a holding pattern from using our ongoing subscription due to various issues.

**Comment by boka003** [comment]
Hello,

Can you please provide us some ETA for this?

I hope that we can start using V5 at start of 2022.


Regards
