### ISSUE TITLE
v5 Invoice Design Editor Broken

### ISSUE THREAD

**Issue by plwc** [invoiceninja/admin-portal#279]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
5.1.65

**What environment are you running?**
Shared Hosting

**Have you searched existing issues?**
Yes

**Have you reported this to Slack/forum before posting?**
No

**Describe the bug**
The cursor position in the editing window get more and more out of line the further you go down. In the screenshot I've highlighted the text and it shows off the problem really well. By the time you get to the end of this code it's out of wack by many lines.

**Steps To Reproduce**
Go to the invoice design area and try to edit the code.

**Expected behavior**
I expect the cursor edit the area you click on.

**Screenshots**
![image](https://user-images.githubusercontent.com/44763211/120426588-8734a700-c3af-11eb-9472-0aa2b00adcf8.png)

**Additional context**
I'm using Firefox 78.10.0esr with no plugins and all privacy settings disabled on Debian 10.

Note: Before posting don't forget to check our "Troubleshooting" category in the [docs](https://invoiceninja.github.io/docs/self-host-troubleshooting/) (https://invoiceninja.github.io/docs/self-host-troubleshooting/).

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**
Yes

**Comment by hillelcoren** [comment]
Thanks for reporting this!

It's most like a problem with the underlying framework we're using, hopefully it will be improved in the future.

**Comment by hillelcoren** [comment]
Closing in favor of this issue:

https://github.com/invoiceninja/admin-portal/issues/170#issuecomment-813972916
