### ISSUE TITLE
Not auocompleting / auto fillin of products

### ISSUE THREAD

**Issue by gregoryvanhout** [invoiceninja/admin-portal#280]
**What version of Invoice Ninja are you running? after git pull latest

**What environment are you running?** dedicated server

**Have you checked log files (storage/logs/) Please provide redacted output** no error found

**Have you searched existing issues?** yes, no solution

**Have you reported this to Slack/forum before posting?** no

**Describe the bug**
When starting to type a product name the product is found but when you click on the product nothing happens, no fields are set to the product properties

**Steps To Reproduce** just installed the latest version ( clean install as discribed on the documentation )

**Expected behavior** change of the fields with the properties of the product like VAT,discription,price ......

**Screenshots** no sceenshot 

**Additional context**

Note: Before posting don't forget to check our "Troubleshooting" category in the [docs](https://invoiceninja.github.io/docs/self-host-troubleshooting/) (https://invoiceninja.github.io/docs/self-host-troubleshooting/).

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**

**Comment by hillelcoren** [comment]
Hi,

Can you please confirm "Fill products" is enabled on Settings > Product Settings
