### ISSUE TITLE
Add autocomplete="one-time-code" to login form OTP field (compatibility with password managers)

### ISSUE THREAD

**Issue by zaxbux** [invoiceninja/admin-portal#293]
**What version of Invoice Ninja are you running? ie v4.5 / v5**
v5

**What environment are you running?**
Docker

**Have you searched existing issues/requests?**
Yes

**Screenshots**
![invoice-ninja-otp](https://user-images.githubusercontent.com/5186921/121939206-9bf33200-cd01-11eb-9fd7-1d2a932e3669.png)
Screenshot taken after editing the login form with the browser inspector (moved one time code input to the form element and added proper autocomplete attribute). One Time Password was auto-filled by my password manager (1Password).

**Additional context**
The current login form doesn't fully support password managers (only autofills username/password). For full support, the One Time Password `<input>` should be contained within a `<form>` element, and have the `autocomplete="one-time-code"` attribute set (see https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete).

**Comment by hillelcoren** [comment]
Thanks for reporting this, I've checked in a change which should help.
