### ISSUE TITLE
Product custom fields are not being translated in reports by product

### ISSUE THREAD

**Issue by gfpalacios** [invoiceninja/admin-portal#294]
**What version of Invoice Ninja are you running? 
v5.1.65**

**What environment are you running?**
ZIP

**Have you searched existing issues?**
Yes

**Have you reported this to Slack/forum before posting?**
no

**Describe the bug**
Custom fields are not taken into account for Products reports. This is not an issue in clients for example.

**Steps To Reproduce**
1) Create a custom field for Products, Custom Field 1, 2 and 3. 
2) Go to reports, select by Product in drop down button. 
3) Click on add columns, you will see right away, custom fields are not translated and they are shown as "Custom value 1".
4) After saving those custom fields as new columns in your report, you will see the report with this labels.

**Expected behavior**
You should see a translated value of your custom field.

**Screenshots**
![Selection_004](https://user-images.githubusercontent.com/7843222/122229264-983ce800-ce86-11eb-84a3-bae4fa3943c4.png)

then..
Reports by products:
![Selection_005](https://user-images.githubusercontent.com/7843222/122229327-a2f77d00-ce86-11eb-97bb-ad54363b9068.png)

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**
I couldn't find the custom fields settings. I'd like to try it.

**Comment by hillelcoren** [comment]
Thanks for reporting this, we'll include a fix in the next release.

Note: you'll need to add back the custom fields in the report.
