### ISSUE TITLE
Edit Invoice (and similar) difficult to read - could you offer options to alter colors/layout?

### ISSUE THREAD

**Issue by kwoodall** [invoiceninja/admin-portal#295]
I happen to have a nice trifecta of astigmatism, nearsightedness and farsightedness amongst other issues. The new V5 displays being primarily white on white are more difficult to read without the color cues V4's screens had.

If you don't want to revert the layouts, which is understandable, what about offering options to let us theme the layout? 

Personally I would like to be able to make the list of invoices/payments/etc have the alternating color/shade that it had in V4. 

In the Edit Invoice screen I would like to have a darker background behind the header text/row for the billed items, I'd like to have a border around entry areas, I'd like the View PDF/Email Invoice/etc able to appear on the top bar with Cancel/Save, and control colors for other items as well.

I'd also like to be able to have the grey background behind the leftmost menu like v4.

Even if this were just a set of CSS options we could fill out in Settings - that would be wonderful!

**Comment by hillelcoren** [comment]
This is really good feedback, thank you!

**Comment by hillelcoren** [comment]
In the next version we've added the ability to set custom colors for the admin portal theme

![image](https://user-images.githubusercontent.com/4629496/127104209-0212413e-aa29-468d-8044-362cfa42a36d.png)

**Comment by kwoodall** [comment]
Can you show where and how this is edited? Also, what version # will this been and possibly when? Whatever you're able to let us know. And thanks so much!

**Comment by hillelcoren** [comment]
It should be available within a few days.

![image](https://user-images.githubusercontent.com/4629496/127207155-7e4eccc7-959c-4c2f-bf97-443465e9eeb5.png)

**Comment by kwoodall** [comment]
Thank you so much! 

Kermit

**Comment by kwoodall** [comment]
Just got to try this out today! Thanks! Is there a way to directly enter a color? There's no light grey or white color options. 

Thanks again!

Kermit

**Comment by hillelcoren** [comment]
You can either type in the hex code or click the color swatch to use the picker.

**Comment by kwoodall** [comment]
Aha. I just discovered this, although it won't let you type in the color until you clear the existing color.

**Comment by kwoodall** [comment]
Now that I know this it's great! Thanks again!

**Comment by hillelcoren** [comment]
Thanks again for your feedback, I think it's a big improvement!

**Comment by kwoodall** [comment]
I just replaced my old computer and when I logged into invoicing.co with the new one all these color settings had reset to the defaults!

**Comment by hillelcoren** [comment]
The options under device settings are specific to the device
