### ISSUE TITLE
not adding products when clicking on the product

### ISSUE THREAD

**Issue by gregoryvanhout** [invoiceninja/admin-portal#296]
**What version of Invoice Ninja are you running? v5.2.6-C51

**What environment are you running?** Dedicated Hosting

**Have you checked log files (storage/logs/) Please provide redacted output** no output in logs

**Have you searched existing issues?** yes

**Have you reported this to Slack/forum before posting?** no

**Describe the bug**
When typing for a product, the product list appears but can't add the product info by clicking on the product, 
All options are enabled in product settings, when typing in prodict id field for adding a product to the invoice, you see the options but not able to add them, fullin option is enabled, tested in chrome and edge

**Steps To Reproduce**
Please list the steps to reproduce the issue
default installation, 

**Expected behavior**
the product info is added to the invoice

**Screenshots**

![image](https://user-images.githubusercontent.com/74876572/123509461-faab9a80-d675-11eb-8505-4f471c73c988.png)

**Additional context**
i have installed 3 in the past, and upgraded them to newest version, old and new version are 5.XXX
i have installed a new one from scratch as discribe on the install page and this issue popped up, reinstalled the application, no luck, i installed a 2th new install for a new client and the same issue is there, checked all the fields and settings as my own working version, all are the same

Note: Before posting don't forget to check our "Troubleshooting" category in the [docs](https://invoiceninja.github.io/docs/self-host-troubleshooting/) (https://invoiceninja.github.io/docs/self-host-troubleshooting/).

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**

No, this issue is not active when you do an upgrade from a older version, this is the case for new installations

**Comment by gregoryvanhout** [comment]
When i reopen a quote where i entered for the first time a product, it is filled in auto, when creating a new qoute/invoice is refuses to add the product

**Comment by hillelcoren** [comment]
Hi,

I think the demo server is now running the latest version, can you please re-check if you see the problem there?

**Comment by gregoryvanhout** [comment]
Is that a new installation from scratch or upgrade, the situation is only active when it is a new installation not wit a upgrade



Sent from my Galaxy



-------- Original message --------
From: Hillel Coren ***@***.***>
Date: 6/26/21 20:13 (GMT+01:00)
To: invoiceninja/admin-portal ***@***.***>
Cc: gregoryvanhout ***@***.***>, Author ***@***.***>
Subject: Re: [invoiceninja/admin-portal] not adding products when clicking on the product (#296)


Hi,

I think the demo server is now running the latest version, can you please re-check if you see the problem there?

**Comment by hillelcoren** [comment]
It's been upgraded to the latest version.

I can't think of any reason why a new install would behave differently than an updated one.

**Comment by gregoryvanhout** [comment]
Yes i know, but i have my own and its upgraded there it works, 2 of my clients use a upgraded version, yesterday i installed 2 new ones for 2 clients and those 2 had this issue, so i know it sounds weird but that is realy the case



Sent from my Galaxy



-------- Original message --------
From: Hillel Coren ***@***.***>
Date: 6/26/21 20:42 (GMT+01:00)
To: invoiceninja/admin-portal ***@***.***>
Cc: gregoryvanhout ***@***.***>, Author ***@***.***>
Subject: Re: [invoiceninja/admin-portal] not adding products when clicking on the product (#296)


It's been upgraded to the latest version.

I can't think of any reason why a new install would behave differently than an updated one.

**Comment by hillelcoren** [comment]
I suggest checking if updating help.

If I'm not able to reproduce the problem myself it will be hard for me to help.

**Comment by gregoryvanhout** [comment]
Dear,

Is it possible to have a private coversation,
I can send you cedentals of a test env



Sent from my Galaxy



-------- Original message --------
From: Hillel Coren ***@***.***>
Date: 6/26/21 21:03 (GMT+01:00)
To: invoiceninja/admin-portal ***@***.***>
Cc: gregoryvanhout ***@***.***>, Author ***@***.***>
Subject: Re: [invoiceninja/admin-portal] not adding products when clicking on the product (#296)


I suggest checking if updating help.

If I'm not able to reproduce the problem myself it will be hard for me to help.

**Comment by hillelcoren** [comment]
Sorry, our policy is not to access our user's servers

**Comment by gregoryvanhout** [comment]
Can you start a demo2 env with a clean install of the application and test is

You create a quote with products that are entered for the first time and then you create a second one with the same products, you will see them but you wont be able to select them



Sent from my Galaxy



-------- Original message --------
From: Hillel Coren ***@***.***>
Date: 6/26/21 22:30 (GMT+01:00)
To: invoiceninja/admin-portal ***@***.***>
Cc: gregoryvanhout ***@***.***>, Author ***@***.***>
Subject: Re: [invoiceninja/admin-portal] not adding products when clicking on the product (#296)


Sorry, our policy is not to access our user's servers

**Comment by hillelcoren** [comment]
If this problem was present in a clean install I would expect other users to report it, I'm happy to leave this issue open for a bit to check if anyone else is seeing this problem.

**Comment by gregoryvanhout** [comment]
Is there another way to test or check what the issue is?

**Comment by hillelcoren** [comment]
You could try more installs/updates to confirm your hypothesis?

**Comment by gregoryvanhout** [comment]
Ok i could but 3 upgrades are working and 2 new installs not that is already a sign not, please you have servers to for the demo, you could install a dev env and test a new install please, maybey i forvot somting to do



Sent from my Galaxy



-------- Original message --------
From: Hillel Coren ***@***.***>
Date: 6/27/21 09:56 (GMT+01:00)
To: invoiceninja/admin-portal ***@***.***>
Cc: gregoryvanhout ***@***.***>, Author ***@***.***>
Subject: Re: [invoiceninja/admin-portal] not adding products when clicking on the product (#296)


You could try more installs/updates to confirm your hypothesis?

**Comment by hillelcoren** [comment]
I suggest checking if updating the new installs resolves the problem. If this is a problem in the app other people will report it (it's a noticeable feature). The problem could be related to the specific data in the account.

**Comment by gregoryvanhout** [comment]
Dear, it is currenty the latest version, how can I upgrade the version?

**Comment by hillelcoren** [comment]
A new version will be available within a few days

**Comment by gregoryvanhout** [comment]
A ok super let me know I will upgade asap.

**Comment by gregoryvanhout** [comment]
Dear,

Tested again,
If you save an empty invoice, and open it again auto complete of the products work.
When creating a new without saving it does not word

**Comment by hillelcoren** [comment]
Are you able to reproduce this problem in the demo?

https://demo.invoiceninja.com

**Comment by gregoryvanhout** [comment]
no, it is strange, 
i will check the logs

**Comment by gregoryvanhout** [comment]
Dear,

This is all that I can find

Chrome console:
***@***.***D76FFF.D34DBDB0]


Laravel Logs:
[2021-07-03 09:25:02] production.INFO: latest version = 5.2.9
[2021-07-03 09:30:02] production.INFO: latest version = 5.2.9
[2021-07-03 09:35:03] production.INFO: latest version = 5.2.9

**Comment by gregoryvanhout** [comment]
Never Mind,
Fixed in version after upgrading to 5.2.9

**Comment by gregoryvanhout** [comment]
Not all instances are solved,
The new installed once still have the issue


***@***.***D77000.F3BD0140]

[2021-07-03 09:40:02] production.ERROR: file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 {"exception":"[object] (ErrorException(code: 0): file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 at /usr/www/users/idvision/COMMON/FINANCE/app/Jobs/Util/VersionCheck.php:37)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'file_get_conten...', '/usr/www/users/...', 37, Array)
#1 /usr/www/users/idvision/COMMON/FINANCE/app/Jobs/Util/VersionCheck.php(37): file_get_contents('https://pdf.inv...')
#2 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\Util\\VersionCheck->handle()
#3 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#5 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#6 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Container/Container.php(614): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#7 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call(Array)
#8 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(App\\Jobs\\Util\\VersionCheck))
#9 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\Util\\VersionCheck))
#10 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#11 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(120): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\Jobs\\Util\\VersionCheck), false)
#12 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}(Object(App\\Jobs\\Util\\VersionCheck))
#13 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\Util\\VersionCheck))
#14 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#15 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\\Queue\\Jobs\\SyncJob), Object(App\\Jobs\\Util\\VersionCheck))
#16 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\SyncJob), Array)
#17 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(43): Illuminate\\Queue\\Jobs\\Job->fire()
#18 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(253): Illuminate\\Queue\\SyncQueue->push(Object(App\\Jobs\\Util\\VersionCheck))
#19 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(229): Illuminate\\Bus\\Dispatcher->pushCommandToQueue(Object(Illuminate\\Queue\\SyncQueue), Object(App\\Jobs\\Util\\VersionCheck))
#20 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(77): Illuminate\\Bus\\Dispatcher->dispatchToQueue(Object(App\\Jobs\\Util\\VersionCheck))
#21 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php(202): Illuminate\\Bus\\Dispatcher->dispatch(Object(App\\Jobs\\Util\\VersionCheck))
#22 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php(17): Illuminate\\Foundation\\Bus\\PendingDispatch->__destruct()
#23 /usr/www/users/idvision/COMMON/FINANCE/app/Jobs/Util/SchedulerCheck.php(72): App\\Jobs\\Util\\VersionCheck::dispatch()
#24 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\Util\\SchedulerCheck->handle()
#25 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#26 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#27 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#28 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Container/Container.php(614): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#29 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call(Array)
#30 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(App\\Jobs\\Util\\SchedulerCheck))
#31 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\Util\\SchedulerCheck))
#32 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#33 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(120): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\Jobs\\Util\\SchedulerCheck), false)
#34 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}(Object(App\\Jobs\\Util\\SchedulerCheck))
#35 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\Util\\SchedulerCheck))
#36 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#37 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\\Queue\\Jobs\\SyncJob), Object(App\\Jobs\\Util\\SchedulerCheck))
#38 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\SyncJob), Array)
#39 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(43): Illuminate\\Queue\\Jobs\\Job->fire()
#40 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(253): Illuminate\\Queue\\SyncQueue->push(Object(App\\Jobs\\Util\\SchedulerCheck))
#41 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(229): Illuminate\\Bus\\Dispatcher->pushCommandToQueue(Object(Illuminate\\Queue\\SyncQueue), Object(App\\Jobs\\Util\\SchedulerCheck))
#42 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(77): Illuminate\\Bus\\Dispatcher->dispatchToQueue(Object(App\\Jobs\\Util\\SchedulerCheck))
#43 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Console/Scheduling/Schedule.php(172): Illuminate\\Bus\\Dispatcher->dispatch(Object(App\\Jobs\\Util\\SchedulerCheck))
#44 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Console/Scheduling/Schedule.php(142): Illuminate\\Console\\Scheduling\\Schedule->dispatchToQueue(Object(App\\Jobs\\Util\\SchedulerCheck), NULL, NULL)
#45 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Console\\Scheduling\\Schedule->Illuminate\\Console\\Scheduling\\{closure}()
#46 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Closure->__invoke()
#47 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#48 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#49 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#50 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Container/Container.php(614): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#51 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Console/Scheduling/CallbackEvent.php(79): Illuminate\\Container\\Container->call(Array, Array)
#52 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Console/Scheduling/ScheduleRunCommand.php(143): Illuminate\\Console\\Scheduling\\CallbackEvent->run(Object(Illuminate\\Foundation\\Application))
#53 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Console/Scheduling/ScheduleRunCommand.php(102): Illuminate\\Console\\Scheduling\\ScheduleRunCommand->runEvent(Object(Illuminate\\Console\\Scheduling\\CallbackEvent))
#54 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Console\\Scheduling\\ScheduleRunCommand->handle(Object(Illuminate\\Console\\Scheduling\\Schedule), Object(Illuminate\\Events\\Dispatcher), Object(App\\Exceptions\\Handler))
#55 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#56 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#57 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#58 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Container/Container.php(614): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#59 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call(Array)
#60 /usr/www/users/idvision/COMMON/FINANCE/vendor/symfony/console/Command/Command.php(288): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#61 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#62 /usr/www/users/idvision/COMMON/FINANCE/vendor/symfony/console/Application.php(974): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#63 /usr/www/users/idvision/COMMON/FINANCE/vendor/symfony/console/Application.php(291): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Console\\Scheduling\\ScheduleRunCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#64 /usr/www/users/idvision/COMMON/FINANCE/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#65 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#66 /usr/www/users/idvision/COMMON/FINANCE/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#67 /usr/www/users/idvision/COMMON/FINANCE/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#68 {main}
"}

Changed server config

allow_url_fopen
allow_url_include

still not fixed

**Comment by hillelcoren** [comment]
This appears to be a configuration issue, if you need more help please post to the forum

https://forum.invoiceninja.com
