### ISSUE TITLE
Where can I get the app code which supports self hosted v4.5?

### ISSUE THREAD

**Issue by arslannawaz** [invoiceninja/admin-portal#297]
My self hosted version is v4.5. The current master branch of this repo/app do not supports self hosted v4.5. It requires v5. so is there any solution or a way to get the code of app which supports self hosted version 4.5. What about legacy branch? Will it support? or what do you say? or do I have to update my self hosted version from 4.5 to 5?

![ninja-app-v5](https://user-images.githubusercontent.com/46641425/123973803-85252e80-d9d5-11eb-9b63-9a923bbd9e32.jpeg)

**Comment by hillelcoren** [comment]
Is there a reason you're building the app rather than using the app from the store?

**Comment by arslannawaz** [comment]
Just want to update few things.

**Comment by arslannawaz** [comment]
> Is there a reason you're building the app rather than using the app from the store?

Just want to update few things.

**Comment by hillelcoren** [comment]
The v4 code is available on the legacy branch but it probably requires a much older version of Flutter to compile.

**Comment by hillelcoren** [comment]
Yes, v5 is stable

**Comment by arslannawaz** [comment]
> Yes, v5 is stable

And should I use 'v5-stable' branch for that?

**Comment by hillelcoren** [comment]
Yup

**Comment by arslannawaz** [comment]
> Yup

Thanks :)
