### ISSUE TITLE
Expenses: Ability to calculate Exchange Rate by inputting Converted amount.

### ISSUE THREAD

**Issue by atajsic** [invoiceninja/admin-portal#300]
**What version of Invoice Ninja are you running? ie v4.5 / v5**
v5

**What environment are you running?**
Docker

**Have you searched existing issues/requests?**
Yes

**Additional context**
Expenses

I'm pretty sure in version 4 I was able to put in the foreign price, and the converted price, and it would work out the exchange rate for me.

In version 5, I can only put in the foreign price, and the exchange rate... 

The exchange rate changes daily, and so I merely cross reference my bank statements while I do the expenses to input the converted amount. At the moment I have to manually do this in a spreadsheet, then input that exchange rate number instead.

It would be good to put in either the converted amount, or the exchange rate, and it would populate / calculate the other. 

Thank you for your consideration.

**Comment by hillelcoren** [comment]
My mistake, there is an option to set taxes by the final amount but not the converted amount.

We'll look into adding this.

**Comment by atajsic** [comment]
Thanks!

**Comment by hillelcoren** [comment]
This has been implemented,, it will be included with the next release

**Comment by atajsic** [comment]
Thanks! :)
