### ISSUE TITLE
Invoice/quote line item 'Show menu' icon invisible at narrow window width

### ISSUE THREAD

**Issue by hmnd** [invoiceninja/admin-portal#302]
The `Show menu` kebab icon next to each invoice or quote line item has turned invisible as of at least v5.2.11. I've been able to reproduce this with both the dark and light theme.

[Screen recording](https://user-images.githubusercontent.com/12853597/126433332-f597931b-9c1a-4d7b-8090-53738d992339.mp4)

**Comment by hmnd** [comment]
It seems that this is a weird issue to do with responsive layout. Below a certain width, the kebab icon gets moved out of place and eventually disappears; eventually, along with the button containing it. See the screen recording below.

[Screen recording](https://user-images.githubusercontent.com/12853597/126435828-eea327d0-4fd7-4283-996f-59429f14ab8d.mp4)

**Comment by hillelcoren** [comment]
Thanks, there's definitely a problem. Have you always been using the line item tax and discount columns or were they recently added, it could help explain the problem.

**Comment by hmnd** [comment]
@hillelcoren I did enable a per-item tax recently and I think that's why I've only noticed it now. With that column removed, the issue still occurs but at a narrower width (icon disappears at ~1185px, compared to ~1400px with tax column).

**Comment by hillelcoren** [comment]
Got it, thanks for the info!

**Comment by hillelcoren** [comment]
Thanks for reporting this, it should be corrected in the next release.
