### ISSUE TITLE
Invoice List by n Invoices

### ISSUE THREAD

**Issue by kwoodall** [invoiceninja/admin-portal#305]
V4 let you choose a number of invoices to view at one time. V5 does not. Could you add a setting to let us choose how many invoices, recurring invoices, clients, etc we see at one time?

Thanks!

**Comment by hillelcoren** [comment]
Not sure I understand this. 

Do you mean the number of rows shown in the datatables? This can be configured on Settings > Device Settings.

**Comment by kwoodall** [comment]
Yep. I just found this today. Thanks and I'm really enjoying v5 now!

**Comment by hillelcoren** [comment]
Awesome, really glad to hear it!
