### ISSUE TITLE
Can't build app due version solving failed

### ISSUE THREAD

**Issue by zolkiBy** [invoiceninja/admin-portal#306]
Try to run build admin-portal on Windows 10 machine and Android Studio Arctic Fox, but it fails
![image](https://user-images.githubusercontent.com/12282866/127736101-a6f7bfdd-d65d-468c-aee2-185cc86c945f.png)

**Comment by hillelcoren** [comment]
We're currently using Flutter 2.0.6 which probably explains the problem.

Is there a reason you're building the app from code, are you planning to resell it?

**Comment by zolkiBy** [comment]
Thanks for explanation. No, I don't plan to recell it. I'm Flutter enthusiast and only interest in your approach. I think your app one of the most interesting open source big apps which use Redux architecture. I use your code only for learning purpose)

**Comment by hillelcoren** [comment]
Ok, sounds good.

FYI.. we plan to upgrade to the latest version of Flutter soon.

**Comment by zolkiBy** [comment]
ok, thanks for the info, waiting for update)
