### ISSUE TITLE
Localization problem / commat - dot float parsing

### ISSUE THREAD

**Issue by tixsys** [invoiceninja/admin-portal#307]
v 5.2.16, latest flutter

Create task -> press Invocie Task -> in opened New Invocie window go to Items, click on edit.  You will see somethign like 0,123 in quantity. if u change it to 0,2 then quantity will be reset. as it shows Quantity with comma, and when saved tries to parse dot as float separator.

**Comment by hillelcoren** [comment]
Thanks for reporting this, it should be corrected in the next release.
