### ISSUE TITLE
when cloning tasks - logged time and project not copied.

### ISSUE THREAD

**Issue by tixsys** [invoiceninja/admin-portal#308]
5.2.16 invoice ninja, latest flutter

Create some task, add time there. make invoice.. now i want to change client.. i clone the task and see that data is not cloned (project name, time logged items).

**Comment by hillelcoren** [comment]
In my test the project name is included in the clone, since a project is linked to a client if you remove the client it will also remove the project.

The time details weren't being brought over, this was by design but I've changed the behavior.
