### ISSUE TITLE
Recurring invoice Bad sorting on date

### ISSUE THREAD

**Issue by Freshou** [invoiceninja/admin-portal#310]
In recurring invoice, if we ask to sort recurring invoice by "next Send date", the sorting order doesn't work correctly ...

**Comment by Freshou** [comment]
Using Self Hosted version, v5.2.17-M42 ... 

Do a resource is necessary on the Web Server the the sorting to Work ??? i can send Screenshot or video if required !

**Comment by hillelcoren** [comment]
Downloading the latest version of the macOS app should help:

https://download.invoiceninja.com/macos

Note: in the future please use the issue template.

**Comment by Freshou** [comment]
I confirm that the update of the MacOS App corrected the problem ! 
Thanx !
