### ISSUE TITLE
Default to last selected company when re-opening app or website

### ISSUE THREAD

**Issue by jinjie** [invoiceninja/admin-portal#311]
## Version

v5.2.17-C56

## Problem

- I have created 2 company in a single installation (Company A and Company B). Company B was the last created one.
- When working on Company A and close the app, regardless of Desktop, Mobile or Web. Close and reopen the app will defaulted to the last created company (Company B) instead of Company A. 

## Recreate

- Create a new company
- Select another company from top left corner.
- Close desktop app, mobile or web
- Open desktop app, mobile or web

**Comment by jinjie** [comment]
> Hi,
> 
> Are the companies large/roughly how many invoices do you have?

2 Companies.

Company A have 400 invoices and 34 recurring invoice.
Company B have 0 invoice.

Created the second company to get ready for a new business I am preparing to start. Did I infringe any of the license?

**Comment by hillelcoren** [comment]
Thanks for the info, I was curious if maybe a large amount of data was causing the problem. 

No, you can have up to 10 companies registered to your account.

**Comment by jinjie** [comment]
Good to know! Let me know if you need more information..

It's not a deal breaker for such an amazing app. But still quite annoying that the app default to the last created company whenever I start the app on web, desktop or mobile.

**Comment by hillelcoren** [comment]
Can you please check if logging out and then back in helps

**Comment by hillelcoren** [comment]
This should be resolved in the next version

**Comment by jinjie** [comment]
Seem to have fixed after upgrading. Closing this issue.

**Comment by hillelcoren** [comment]
Glad to hear it, thanks for the update!
