### ISSUE TITLE
Invoice status 'Viewed' does not work

### ISSUE THREAD

**Issue by stefaandevylder** [invoiceninja/admin-portal#312]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.2.17-C56

**What environment are you running?**
Shared Hosting

**Have you checked log files (storage/logs/) Please provide redacted output**
No logs about this

**Have you searched existing issues?**
Yes

**Have you reported this to Slack/forum before posting?**
No

**Describe the bug**
There is no 'Viewed' status anymore when a customer checks the invoices.

**Steps To Reproduce**
/

**Expected behavior**
/

**Screenshots**
/

**Additional context**
/

Note: Before posting don't forget to check our "Troubleshooting" category in the [docs](https://invoiceninja.github.io/docs/self-host-troubleshooting/) (https://invoiceninja.github.io/docs/self-host-troubleshooting/).

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**
Yes

**Comment by hillelcoren** [comment]
Thanks, understood

**Comment by hillelcoren** [comment]
This should be correct in the next release, thanks for reporting it!
