### ISSUE TITLE
Task Overview does not respect localized time settings for date/time

### ISSUE THREAD

**Issue by devotoare** [invoiceninja/admin-portal#315]
When editing a task today I had a task end at 8:45pm local. This all looks fine and normal when editing. However when moving to the overview screen the date is tomorrow unless I change the time back a few hours (I'm in Pacific so If I move it back 6/7 hours it seems to be fine).

Example:
![Capture](https://user-images.githubusercontent.com/5583396/129517867-0d15f03b-ccfa-403c-9758-a9881b1cadb2.PNG)
![Capture2](https://user-images.githubusercontent.com/5583396/129517870-4021b960-01e8-4e95-bd7d-06217543ca1b.PNG)

**Comment by hillelcoren** [comment]
There's clearly a problem but I haven't been able to replicate it yet.

The app uses the device timezone, is it possible it's different than the setting on Settings > Localization? 

Also, which state are you in? Maybe it's a daylight savings issue.

**Comment by hmnd** [comment]
@hillelcoren I'm experiencing a similar issue here too. Reproduced on the demo instance today at ~22:40 PDT (British Columbia, Canada, so daylight saving applies). Strangely, this only seems to affect the date, and only in the overview display.

Here's a recording, if that helps:

https://user-images.githubusercontent.com/12853597/132084125-61a47208-5e75-4378-ac73-eb886871df30.mp4
