### ISSUE TITLE
Fancy icon bugs after update

### ISSUE THREAD

**Issue by itkfm** [invoiceninja/admin-portal#316]
After updating to: v5.2.19-C58

![image](https://user-images.githubusercontent.com/53079668/129914856-fe2626bb-85bc-4ff8-bf85-6b38fb075f8d.png)
![image](https://user-images.githubusercontent.com/53079668/129914888-ca6308b7-5bbf-4625-a0ed-91c5bead92e3.png)
![image](https://user-images.githubusercontent.com/53079668/129914931-6ed5c7be-bbb9-436c-88ad-854523831ec4.png)

Workaround: manually clear browser caches

Also had this after the v5.2.18 update, with a nice bonus: the loading marquee bar would not go away and constantly move around although loading was finished

My browser: Firefox 91
OS: GNU/Linux (Ubuntu 20.04)

**Comment by hillelcoren** [comment]
I believe this is a bug in the framework we're using, more info here: https://github.com/flutter/flutter/issues/83703
