### ISSUE TITLE
Feeling unresponsive

### ISSUE THREAD

**Issue by itkfm** [invoiceninja/admin-portal#317]
Selfhosted (ZIP) v5.2.19-C58

This version feels really unresponsive here (on several machines, using several accounts).
It hangs e.g. when saving things.

Timings:
1. Let’s imagine we press the Save button in the invoice editor.
![image](https://user-images.githubusercontent.com/53079668/130249710-82165794-951b-4ae1-af3e-650cb52c9156.png)
2. The first PUT-request would get sent immediately and be done in about 1 second, which feels pretty performant as usual.
3. But afterwards it takes several seconds (usually more than 10) until the the second (POST) request is even sent. Once it’s through, it will receive the response almost immediately.<br/> ![image](https://user-images.githubusercontent.com/53079668/130250424-bc7d2d9f-cb46-49cb-bc82-b83e43982ae9.png)

<details>
<summary>Not sure whether related:</summary>

![image](https://user-images.githubusercontent.com/53079668/130248601-1fabcaf5-450d-49ec-8e25-117bc189c509.png)

![image](https://user-images.githubusercontent.com/53079668/130250819-91c62465-c12d-4aa2-88d3-0bd0b4810f29.png)

</details>

**Comment by hillelcoren** [comment]
Thanks for reporting this!

I think this should be corrected in the next release but please let us know if it isn't.

**Comment by hillelcoren** [comment]
When you have a chance I'm curious to know if v5.3.0 helps with this issue. 

https://github.com/invoiceninja/invoiceninja/releases

**Comment by itkfm** [comment]
seems like it’s fixed, at least for me.
Let’s see what my colleagues say. Will let you know…

**Comment by hillelcoren** [comment]
Awesome, glad to hear it :)

FYI.. I think the problem was related to persistence, where the app tries to save the state locally to make restarts quicker. In the next release we've added an option to disable the feature on Settings > Device Settings which for large accounts can help.

**Comment by itkfm** [comment]
yeah, I see it. It’s disabled here.

It’s been a while (+ a few updates) since the last time I’ve encountered this issue.
we’ll see… Maybe it’s resolved.
