### ISSUE TITLE
123,00 saved as 12300,00

### ISSUE THREAD

**Issue by itkfm** [invoiceninja/admin-portal#318]
v5.3.0-C58 (zip)

If I save an invoice (or the global task hourly rate) as `123,00` format, it’s saved as `12300,00`, which is horribly wrong.
If I save an invoice (or the global task hourly rate) as `123`, it’s saved as `123,00`, which is fine.

<details>
<summary>Localisation settings</summary>

![image](https://user-images.githubusercontent.com/53079668/130805277-e66f2e64-3f2b-48ef-ac7b-0300acd95c19.png)

</details>

**Comment by hillelcoren** [comment]
We've added a new 'decimal comma' option on Settings > Account Management
