### ISSUE TITLE
Add fee calculation back in V5

### ISSUE THREAD

**Issue by mrkylegp** [invoiceninja/admin-portal#322]
**What version of Invoice Ninja are you running? ie v4.5 / v5**
V5.3.5

**What environment are you running?**
Self Hosted

**Have you searched existing issues/requests?**
Yes

**Screenshots**
V4
![bringback](https://user-images.githubusercontent.com/52687659/131817119-f0eaa8e2-c155-4362-a4aa-50ec383c922a.png)

V5
![nocalc](https://user-images.githubusercontent.com/52687659/131817191-6619df75-c8cb-4e8d-a7ba-8095792ed1e9.png)

**Additional context**
There used to be a handy calculation of the fee based on the fields entries. It would be nice to have this back in V5.

**Comment by hillelcoren** [comment]
I suggest creating this as a separate issue, the main point is for the admin portal whereas this is the client portal.

**Comment by mrkylegp** [comment]
> I suggest creating this as a separate issue, the main point is for the admin portal whereas this is the client portal.

Sure, glad to :)
