### ISSUE TITLE
Constant high CPU usage in beta Windows app

### ISSUE THREAD

**Issue by hmnd** [invoiceninja/admin-portal#324]
The native Invoice Ninja app for Windows seems to be hogging a constant 15-20% of my CPU. Can provide logs or further details that might help; just let me know.

![image](https://user-images.githubusercontent.com/12853597/131968274-7bf35775-a17e-41ba-ac56-2dac9317b148.png)

**Comment by hillelcoren** [comment]
Thanks for reporting this, I'm seeing the same thing.

It looks like this may help (https://github.com/flutter/flutter/issues/85745#issuecomment-908099839), we'll include the change with our next release.

**Comment by hmnd** [comment]
@hillelcoren Any idea when the next release for Windows might come? Still haven't been able to use the app due to this :(

**Comment by hmnd** [comment]
Oh that's unfortunate :/. Would love to help some more with debugging, but I'm not super well versed with Flutter...

**Comment by hillelcoren** [comment]
This will be fixed in the next release of the Windows app available soon.
