### ISSUE TITLE
Forgetting/not appyling local settings

### ISSUE THREAD

**Issue by itkfm** [invoiceninja/admin-portal#325]
v5.3.6-C58

Invoice Ninja forgets local settings after re-opening the tab/browser (Firefox 91.0.2 + Chromium 93.0).

### Examples

<details>
<summary>apparently English (despite it saying “German”/“Deutsch”)</summary>

#### Localization settings
![Localization settings](https://user-images.githubusercontent.com/53079668/131982966-494c274a-867c-4736-a3d2-d947dd86f282.png)

</details>

<details>
<summary>wrong color</summary>

#### User Details
![image](https://user-images.githubusercontent.com/53079668/131983721-8c273111-aaf3-43f4-ab2e-5a99d86afa5d.png)
</details>

### Woraround
Log out + in again

**Comment by hillelcoren** [comment]
Thanks for reporting this!

- Do you see anything in the browser console after refreshing the page

- Does enabling persist data on Settings > Device Settings change the behavior

**Comment by itkfm** [comment]
- ![image](https://user-images.githubusercontent.com/53079668/131990058-14efad66-0c4f-43e3-b0b4-7d9b09dd33e3.png)
- yes, seems to bypass this issue

**Comment by itkfm** [comment]
Further findings:
- Manually hitting “refresh data” in device settings works around this bug
- After having had enabled “persist data”, re-opening the tab wouldn’t drop color/language etc. (logging out + in brought this issue back, though)
