### ISSUE TITLE
Decimal/thousand separators wrong when international format in use

### ISSUE THREAD

**Issue by scwfan06** [invoiceninja/admin-portal#328]
![2019-05-30 17_10_21-Window](https://user-images.githubusercontent.com/8067715/58643609-e31b4f80-82ff-11e9-98d8-22ba7df5d2c0.png)

**Comment by hillelcoren** [comment]
Note: in the latest version the option has been moved to Settings > Localization

**Comment by egrueda** [comment]
If I enable decimal comma option, it works fine.
But that doesn't fix the bug, just hide it.
When not using comma, amounts change anormally, I think that's a bug

**Comment by hillelcoren** [comment]
Sorry, I don't understand. What do you mean by "When not using comma, amounts change anormally", can you explain the bug?

**Comment by egrueda** [comment]
> Sorry, I don't understand. What do you mean by "When not using comma, amounts change anormally", can you explain the bug?
Of course, sorry if I didn't make myself clear
See my previous screenshot at https://github.com/invoiceninja/admin-portal/issues/328#issuecomment-913795239
1. I enter 35€
2. I assign that to an invoice
3. those 35€ become 3500.00€ automatically
And that's what I'm talking about :-)

**Comment by hillelcoren** [comment]
In the screenshot above you've entered 35 as the amount but selected an invoice for 3500

**Comment by egrueda** [comment]
If the invoice was 3500 I would not fill a bug report. 
Please, see attached video, it's easily reproducible

https://user-images.githubusercontent.com/358397/132632880-7c8ced43-9490-461a-adf9-c0e62dcb089a.mp4

**Comment by hillelcoren** [comment]
Thanks for the video, is the decimal comma option enabled?

**Comment by egrueda** [comment]
As said before, If I enable decimal comma option, it works fine.
Problem happens when NOT using comma, and it's not supposed to fail

**Comment by hillelcoren** [comment]
Thanks for reporting it, it was definitely a bug.

Should be resolved in the next release.
