### ISSUE TITLE
Wrong Decimal Seperator for Discount Input in German Local

### ISSUE THREAD

**Issue by Akjo4712** [invoiceninja/admin-portal#331]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
5.3.10

**What environment are you running?**
Docker

**Have you searched existing issues?**
Yes

**Have you reported this to Slack/forum before posting?**
No

**Describe the bug**
I have to use a Point as a Decimal Sperator for the Discount Field. This is not correct for German Local, we use a Comma as a Decimal Sperator.

**Steps To Reproduce**

1. Change to German/Austria Locale
2. Create new Invoice with Discount
3. Use Comma as Decimal Seperator
4. Observe the Wrong math for Discount Calculation

**Screenshots**
![image](https://user-images.githubusercontent.com/65533611/133030698-6b76d262-2dea-4acb-85ea-3ef24cc70e3a.png)

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**
Can't change Language on Demo Site, so I can't test.

**Comment by hillelcoren** [comment]
Can you please check the decimal comma option is enabled on Settings > Localization

**Comment by hillelcoren** [comment]
Thanks for reporting, we'll look into it

**Comment by hillelcoren** [comment]
Sorry for the multiple responses, I misread the issue.

Please check the decimal comma option on Settings > Localization

**Comment by Akjo4712** [comment]
Thanks! Was unaware of this Option.

**Comment by hillelcoren** [comment]
It's newly added, in the past we tried to automatically determine the separator but found it wasn't always correct
