### ISSUE TITLE
Payment link via stripe is wrong

### ISSUE THREAD

**Issue by LarsK1** [invoiceninja/admin-portal#332]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.3.12
**What environment are you running?**
Shared Hosting

**Describe the bug**
When clicking on the payement tab on the open button, the wrong page opens:
https://dashboard.stripe.com/payments/src_1JZgW7LaevbwEJ347yc01U7l, which doesn't exist.

There is:
https://dashboard.stripe.com/sources/src_1JZgW7LaevbwEJ347yc01U7l
or
https://dashboard.stripe.com/payments/py_1JZgWfLaevbwEJ34Z8UCOsT8 (I guess, the one with payment is the more interesting page for the customer and user)

**Screenshots**
![image](https://user-images.githubusercontent.com/28981528/133462975-869940a2-7c29-49cb-88df-3a5643976f36.png)

**Additional context**
See invoiceninja/invoiceninja#6612 

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**
yes

**Comment by turbo124** [comment]
@hillelcoren 

is it possible to switch /payments /sources based on the transactionr reference prefix src_ or py_ ?

**Comment by hillelcoren** [comment]
Sure, shouldn't be a problem

**Comment by LarsK1** [comment]
@turbo124  still not completely fixed, as the src-page has no value for the user. Is it possible to receive from the source-id (src_1JZxZyLaevbwEJ347fNexiki) the payment_id (py_1JZxaYLaevbwEJ34kGyBTsoY), which is way more helpful for the business owner

![image](https://user-images.githubusercontent.com/28981528/133785265-5ef62519-df6a-4926-83fd-296cc68fa354.png)
(sources view)

![image](https://user-images.githubusercontent.com/28981528/133785384-6bc6e3c3-91a8-4cb2-b9b2-2d20a307800c.png)
(payment view)

**Comment by LarsK1** [comment]
@turbo124 any answer?

**Comment by turbo124** [comment]
@LarsK1 we'll need to wait for @hillelcoren to report back on this.

**Comment by hillelcoren** [comment]
@turbo124 I think the second suggested changed would need to be made in the backend (if it's possible)
