### ISSUE TITLE
Requesting drag to arrange

### ISSUE THREAD

**Issue by nchetoora** [invoiceninja/admin-portal#335]
I would like to request the old feature that we had in version 4 which allows us to drag an item up or down the invoice or quote instead of using the new three dots to move it up or down. It takes a long time to arrange the items in the order I would like it to be because I have to move it one line at a time.

**Comment by mrkylegp** [comment]
This is a great suggestion and something I'd also love to see return :)

**Comment by fusitron** [comment]
+1

**Comment by hillelcoren** [comment]
This has been added and will be available in the next release
