### ISSUE TITLE
Incorrect Label "bulk_email_payment" under Payments contextual menu

### ISSUE THREAD

**Issue by mrkylegp** [invoiceninja/admin-portal#336]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.3.16-C59

**What environment are you running?**
Shared Hosting

**Describe the bug**
In the payments section, when using the dots menu for a payment, the email payment label is incorrect and displays "bulk_email_payment"

![bulkemail](https://user-images.githubusercontent.com/52687659/134290185-87605f76-2dd4-4501-b75d-f817b2f07fe8.png)

**Steps To Reproduce**
Add a payment.
Go to the payments tab from the sidebar.
Click the dots menu for that payment. Observe the incorrect label.

**Expected behavior**
It should be labelled "Email Payment" or "Email Payment Receipt"

**Comment by hillelcoren** [comment]
Thanks for creating the issue, to be fixed...

**Comment by mrkylegp** [comment]
> Thanks for creating the issue, to be fixed...

My pleasure, thankyou for your continued efforts!
