### ISSUE TITLE
Windows app dumping .json files in my Documents folder

### ISSUE THREAD

**Issue by onetrev** [invoiceninja/admin-portal#337]
I just noticed that every time I load the Invoice Ninja Windows app it drops a bunch of .json files in my root Documents folder. I end up with: `invoiceninja_company_state_0.json` repeating over and over again (with the number at the end increasing by one each time) every time I load the app. That seems like something that shouldn't happen since it will keep on growing the file count forever then.

Loading the app also creates other files in my root Documents folder. But these seem to be only created once:
```
invoiceninja__static_state.json
invoiceninja__ui_state.json
invoiceninja__auth_state.json
```

**Comment by hillelcoren** [comment]
Thanks for reporting this!

These files are used to store the app's state, we'll look into improving their storage location.

**Comment by onetrev** [comment]
You're welcome! Good to hear you'll look to saving these files in a better location. 

Just to check then, does `invoiceninja_company_state_X.json` have some clean-up functionality then, because as noted they just seemed to keep getting created over and over again?

**Comment by hillelcoren** [comment]
As long as the app is running it will keep generating those files

**Comment by onetrev** [comment]
Hey, just checking in to see if the fix (storage location for app state files) might be coming soon? I'm picky about keeping my root Documents folder clean so it's keeping me on using it as a PWA until then. :)

**Comment by hillelcoren** [comment]
In the next release the files will be grouped inside an 'invoiceninja' folder
