### ISSUE TITLE
Shift key locks when pressed for all additional characters

### ISSUE THREAD

**Issue by iamkhris** [invoiceninja/admin-portal#341]
I installed the Windows Flutter client tonight, but unfortunately can't even log in.  As soon as I enter any character that requires SHIFT to be pressed (a : for example), all characters from that point on are capitalized.

Example:  If I type out "https://www.website.com" I get the following "https:??WWW>WEBSITE>COM"

Anyone else see behaviour like this?  I'm using Windows 11 Beta, with US Keyboard layout (not Canadian).

**Comment by hillelcoren** [comment]
It may help to use the left shift key: https://github.com/flutter/flutter/issues/75675

This should be resolved in an upcoming release of the app.

**Comment by hmnd** [comment]
@hillelcoren Curious how soon the fix for this will be released? The latest release of the app (v5.0.66) still seems to have this issue, and I'd really love to fully switch over to the native app.

**Comment by hillelcoren** [comment]
We aren't able to provide ETAs but I consider this one of our highest priority issues.

**Comment by iamkhris** [comment]
This is the single reason I’m not regularly using the desktop client.

**Comment by hillelcoren** [comment]
We've deployed a new version of the Windows app (build 67), it should be available in the store soon.

Please let us know if it helps.

**Comment by nathanoster** [comment]
It has indeed helped — the shift key works as expected on the latest version of the Windows app. Thank you!

**Comment by hillelcoren** [comment]
Brilliant, thanks for the update!

**Comment by mrkylegp** [comment]
@hillelcoren @turbo124 This issue should be re-opened. I am experiencing this issue on the Windows desktop app (5.0.84) when using the right shift key.

**Comment by hillelcoren** [comment]
Are you using a standard English keyboard or something else?

Does the left shift key work correctly?

**Comment by mrkylegp** [comment]
> Are you using a standard English keyboard or something else?
> 
> Does the left shift key work correctly?
@hillelcoren Keyboard is English (United States), standard english keyboard. The left key does work correctly and doesn't give me any issues.

Strange thing is I just closed and re-opened the app and now it's not doing it. I'm not exactly sure what triggered it to start playing up again with the right shift key. I'm trying to see what specific circumstances cause it to happen.

**Comment by hillelcoren** [comment]
It sounds like the underlying issue may be partially fixed, we're updating soon to the latest version of the framework which may help.
