### ISSUE TITLE
The test flight for iOS has expired

### ISSUE THREAD

**Issue by publicarray** [invoiceninja/admin-portal#342]
![image](https://user-images.githubusercontent.com/5497998/135732676-f6d956bc-2a66-4fe4-893b-7f041f7484ed.jpeg)

Is there going to be a release on iOS soon? Thanks for your amazing work on the platform.

**Comment by hillelcoren** [comment]
The v5 iOS app is now live, you can download it here:

https://apps.apple.com/us/app/invoice-ninja-v5/id1503970375

You can links find all v5 client apps here:

https://invoiceninja.org

**Comment by publicarray** [comment]
Thank you!
 It did not show up yet when I searched for it in the app store.

**Comment by hillelcoren** [comment]
Yeah, doesn't show for me either. I need to add 'v5' in the search field to see it. 

Enjoy the app, let us know if you see any problems.

**Comment by publicarray** [comment]
Thanks, yea will do.
