### ISSUE TITLE
Invoice file upload (v5.2.17) (iOS 1.1)

### ISSUE THREAD

**Issue by publicarray** [invoiceninja/admin-portal#343]
While the camera works the `Upload  file` button does nothing, probably not implemented yet. So this makes it more of a feature request

Steps to reproduce: Adding Documents to an invoice.

I would expect to be able to select files from the device ([document picker](https://developer.apple.com/documentation/uikit/view_controllers/providing_access_to_directories)) or the Photo Library.

I'm on iOS 15.0.1 by the way

**Comment by hillelcoren** [comment]
I believe this will be corrected in the next version of the mobile app, hopefully within a week or two.

**Comment by publicarray** [comment]
No worries Just thought I let you know. Impressive that this is already being worked on :clap:
