### ISSUE TITLE
Edition forms of invoices, tasks etc. are not closing after saving - intended change or bug?

### ISSUE THREAD

**Issue by hahyes** [invoiceninja/admin-portal#350]
Invoice Ninja v5.3.23 / Self-hosted

Hi there, 
little enhancement suggestion. In last updates of admin portal behavior of forms changed. When I'm editing task, invoice, whatever else - form is not closing upon successful save. I understand that someone could want to save multiple times. But **I think it should be configurable** to not irritate people who want to save once and automatically move somewhere else. Some people under me working with IN are reporting this as bug to me, maybe they are right? 

Anyway I'm leaving it mostly as suggestion, because I think both behaviors could be wanted by users.

**Comment by hillelcoren** [comment]
We've added this as an option on Settings > Device Settings
