### ISSUE TITLE
Recurring invoices are sorted wrong

### ISSUE THREAD

**Issue by stefaandevylder** [invoiceninja/admin-portal#352]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.3.23

**What environment are you running?**
ZIP

**Have you checked log files (storage/logs/) Please provide redacted output**
NA

**Have you searched existing issues?**
Yes

**Have you reported this to Slack/forum before posting?**
No

**Describe the bug**
When you go to the page where all invoices are listed and sort by number, the recurring invoices are always at the end of the list. Example: You have 5 invoices, invoice number 4 is a recurring invoice. When you sort by number counting down, the output will be 5, 3, 2, 1, 4

IMPORTANT: It only happens when you also have a recurring prefix!

**Steps To Reproduce**
- Set a recurring prefix
- Have multiple existing invoices with 1 or more recurring invoice in the middle

**Expected behavior**
NA

**Screenshots**
![1](https://i.imgur.com/8LZdhUP.jpg)
![1](https://imgur.com/wTdqIPL.jpg)

**Additional context**

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**
Absolutely

**Comment by hillelcoren** [comment]
What value is the recurring invoice prefix set to?

**Comment by hillelcoren** [comment]
In the screenshots all of the invoices have the same prefix, are there other invoices not shown without the prefix?

**Comment by stefaandevylder** [comment]
No, as shown in screenshot the invoices: 79, 80, 81, 100, 101, 102 are recurring, everyingthing else is not

**Comment by hillelcoren** [comment]
If only some are recurring why do they all have the recurring prefix?

**Comment by hillelcoren** [comment]
The recurring invoice prefix is designed to be used when recurring invoices numbers should have a different prefix than standard invoices. If they should all be the same than I suggest clearing the value.

**Comment by stefaandevylder** [comment]
Alright, there is no way to test it without waiting a day I think right?

**Comment by hillelcoren** [comment]
Sorry I'm not sure, I can't reproduce the problem. I've tried manually setting invoices to have similar numbers and the app sorts them correctly.

**Comment by stefaandevylder** [comment]
Hopefully it does not happen again. Ill close for now.
