### ISSUE TITLE
Translation: Button Text not shown

### ISSUE THREAD

**Issue by alexanderhofstaetter** [invoiceninja/admin-portal#355]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.3.25-C60

**What environment are you running?**
Docker

![image](https://user-images.githubusercontent.com/6820505/137716105-db7e4c89-301b-4158-a09a-7b8d331f80cb.png)

Current language: German

The button shows the translation slug and not the translated string.

**Comment by hillelcoren** [comment]
Thanks for reporting this! In the next release the app will show the English value.

@turbo124 we need to work on getting the new translations updated to Transifex.
