### ISSUE TITLE
iOS APP: Always prompts for Add new company

### ISSUE THREAD

**Issue by alexanderhofstaetter** [invoiceninja/admin-portal#358]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**

v5.3.27-C62 / Latest available iOS app from the appstore (iOS 15)

**What environment are you running?**
Docker

Problem:
Everytime I open the app on iOS it prompts for new company details. When i fully close the app from the app switcher and open it again, it prompts me again.

To be clear: there are already 3 companies set up ...

![image](https://user-images.githubusercontent.com/6820505/138665491-ca022bf0-7ee2-4e0a-9e7c-9ecea84760bd.png)

**Comment by hillelcoren** [comment]
We've made a change which may help, please let us know if you still see the problem using build 64 or greater of the admin portal.

**Comment by alexanderhofstaetter** [comment]
@hillelcoren I updated the portal to v5.3.30-C64 and still have the same issues on iOS.

What is new: since I did this update, the GUI has some wrong preloading effects: while the app is loading, it shows wrong language, wrong colors and wrong logos. This behaviour is on the WebApp and on the iOS App. 

There should be some kind of browser caching, as this happens on every (!) browser page reload.

First view of loading:
![Bildschirmfoto 2021-11-09 um 17 02 51](https://user-images.githubusercontent.com/6820505/140960691-bd394438-c0e0-4a23-917e-fd09868428b6.png)

Loaded
![Bildschirmfoto 2021-11-09 um 17 02 58](https://user-images.githubusercontent.com/6820505/140960725-93200b79-f057-4b02-9cac-93fc4ce1e9ec.png)
:

**Comment by hillelcoren** [comment]
Are you seeing the new company prompt in the web app?

Enabling persist data/UI on Settings > Device Settings may help with the loading.

**Comment by alexanderhofstaetter** [comment]
Sorry if I was unclear: I see the prompt for new company only in the iOS app.

Regarding date loading: Persist data is enabled, i did also some reload, deleted all app data in the chrome browser, tried another browser, deleted CDN data and did a full logout / login - no change

**Comment by hillelcoren** [comment]
Thanks, the prompt should be resolved with the next iOS update.

It may help to toggle the persist options (it forces a recache) or add ?clear_local=true to the URL to clear the cache.
