### ISSUE TITLE
Feature request: Turn off PDF / HTML invoice preview

### ISSUE THREAD

**Issue by anarchyscd** [invoiceninja/admin-portal#361]
Would love the ability to switch off the PDF/HTML preview, or be able to have it on an accordion (default shut) so it's not constantly refreshing.  Expand accordion to view HTML/PDF preview (if needed) or simply use the existing menu functionality for "VIEW PDF" (Ideally a new menu option straight to "DOWNLOAD PDF" also).

**Comment by hillelcoren** [comment]
Thanks for creating the issue. FYI.. a download option will be added in the next release.

**Comment by anarchyscd** [comment]
Excellent =)

Just paid up for the year.  Dark mode & the new UI are lifechanging – Well done to all involved!

[A picture containing text, clipart  Description automatically generated]

Aron Dobrowolski
ANARCHY SCD
STRATEGY | CREATIVE | DESIGN
M: 0419 953 165    E: ***@***.******@***.***>
