### ISSUE TITLE
Text input broken in latest Windows release

### ISSUE THREAD

**Issue by hmnd** [invoiceninja/admin-portal#362]
The latest Windows release introduced some strange inconsistencies with text input. The shift key 'sticks' while typing, so pressing the shift key once results in all caps text input, with no way to revert. Weirdly, opening the on screen keyboard fixes this behavior for as long as the on screen keyboard is open.

**Comment by hillelcoren** [comment]
I believe this is a duplicate of #341

**Comment by hmnd** [comment]
Oh sorry, totally missed that!
