### ISSUE TITLE
"Welcome to Invoice Ninja" dialog appears on every launch of Windows app

### ISSUE THREAD

**Issue by hmnd** [invoiceninja/admin-portal#363]
Since the latest release, a "Welcome to Invoice Ninja" dialog (see screenshot below) appears on every launch of the app. This happens even if already signed in.
![Welcome to Invoice Ninja dialog](https://user-images.githubusercontent.com/12853597/140001896-47e7e8d0-9104-424f-8d03-e68fc1f8537f.png)

**Comment by hillelcoren** [comment]
Is it possible you have an extra blank company in your account? The wizard is shown when the current selected company doesn't have a name set on Settings > Company Details.

**Comment by hmnd** [comment]
I used to have a second company, but now it's only one (it has a name).

**Comment by hillelcoren** [comment]
Thanks! I'm going to close this as I think it may be the same root problem as #358
