### ISSUE TITLE
App will not load. Requires internet connection? Server is accessible on LAN

### ISSUE THREAD

**Issue by mstyp** [invoiceninja/admin-portal#365]
I installed invoice ninja on a raspberry pi. another PI broadcasts a wifi signal, creating a LAN that has no connection to the internet. However, the android app will not even start. It just loads forever with and then a "please restart the app once connected to the internet" message pops up. This is a problem, because my tablet only ever connects to the LAN. It never directly connects to the internet, and it never will.

There is no need for an internet connection when the tablet and the server run on the same local network. I can login via firefox on my tablet just fine.

**Comment by hillelcoren** [comment]
Thanks for reporting this, we'll look into it.
