### ISSUE TITLE
Sort tasks by task ID

### ISSUE THREAD

**Issue by gerroon** [invoiceninja/admin-portal#366]
**What version of Invoice Ninja are you running? ie v4.5 / v5** 
v5

**What environment are you running?**
Apache

**Have you searched existing issues/requests?**
Yes

Hi

It would be very helpful if there is a way to sort the tasks by their ID numbers. The update date is useful but not so much when older tasks are updated after the latest tasks. The tasks are generally done in order so this will be helpful for determining the order of completion especially the logged ones.

**Comment by hillelcoren** [comment]
HI,

You can click the 'columns' button in the bottom right corner to add the number field to the table to use it to sort.

Does that solve it?

**Comment by gerroon** [comment]
Thanks, I will try it.
