### ISSUE TITLE
Missing strings

### ISSUE THREAD

**Issue by LarsK1** [invoiceninja/admin-portal#367]
IN the stripe payment settings, two strings seem to be missing. I think it BECS and ACSS. They are added to the strings but don't show up?
![image](https://user-images.githubusercontent.com/28981528/140713590-49512b3d-309f-4f78-b558-2e6db1d7ba20.png)

**Comment by hillelcoren** [comment]
Hi,

Which version of the app are you using, you can check the full version by clicking about in the lower left corner.

**Comment by LarsK1** [comment]
v5.3.29-A62
I just pulled the latest changes from v5-develop  repository. So should be the latest version?

**Comment by hillelcoren** [comment]
Your backend is most likely up to date however the Android app is a bit behind, I suggest checking in the webapp.

**Comment by LarsK1** [comment]
The screenshot is from the webapp

**Comment by hillelcoren** [comment]
What version do you see in the webapp?

**Comment by LarsK1** [comment]
v5.3.29-C63

**Comment by hillelcoren** [comment]
Not sure, I can't replicate the issue. 

Are the labels there if you change to English?

**Comment by LarsK1** [comment]
No changes, but now I've seen that the console shows an error:
```
## ERROR: localization key not found - giropay
main.foss.dart.js?v=5.3.29:5284 ERROR: unhandled entityType companyGateway in entity_status_chip.dart
```

**Comment by LarsK1** [comment]
Now all are visible. Thanks!

**Comment by hillelcoren** [comment]
Glad to hear it!
