### ISSUE TITLE
Add adaptive icon support on Android 8+

### ISSUE THREAD

**Issue by JacobDB** [invoiceninja/admin-portal#37]
Newer versions of Android have a featured called Adaptive Icons. Essentially, this lets users choose the shape of all of the icons on their home screen, to keep them uniform. In the future, Google may use this feature for things such as notification indicators, or other unknown features.

Currently, the Invoice Ninja icon is appearing against a solid white background in most cases, and looks pretty bad (at least in my opinion). Adaptive icons are pretty easy to support, just requiring a couple of new graphics and about 5 lines of new XML code. I'd greatly appreciate it if Invoice Ninja could be updated to support Adaptive Icons.

https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive

![invoice-ninja](https://user-images.githubusercontent.com/1123997/46879307-4a38d200-ce0b-11e8-9778-774ea46f0052.gif)

**Comment by hillelcoren** [comment]
Thanks for the info, I'll look into it.
