### ISSUE TITLE
Desktop app warning keeps coming back

### ISSUE THREAD

**Issue by itkfm** [invoiceninja/admin-portal#371]
**v5.3.30-C64**

Dismissing it won’t be “saved” after reloading the page in the browser.

![image](https://user-images.githubusercontent.com/53079668/141353961-e14b27d7-4daf-42b0-9b61-68eed5bb4bf1.png)

**Comment by hillelcoren** [comment]
This is by design

**Comment by hillelcoren** [comment]
The performance of the desktop app is significantly better than the web app. The warning is temporary, we're working to improve the performance of the web app at which point will remove it

**Comment by hillelcoren** [comment]
It's clear many people want the option to permanently hide the warning, we'll add it.
