### ISSUE TITLE
Select all button only selects 10 invoices in list view mode, not all visible

### ISSUE THREAD

**Issue by mrkylegp** [invoiceninja/admin-portal#372]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.3.30-C64

**What environment are you running?**
Self Hosted

**Describe the bug**
In list view, the select all button doesn't select all invoices. Only the first 10 are selected.

A tick in the select all box is also not present (visual issue).

Ties in with invoiceninja/invoiceninja#6963 as I believe the select all box is only taking affect to select 10 invoices which are visible in table view, but when in list mode, all invoices are visible yet the select all box is still designed around table view.

**Expected behavior**
All invoices visible in the list view mode are selected.

**Screenshots**
![Screenshot 2021-11-13 170540](https://user-images.githubusercontent.com/52687659/141608004-3c6c0b61-49b5-4cfb-82c1-84bdb3510354.png)

**Comment by hillelcoren** [comment]
The app currently limits the selected number of items to the number of row set on Settings > Device Settings

This is clear on the table view but not clear on the list view, @turbo124 is there a standard limit you'd like me to apply in the list view?

**Comment by mrkylegp** [comment]
When viewing everything in list view and having a select all button at the top, the expected behaviour is that it will select all that are visible. This is typically what that kind of box is supposed to do. I am trying to select all my invoices, and download them all in one go. I understand the number of row in Settings > Device settings affects table view, but it shouldn't affect list view where all things are visible.

![Screenshot 2021-11-16 082834](https://user-images.githubusercontent.com/52687659/141856505-5daccb68-60ce-4e46-a204-71da6ba206d6.png)

**Comment by hillelcoren** [comment]
The backend can't support processing an unlimited number of records at once, we'll set the limit to 100 for now.
