### ISSUE TITLE
List view is not possible without an invoice being selected first

### ISSUE THREAD

**Issue by mrkylegp** [invoiceninja/admin-portal#373]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.3.30-C64

**What environment are you running?**
Self Host

**Describe the bug**
Full list view (and it's toggle button) is not visible unless an invoice is selected first.

In addition to that, if you choose list view then hit the X to close off a selected invoice (the panel on the right), then the view switches back to table view.

**Expected behavior**
The list/table view button is visible at all times and list view is possible when an invoice is not selected.

**Screenshots**
![Inkedlist](https://user-images.githubusercontent.com/52687659/141607718-00647188-7c1a-493c-8595-025db9dd87c6.jpg)

**Additional context**
I needed to view an entire list of ALL my invoices. I couldn't find a way to do so and instead I could only go through pages at a time displaying 10 invoices per page, like this...

![Screenshot 2021-11-13 165722](https://user-images.githubusercontent.com/52687659/141607751-9e08021e-cfa0-4fec-88c6-a4f9112407d1.png)

It wasn't until I clicked on an invoice did a new button appear at the bottom where I could toggle between table view or full list view.

I believe this button should be visible at all times and not only when an invoice is selected?

**Comment by hillelcoren** [comment]
Thanks for the suggestion, we'll look into it.
