### ISSUE TITLE
Add a print button

### ISSUE THREAD

**Issue by mrkylegp** [invoiceninja/admin-portal#374]
It would be great to have a print button so you don't have to download/view the PDF then print it.

In the case of utilising the Windows desktop app, I have to actually download the PDF before I can print.

There is no way to print from the desktop app without downloading and opening the PDF first.

![Screenshot 2021-11-13 165150](https://user-images.githubusercontent.com/52687659/141607620-f28f78d5-2120-437f-afe9-6a256cad5454.png)

In the browser, at least when you view the PDF, there is a little print icon when you hover over the PDF section.

It would also be good to have the print button in the multiple selection action list, in case you want to select multiple invoices to print. I have a need for this use case.
![Screenshot 2021-11-13 170336](https://user-images.githubusercontent.com/52687659/141607943-a547c9fa-b4fe-4248-aec4-5093c1aa480d.png)

**Comment by hillelcoren** [comment]
Thanks for the suggestion!

I agree this would be useful but I'm not sure how to make it work just yet.

**Comment by hillelcoren** [comment]
We found a package to support this, hope to add this feature in the future:

https://pub.dev/packages/printing

**Comment by mrkylegp** [comment]
> We found a package to support this, hope to add this feature in the future:
> 
> https://pub.dev/packages/printing

Perfect, can't wait!

**Comment by hillelcoren** [comment]
We've added support for printing an individual PDF invoice
