### ISSUE TITLE
Broken in safari

### ISSUE THREAD

**Issue by zedpr0** [invoiceninja/admin-portal#376]
Version 5.3.31

Issue is present even in https://demo.invoiceninja.com when using the safari browser on an m1 Mac. UI glitches and just starts artifacting. Have reverted back to an older version.

<img width="270" alt="Screenshot 2021-11-16 at 10 21 13 AM" src="https://user-images.githubusercontent.com/44780859/141884434-71986496-ff1b-45da-995b-aff1ba35f013.png">

**Comment by turbo124** [comment]
Can you advise if appending ?build=html to the url improves this or not please

**Comment by zedpr0** [comment]
Yeah that makes the problem go away. No more glitching and artifacting.

**Comment by zedpr0** [comment]
This issue is apparently from flutter, and affects everyone using macOS Monterey regardless of intel or m1 cpu.

flutter/flutter#92495

**Comment by hillelcoren** [comment]
Thanks for reporting this!

FYI.. the macOS app was recently made available in the Apple App Store

https://itunes.apple.com/WebObjects/MZStore.woa/wa/viewSoftware?id=1503970375

**Comment by zedpr0** [comment]
My pleasure, I think I will stick with the older version for now.

**Comment by zedpr0** [comment]
latest safari update has fixed the problem.

**Comment by hillelcoren** [comment]
Glad to hear it, thanks for letting us know!
