### ISSUE TITLE
Sort Order not in line with database sort order

### ISSUE THREAD

**Issue by alexanderhofstaetter** [invoiceninja/admin-portal#377]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.3.31-C67

**What environment are you running?**
Docker

The sort oder of e.g customers is not the same with the database sorting Collation.

Even though the database collation is `utf8mb4_unicode_ci` clients names in the gui are sorted differntly.

In the GUI, german Umlaute are sorted behind Z:

![image](https://user-images.githubusercontent.com/6820505/142019841-abc6065e-c63e-438b-933c-20cb47edddf3.png)

In the DB, umlaute are sorted behind der correspondig letter.

![image](https://user-images.githubusercontent.com/6820505/142019873-f7dcac3e-942e-4e56-9478-96f676579ad5.png)

The GUI should respect the database collation here in my opionion.

**Comment by hillelcoren** [comment]
The GUI isn't aware of the database collation but I agree the sorting could be better. 

This may be a possible solution: https://pub.dev/packages/diacritic

**Comment by alexanderhofstaetter** [comment]
replacing them in the sort string would definitly behave more natural for the user, yes! :)

**Comment by alexanderhofstaetter** [comment]
Another thing which is annoying for us regarding sorting is the "Pending" Invoice number column.

When the invoice number generation is set to "on sent", all invoices show "pending" as the invoice number, which is fine. However, normally theese invoices are drafts ready to be send in the next days / weeks, and therefore definitly future invoices. From a logical view these invocies should be ranked higher than any sent invoices when sorted by the invoice number column.

Currently, it is different:
![image](https://user-images.githubusercontent.com/6820505/142023444-0a545e3f-7d7c-47c9-b13d-ccbe438c3cd6.png)

![image](https://user-images.githubusercontent.com/6820505/142023536-edd2cf35-64e2-4775-a79f-7bf612e1bd4f.png)

 Expacted behaviour:
- When sorted descending by invoice numbers, pending invoices should be always sorted to top :)

**Comment by hillelcoren** [comment]
Both changes have been implemented and will be included with the next release, thanks for the suggestions!
