### ISSUE TITLE
iOS App does not show table data (clients / invoices / payments)

### ISSUE THREAD

**Issue by alexanderhofstaetter** [invoiceninja/admin-portal#378]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.3.31-I67 and latest available iOS App

**What environment are you running?**
Docker 

We freshly installed the v5 iOS app on iOS 15.1 (iPhone 13) and we see no data at any table listing at all. However, if we switch the table view to the "other one for mobile" we see the listings (after pressing the button marked red in the screenshot it works with the different view - switching back shows nothing again).

![IMG_5839](https://user-images.githubusercontent.com/6820505/142197908-cb0bb0c9-2306-44ec-8769-8453a5675a20.jpeg)

The behaviour is the same for all datatables (clients / invoices / payments)

**Comment by alexanderhofstaetter** [comment]
No success, I tried every sort option, same result at all of them

**Comment by hillelcoren** [comment]
We've tracked down the problem, it should be corrected in the next release in a few days.
