### ISSUE TITLE
2FA code input - Change to Number Pad keyboard

### ISSUE THREAD

**Issue by NPCtom** [invoiceninja/admin-portal#379]
When logging in for the first time the 2FA code uses the full sized iOS keyboard - forcing users to have to tap the number icon.

It would be a nicer UX to use the number pad keyboard for the 2FA code input.

![image](https://user-images.githubusercontent.com/44740840/142399175-4e607069-0796-4ce8-8085-60349081ff13.png)

**Comment by hillelcoren** [comment]
Thanks for the suggestion!

Are you NZNinja on the support forum?

**Comment by NPCtom** [comment]
> Are you NZNinja on the support forum?

Yes I am!

**Comment by hillelcoren** [comment]
Awesome, just wanted to thank you for all of your help on the forums!!

**Comment by NPCtom** [comment]
No problem mate. It's an awesome project that has really helped my business. I finally found a way to help support it!

**Comment by hillelcoren** [comment]
This has been implemented
