### ISSUE TITLE
Linux Desktop app is not updateable

### ISSUE THREAD

**Issue by grandeljay** [invoiceninja/admin-portal#380]
In regard to [this slack thread](https://invoiceninja.slack.com/archives/C9KSLL0TE/p1637654840405700) I am asking for an updatable solution for the Linux Desktop App. @hillelcoren mentioned a snap is being worked on at high priority.

I am creating this issue as a formality and so I can subscribe to any updates regarding the snap. 

I look forward to it!

**Comment by hillelcoren** [comment]
https://snapcraft.io/invoiceninja
