### ISSUE TITLE
Search result "Password Protect Invoices" opens wrong panel/tab

### ISSUE THREAD

**Issue by mrkylegp** [invoiceninja/admin-portal#381]
If you search settings for password and click on the "Password protect invoices" result, it displays the client portal "registration" settings tab, rather than the "authorization" tab where the password protect invoices setting actually exists. Not a massive bug but caused me some confusion when I used search to find this setting and was presented the wrong section when clicking the search result.

![Screenshot 2021-11-29 162628](https://user-images.githubusercontent.com/52687659/143813767-34f6131e-1d55-48a5-936d-93b3007d174c.png)

**Comment by hillelcoren** [comment]
Thanks for catching this!
