### ISSUE TITLE
Recurring vs. Recurring

### ISSUE THREAD

**Issue by itkfm** [invoiceninja/admin-portal#382]
- same label
- same icon
- **but** different purpose

_Recurring_ invoices vs. _Recurring_ expenses

![image](https://user-images.githubusercontent.com/53079668/144285163-e1f2bd3f-c667-493f-b901-98384a2d1028.png)

v5.3.32-C67

**Comment by hillelcoren** [comment]
I think the translated text isn't fitting so it's getting cut off, not sure the best way to solve this.

**Comment by itkfm** [comment]
Maybe use at least some different icon?

**Comment by LarsK1** [comment]
Couldn't we just double the height from the columns with text length over xchars?

**Comment by hillelcoren** [comment]
Possibly, I'll look into it...

**Comment by itkfm** [comment]
nice, thx
