### ISSUE TITLE
Confusing tab UI around login/signup forms

### ISSUE THREAD

**Issue by natevw** [invoiceninja/admin-portal#383]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
**What environment are you running?**

Trying out the app via https://invoicing.co/ for the first time.

**Have you checked log files (storage/logs/) Please provide redacted output**

N/A

**Have you searched existing issues?**

Yes.

**Have you reported this to Slack/forum before posting?**

No.

**Describe the bug**

The "tabs" on the login and signup combo page are confusing. When "Sign Up" is selected the "Login" tab indicator looks active, and vice versa.

**Steps To Reproduce**

1. Visit https://invoicing.co/ for the first time (e.g. in an incognito tab)
2. Look at the tabs from an overall perspective (without carefully reading the buttons inside the selected tab)

**Expected behavior**

The selected tab should be visually connected to its content. But instead there's a more abstract connection: the selected tab is actually a less-prominent blue, and it's the **unselected** tab that gets the white highlight connecting it to the tab content.

**Screenshots**

<img width="568" alt="Screen Shot 2021-12-01 at 3 01 15 PM" src="https://user-images.githubusercontent.com/265902/144328810-e424906d-6fa6-4e2e-aa15-ef7cd061e5b5.png">

The login tab connects visually with the content. But if you read more carefully, the content is actually from the sign up tab.

**Additional context**

On your "compared to Freshbooks" page I liked the claim that Invoice Ninja by comparison offers a:

> solid, conservative design, with bold, distinctive elements that make it easy to navigate.

I found this first impression to contradict that goal.

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**

No, it seems to jump straight to a logged-in demo.

**Comment by hillelcoren** [comment]
Thanks for the feedback, we'll work on it...

**Comment by utkershrajvenshi** [comment]
Hi, I would love to contribute by implementing probable solutions to this issue. Is it being worked upon currently?

**Comment by hillelcoren** [comment]
That would be great, are you able to post a wireframe or mockup first?

**Comment by utkershrajvenshi** [comment]
Yes surely! I was thinking we would want the modification to be in-line with the application's existing user interface. The modifications would look like this:
![redone_form_ui_login](https://user-images.githubusercontent.com/79559223/145264214-526ca2cc-3414-4c96-adcc-751bd148161f.png)
![redone_form_ui_signup](https://user-images.githubusercontent.com/79559223/145264217-9670a1a6-f790-4bb9-bc6b-ce10b4ebc97d.png)

Please suggest if this is good or are there any changes need to be made.

**Comment by hillelcoren** [comment]
Not sure it's the best solution, another would be to change it to show white as selected and blue as deselected. 

@natevw what do you think?

**Comment by utkershrajvenshi** [comment]
Yes I guess that would look more visually coherent. Also, how about changing the deselected blue to a lighter shade so that the inactive tab doesn't look as striking as it presently is?

**Comment by utkershrajvenshi** [comment]
Here's how it looks with the above mentioned changes:
![Screenshot from 2021-12-09 16-58-35](https://user-images.githubusercontent.com/79559223/145398388-45f51905-c6bc-40a6-b98d-6104715a5cda.png)
![Screenshot from 2021-12-09 16-58-42](https://user-images.githubusercontent.com/79559223/145398395-59af1999-1b8f-41d0-94d4-ed9acaed558f.png)

**Comment by utkershrajvenshi** [comment]
@hillelcoren @natevw I request your feedback on these designs. Please have a look at the file:
https://www.figma.com/file/xortOjimPJ0MUY8Srq8rsy/InvoiceNinja-login-forms?node-id=0%3A1

**Comment by natevw** [comment]
@utkershrajvenshi It's unclear what's going on in the Figma file. Are all options showing "Sign Up" selected or are all options showing "Blue is selected"?

I think either of the solutions proposed *here* work: the blue line across the **whole** section in https://github.com/invoiceninja/admin-portal/issues/383#issuecomment-989079269 resolves the confusion for me, or just using white for selected as in https://github.com/invoiceninja/admin-portal/issues/383#issuecomment-989817055.

**Comment by utkershrajvenshi** [comment]
In all options the tab colored in 'blue' is the selected(active) one. The ones in white are deselected(inactive). In some options, "Log In" is the selected tab and in others it's the "Sign Up" tab that is selected.

**Comment by hillelcoren** [comment]
In the next version of the app we're adjusting the UI, it will default to login and creating an account will be a secondary option.
