### ISSUE TITLE
Multi-currency Transaction not visible properly in reports

### ISSUE THREAD

**Issue by HarshadkCon** [invoiceninja/admin-portal#385]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
Self hosted - v5.3.33-C67
Online (invoicing.co) - v5.3.33-C67

**What environment are you running?**
Ubuntu 20.4 for self hosted

**Have you checked log files (storage/logs/) Please provide redacted output**
No

**Have you searched existing issues?**
Yes, Could not find anything similar.

**Have you reported this to Slack/forum before posting?**
i have reported it using contact us (today only after trying on invoicing.co)

**Describe the bug**

**Steps To Reproduce**
Create Client in Foreign currency. (INR 2500)
Receive Payment in foreign currency. Apply conversion to local currency in payment. (GBP 25)
Check the reports for payments / profit or loss -- amount shows as £2500.

**Expected behavior**
Expect amount it to shows in appropriate currency. considering transaction is in INR, either we should show it in iNR everywhere or local currency.

**Screenshots**
![Screenshot 2021-12-03 at 13 33 26](https://user-images.githubusercontent.com/75438182/144611030-75e1e061-eb74-4774-ae52-93cd9174f95b.png)
![Screenshot 2021-12-03 at 13 34 45](https://user-images.githubusercontent.com/75438182/144611095-616cc940-1aee-444c-ac20-792b626e3c5d.png)
![Screenshot 2021-12-03 at 13 35 28](https://user-images.githubusercontent.com/75438182/144611170-5ce47843-93e5-4199-b4eb-b388f614d053.png)

**Additional context**

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**

**Comment by hillelcoren** [comment]
If you're self hosting is the app correctly loading the exchange rates/what's the exchange rate for the payment in question.

**Comment by HarshadkCon** [comment]
Dont think its an issue with exchange rates -- 

i have setup OPENEXCHANGE_APP_ID=xxxxxxxxx

logs are clean --- storage/logs/laravel.log

[2021-12-03 00:00:03] production.INFO: updating currencies  
[2021-12-03 00:30:01] production.INFO: Performing Autobilling 2021-12-03 12:30:01  
[2021-12-04 00:01:32] production.INFO: updating currencies  
[2021-12-04 00:30:01] production.INFO: Performing Autobilling 2021-12-04 12:30:01  
[2021-12-05 00:01:02] production.INFO: updating currencies  
[2021-12-05 00:30:02] production.INFO: Performing Autobilling 2021-12-05 12:30:02

**Comment by HarshadkCon** [comment]
Please let me know if anything needs to be checked, Just to rule out any issues with self hosting, i have tried this on the online version -- https://invoicing.co/#/

In screenshots you can see different currency for same amount.

![Screenshot 2021-12-05 at 09 10 18](https://user-images.githubusercontent.com/75438182/144740601-a0dd9e1d-0a2d-4bab-839d-2300136e26f0.png)
![Screenshot 2021-12-05 at 09 10 46](https://user-images.githubusercontent.com/75438182/144740603-a01bafcb-82a2-493d-812a-26cd70d3f95d.png)
s well.

**Comment by hillelcoren** [comment]
This is a different report, I'm not sure it's the same issue.

**Comment by HarshadkCon** [comment]
Sorry didn't understand, Have you tried to recreate?

i have recreated it on both online version as well as hosted.

**Comment by hillelcoren** [comment]
Ok, I'll look into it and get back to you.

**Comment by hillelcoren** [comment]
I'm not sure, I haven't been able to reproduce this.

I notice in some of the screenshots the currency is blank in the totals table, it may be related?

**Comment by HarshadkCon** [comment]
Should i give you a demo, Setup a zoom call?

**Steps To Reproduce**
Create Client in Foreign currency. (INR 2500)
Receive Payment in foreign currency. Apply conversion to local currency in payment. (GBP 25)
Check the reports for payments / profit or loss -- amount shows as £2500.

**Comment by hillelcoren** [comment]
How exactly is the payment being created?

**Comment by HarshadkCon** [comment]
![Screenshot 2021-12-05 at 17 00 23](https://user-images.githubusercontent.com/75438182/144755950-fe1708ba-eb2a-4211-bea4-58601b107e3c.png)

Screenshot for payment entered.

**Comment by hillelcoren** [comment]
I think I see the problem, there is a bug in the app when using the convert currency option which is setting the wrong rate. This will be corrected in the next release. 

Note: when using that option you'd want to select GBP to convert the payment amount to the local company currency.

**Comment by HarshadkCon** [comment]
thanks
