### ISSUE TITLE
Filter payments by payment type, date range etc.

### ISSUE THREAD

**Issue by mrkylegp** [invoiceninja/admin-portal#390]
It would be great to be able to filter the payments on the payment list via payment type eg. see all cash payments and date ranges.

I also noticed there is a column for payment type but when toggling ascending/descending, it doesn't change anything.

![Screenshot 2021-12-12 184642](https://user-images.githubusercontent.com/52687659/145704631-7f3964b7-0d2f-4f8f-8feb-0af2aefc24bd.png)

**Comment by hillelcoren** [comment]
The bug related to soring has been corrected.

You can use the payments report to filter by type and date.
