### ISSUE TITLE
Dropdowns in windows version keep auto scrolling back to top

### ISSUE THREAD

**Issue by grey-the-geek** [invoiceninja/admin-portal#391]
When adding a task the dropdowns for client and project keep jumping back to the top when trying to scroll down, making it hard to select what you want before it jumps. Have attached a gif to show what I mean.

![Or43VAh6Vm](https://user-images.githubusercontent.com/9677001/145980859-0a8d21d5-828f-45b7-b816-265a37d06af6.gif)

**Comment by hillelcoren** [comment]
Thanks for reporting this, we'll look into it.

**Comment by grey-the-geek** [comment]
Wow, thanks for looking into this so quickly! Really appreciate all the amazing work you guys do.
