### ISSUE TITLE
Cryptographic APIs misuses

### ISSUE THREAD

**Issue by misterAnderson90** [invoiceninja/admin-portal#392]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found a total of 3  warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on admin-portal (or its library dependencies). We documented each one of these issues in private gists for the sake of confidentiality (non-disclosure). 

Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve admin-portal's security, and the quality of the reports of static analysis tools.
(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by hillelcoren** [comment]
Please send an email to contact@invoiceninja.com

**Comment by misterAnderson90** [comment]
Hello @hillelcoren,

Did you receive the gists by email? If yes, could you please share with me your perceptions about the warnings reported? 

Thanks a lot for your collaboration,
