### ISSUE TITLE
Desktop app does not show email template preview like browser version does

### ISSUE THREAD

**Issue by mrkylegp** [invoiceninja/admin-portal#393]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.3.39-C68

**What environment are you running?**
Self hosted

**Describe the bug**
The desktop app (Windows) isn't showing the email template preview like the browser version does.

![Screenshot 2021-12-20 141427](https://user-images.githubusercontent.com/52687659/146706773-59328d4c-d165-455a-ac1f-8ce77ebe1bc8.png)
![Screenshot 2021-12-20 141518](https://user-images.githubusercontent.com/52687659/146706777-9302eba1-77b8-4945-ae93-3b95e1644a5e.png)

**Comment by hillelcoren** [comment]
This isn't yet supported by the framework we're using, once it's supported we'll add it in the app.

**Comment by mrkylegp** [comment]
> This isn't yet supported by the framework we're using, once it's supported we'll add it in the app.

@hillelcoren Is your team waiting on another team to add support to the framework in order to get this working? Do I understand that correctly?

**Comment by hillelcoren** [comment]
That is correct, you can follow the work here: https://github.com/flutter/flutter/issues/37597

**Comment by hillelcoren** [comment]
The next version of the desktop app will include a preview

**Comment by mrkylegp** [comment]
> The next version of the desktop app will include a preview
> 
> Note: the preview is of the message, not the entire email

@hillelcoren Will the desktop app eventually support full HTML preview like the browser?

**Comment by hillelcoren** [comment]
It should work eventually, we're waiting on the framework we're using
