### ISSUE TITLE
Selfhost canvaskit

### ISSUE THREAD

**Issue by itkfm** [invoiceninja/admin-portal#396]
On premises installation of v5.3.45-C68 fetches “canvaskit” resources from an external server.
Why not bundle them, so one can self-host them?

![image](https://user-images.githubusercontent.com/53079668/149321758-0c941673-9d9a-4770-82b3-2abe02114dd9.png)

**Comment by hillelcoren** [comment]
This isn't yet supported by the framework we're using, you can track the request here: https://github.com/flutter/flutter/issues/76009
