### ISSUE TITLE
Selfhost font

### ISSUE THREAD

**Issue by itkfm** [invoiceninja/admin-portal#397]
similar to #396 

- on premises installation
- v5.3.45-C68

![image](https://user-images.githubusercontent.com/53079668/149322343-2c3dea91-456e-4ec0-b9aa-518b54b264ba.png)

“Why do I have to notify Google about my InvoiceNinja usage?”

**Comment by hillelcoren** [comment]
This isn't yet supported by the framework we're using, you can track the request here: https://github.com/flutter/flutter/issues/94404
