### ISSUE TITLE
Aged Receivable List

### ISSUE THREAD

**Issue by JoeBoll** [invoiceninja/admin-portal#398]
**What version of Invoice Ninja are you running? ie v4.5 / v5**
V5.3.43-I69

**What environment are you running?**
invoiceninja.com

**Have you searched existing issues/requests?**
Yes, perhaps they called it something else though.

**Screenshots**
If applicable, add screenshots to help explain your request/question.

**Additional context**
My bookkeeper says we need a "aged receivable list" available from the reports tab.

"It's a list from any given day that details what was owing up to that day" - bookkeeper

I'm told it's like a back-datable outstanding balance list.

(It's very confusing to me :)
Here's an article I found:
https://www.accountingtools.com/articles/what-is-accounts-receivable-aging.html

Thanks for reading :)

**Comment by hillelcoren** [comment]
Hi,

The invoice report has an optional age column which can be used for this.

**Comment by JoeBoll** [comment]
Hi @hillelcoren thanks for your reply :D I appreciate it.

The bookkeeper says the age column doesn't help in this case.
They say it doesn't work because the age column just shows how old the invoice is.

In this case we would need:
Unpaid invoices up to *entered date*


(if that makes sense? XD Trying to translate 'bookkeeper' into english)


"An accounts receivable aging is a report that lists unpaid customer invoices and unused credit memos by date ranges" - https://www.accountingtools.com/articles/what-is-accounts-receivable-aging.html

Thanks again :)

**Comment by hillelcoren** [comment]
The age field calculates how many days past the due date the invoice is.

If you group the report by the age column it will be displayed like a standard aging report.
