### ISSUE TITLE
Android App: links don't open anymore

### ISSUE THREAD

**Issue by LarsK1** [invoiceninja/admin-portal#399]
Hi there,
since the latest update the android app doesn't open any links. So when clicking on "Portal" nothing happens. It's the same with all links that open the customer portal.

Thanks for your great product,
Lars

**Comment by hillelcoren** [comment]
Hi,

If you use the copy option and paste the URL does it load correctly?

**Comment by LarsK1** [comment]
I'm unsure - can't test as the android app shows no links:
![Screenshot_20220116-203328.png](https://user-images.githubusercontent.com/28981528/149675024-2d3e0f49-b95b-4f3a-92c1-478827ff2675.png)
![Screenshot_20220116-203357.png](https://user-images.githubusercontent.com/28981528/149675046-40ebb7da-ec49-4c32-aa30-11f0631629be.png)

**Comment by hillelcoren** [comment]
Thanks for the screenshots! There is a copy option on the contacts tab.

Do you see the same problem with the client's client portal link?

**Comment by LarsK1** [comment]
![Screenshot_20220117-055219.png](https://user-images.githubusercontent.com/28981528/149709951-ef3085d1-ac83-43dd-8435-1ecb989e50c7.png)
The link is correct. In this section also the "show" button work as expected. It's just the buttons in the menues.

**Comment by hillelcoren** [comment]
I'm not sure, I haven't been able to reproduce it

**Comment by LarsK1** [comment]
@hillelcoren shall I try uninstalling the app and reinstalling it again. Or is there any chance to gather logs for the app?

**Comment by hillelcoren** [comment]
You can try, not sure it will help.

Does the client portal menu option work for clients?

**Comment by LarsK1** [comment]
Didn't help as expected by you.

Any idea how I can explore this further?

**Comment by hillelcoren** [comment]
This is the only report we've had so far of this issue, maybe other people will come across it...
