### ISSUE TITLE
Payment report not displaying rows

### ISSUE THREAD

**Issue by jinjie** [invoiceninja/admin-portal#400]
Version: v5.3.47-M68 (Desktop App)
OS: Mac OS

I am trying to get report based on payments and didn't get any rows returned. I tried other reports and some works (especially those only with single currency).

I suspect it is something that got to do with the Currency. Reports are working well without currency tables. 

<img width="1023" alt="Screenshot 2022-01-17 at 3 24 30 PM" src="https://user-images.githubusercontent.com/2721195/149725823-19a4c9eb-1c38-4c02-b817-3a18d860d39a.png">

**Comment by hillelcoren** [comment]
Does removing the grouping help?

Also, can you check if the currency_id field is set in the database for the payments table?

**Comment by jinjie** [comment]
> Does removing the grouping help?

Yes. It will show all payments without group.
 
> Also, can you check if the currency_id field is set in the database for the payments table?

Currently all is 0, except for 2 of them, which is 13 (Singapore Dollar). I tried setting the 2 affected records to "0" in currency_id but that doesn't help.

**Comment by jinjie** [comment]
Ok, cool! now it works. I have set to all to currency_id = 13.

So how do I make the default as 13 whenever a payment is made? Is there a bug somewhere or my configuration

**Comment by hillelcoren** [comment]
@turbo124 any ideas what could cause the currency to be blank?

**Comment by turbo124** [comment]
@jinjie are you billing in multiple currenceis or just one?

**Comment by jinjie** [comment]
> @jinjie are you billing in multiple currenceis or just one?

Just one currency 

> It would also be helpful to know how you are creating these payments, whether manually or via payment gateways

I am creating these payments manually. I will normally go to the invoice and "add payment".

I also see that there is no option to select currency in invoice or payment. Where can this be set? The only place I see it is in customer.

**Comment by hillelcoren** [comment]
The value should be set automatically, this should be corrected in the next release.
