### ISSUE TITLE
Blank textboxes in desktop browser only

### ISSUE THREAD

**Issue by sashi** [invoiceninja/admin-portal#403]
**What version of Invoice Ninja are you running? v5.0.30**

**What environment are you running?**
Docker

**Describe the bug**
Blank textboxes and text in desktop browser only, Firefox and  chrome. No issue on mobile browser or app
I had this happen before and I cleared my browser cache and cookies and it went away but now it sticks

**Screenshots**
![image](https://user-images.githubusercontent.com/25265/151067711-bbf6a2c8-5bc6-438b-9b77-9d32cb71a842.png)

**Comment by hillelcoren** [comment]
HI,

I believe this issue can occur if the firewall is blocking the request to load Google fonts.
