### ISSUE TITLE
Double columns for long strings

### ISSUE THREAD

**Issue by LarsK1** [invoiceninja/admin-portal#406]
Since the beginning of the project there is an issue with the readability of long strings in the menu.
![Screenshot_20220129-064459.png](https://user-images.githubusercontent.com/28981528/151649249-1b89bd91-bbf0-4a86-8d49-df0fbb71aae9.png)
Because on any type of device, you're unable to read "Wiederkehrende Ausgaben" nor "Wiederkehrende Rechnungen" (the same applies to English). 

Is there any chance to double the column height depending on the string length?

**Comment by hillelcoren** [comment]
Thanks for the feedback, this is being tracked here: #382
