### ISSUE TITLE
Safari incompatibility since v5.3.47

### ISSUE THREAD

**Issue by mCruz-de** [invoiceninja/admin-portal#407]
**What version of Invoice Ninja are you running?**
Tried v5.3.45 - v5.3.54

**What environment are you running?**
ZIP self hosted white label

**Have you checked log files (storage/logs/) Please provide redacted output**
nothing in the log files

**Describe the bug**
Since v5.3.47 when logging in with safari, the password input can not be filled.
With v5.3.45 and v5.3.46 everything works like a charm. 
I think there is a modification from v5.3.46 to v5.3.47 that causes the problem.
I can send you my page via dm if it helps.

**Comment by hillelcoren** [comment]
I'm not sure, we've rebuilt the web app with Flutter 2.10.1 but are still seeing the problem

**Comment by hillelcoren** [comment]
Actually, I think it may be corrected with the next release
