### ISSUE TITLE
Currency not correctly recorded in payments

### ISSUE THREAD

**Issue by jinjie** [invoiceninja/admin-portal#408]
Version: v5.3.55-M76 (Desktop App)
OS: Mac OS

Reopening a new issue which is related to #400. Issue not fix in all the latest releases.

`currency_id` is still defaulted as 0 whenever a payment is recorded. I have checked that Currency is set as Singapore Dollar in Settings > Localization.

**Comment by hillelcoren** [comment]
@turbo124 any thoughts?

**Comment by turbo124** [comment]
Fixed here
[#7175](https://github.com/invoiceninja/invoiceninja/pull/7175)

**Comment by jinjie** [comment]
@turbo124 thank you!
