### ISSUE TITLE
Wrong translation & not in Transifex

### ISSUE THREAD

**Issue by LarsK1** [invoiceninja/admin-portal#409]
Hey,
I found some translations that are not in Transifex, but are wrong.
Where can I correct them?

![Screenshot_20220129-063056~2.png](https://user-images.githubusercontent.com/28981528/151649419-8c504cc7-69fd-46c2-b509-96e0870352e1.png)
![Screenshot_20220129-063233~2.png](https://user-images.githubusercontent.com/28981528/151649440-87bba7b0-3fe6-44ea-8516-d823bb05c1ea.png)

Here we need to change the text in order to translate it correctly to:
Last updated: :countminute minutes ago

![Screenshot_20220129-062939~2.png](https://user-images.githubusercontent.com/28981528/151649492-0af77a9d-a307-4d49-9747-2682870fbe6a.png)

Edit:
the translation in the stripe payment settings are not localized, though the language strings already exist.
![Screenshot_20220129-070415.png](https://user-images.githubusercontent.com/28981528/151649763-f88f96d1-a8a6-4dd2-89fd-5fb8b0c145cf.png)![Screenshot_20220129-070420.png](https://user-images.githubusercontent.com/28981528/151649766-2bcdf20d-7b5b-4ac1-9d47-c73916018d81.png)

**Comment by hillelcoren** [comment]
The "5 minutes ago" string is generated by a package we're using

**Comment by LarsK1** [comment]
Can't we strip all except the minutes and add the rest?

**Comment by LarsK1** [comment]
@hillelcoren ?

 Can you please reopen the issue. It makes tracking for me easier...

**Comment by LarsK1** [comment]
@hillelcoren do you see any chance of stripping the rest of the text?

**Comment by hillelcoren** [comment]
We don't plan to remove it but will attempt to translate if possible
