### ISSUE TITLE
Build Failed in iOS

### ISSUE THREAD

**Issue by yeahia2508** [invoiceninja/admin-portal#41]
/Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-14306.16/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/BuildSystem/Runtime/PBXTargetBuildContext.mm:757
    Details:  unexpected successful exit code from cancelled command <C0014:'CpResource flutter_assets':P12>
    Object:   <PBXTargetBuildContext: 0x7f84063f10f0>
    Method:   -createCommandInvocationRecordFromInvocation:
    Thread:   <NSThread: 0x7f8406eb3210>{number = 13, name = (null)}
    Please file a bug at https://bugreport.apple.com with this warning message and any useful information you can provide.
    ** BUILD FAILED **
    
Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    error: the following command failed with exit code 1 but produced no further output
    CopyPlistFile /Volumes/Workspace/AndoridProjects/Github/flutter-mobile/build/ios/Debug-iphonesimulator/Runner.app/GoogleService-Info.plist Runner/GoogleService-Info.plist

**Comment by hillelcoren** [comment]
Is the app building for you on Android?

**Comment by yeahia2508** [comment]
Yes. Successfully built on Andorid. I don't have sufficient knowledge on iOS so I don't get the meaning of error.

**Comment by hillelcoren** [comment]
It may be related to the Google login feature, we don't check the google-services.json file into GitHub.

**Comment by anil1712** [comment]
I am getting the same issue on iOS. Is anybody got any solution?

**Comment by solaamy** [comment]
I am also getting the same issue when building on Appcenter on iOS. Does anyone get any solution?

**Comment by hillelcoren** [comment]
I think you'd need to disable the Google sign in code.

We'll try to support running the app without the google-services.json file.
