### ISSUE TITLE
MacOS App - Can't tab or place cursor into Line Total input

### ISSUE THREAD

**Issue by ELEV8TEDEV** [invoiceninja/admin-portal#412]
Hi - Sorry this is probably the wrong place to report a bug with the MacOS App - Not sure where to report this.

MacOS 12.2.1
Ninja App 5.0.76 (76)

When creating an invoice, I'm unable to place my mouse cursor or tab into the Line Total input

**Comment by ELEV8TEDEV** [comment]
Thanks. I was in a hurry earlier today and overlooked this.

**Comment by hillelcoren** [comment]
No worries
