### ISSUE TITLE
Partially incorrect translation for "cancel"

### ISSUE THREAD

**Issue by LarsK1** [invoiceninja/admin-portal#414]
Hi there,
currently IncoiceNinja makes a bit of a mess with the translation of "cancel" - now it's translated to "Stornieren" only.
But instead we need to differentiate:
between Invoice cancelation and between progress cancelation.
Therefore the default translation should be "Abbrechen" and in only the following places a separate translation is needed (presumably also in other languages than german):
- ![Screenshot_20220304-143539.png](https://user-images.githubusercontent.com/28981528/156773003-980737fa-f6a7-486d-a100-052d600ff8c4.png)("Stornieren")

Thanks for your great software,
Lars

**Comment by LarsK1** [comment]
Any news on this topic?

**Comment by hillelcoren** [comment]
Nope

**Comment by itkfm** [comment]
That’s pretty much what I’ve meant with #347 – those strings and so on without any context make it pretty hard to get translations right in the first place. If they are applied to multiple but different contexts, you’ll end up with countermanding dialogs (instead of cancelling them).

**Comment by itkfm** [comment]
I really wish there was a better solution than having to guess the context for each string in Transifex.

**Comment by hillelcoren** [comment]
We're open to suggestions...

**Comment by itkfm** [comment]
Wish I had any… :(

**Comment by itkfm** [comment]
Is there anything that holds back this change or translation?
in v5.4.4-C85 you still “countermand” basically the whole German UI

**Comment by itkfm** [comment]
This string does not appear to exist for in Transifex in the first place:
![Screenshot from 2022-06-27 15-03-50](https://user-images.githubusercontent.com/53079668/175948274-4f40b295-ae72-49d2-8108-3537f4f6a7e2.png)

But it’s there in the portal:
![Screenshot from 2022-06-27 15-02-40](https://user-images.githubusercontent.com/53079668/175948270-90718aa7-b286-4c01-bf8e-326b3a959a12.png)

**Comment by itkfm** [comment]
in transifex there’s “abbrechen” two times:
![image](https://user-images.githubusercontent.com/53079668/175948905-66a9fc6f-4fdc-421e-8f05-014fa7612c99.png)

Fun question: which one’s which?

**Comment by hillelcoren** [comment]
@david do you know when the languages were last updated/do you have cancel_invoice in the backend?

**Comment by itkfm** [comment]
v5.5.6-C89

why are there two cancel (“Abbrechen”) buttons with different icons?

![image](https://user-images.githubusercontent.com/53079668/186374320-64cc24bf-f0c0-4e1b-8e2e-a15cc2be75f4.png)

**Comment by hillelcoren** [comment]
The second option should be "Cancel invoice", it may be a problem with the translation
