### ISSUE TITLE
Client Portal domain URL for self hosted

### ISSUE THREAD

**Issue by boka003** [invoiceninja/admin-portal#421]
Hello,
V5

Can you please add this function in self-hosted installation:
![image](https://user-images.githubusercontent.com/9454283/160229803-20d3bbe3-57c2-4684-8662-79303ec7723a.png)

Example: my installation is at invoice.example.com and i will like to show client portal at invoice123.example.com

or how I can make the client login as the default login screen?
When I visit my invoice ninja installation ([invoice.example.com](http://invoice.example.com/)) it will show admin login.
But when I visit [invoice.example.com/public/client/login](http://invoice.example.com/public/client/login) it will show client login.
I will like to show client login at [invoice.example.com](http://invoice.example.com/) and to move admin login in some custom location like [invoice.example.com/administration](http://invoice.example.com/administration)
Is it possible with some customization?

**Comment by hillelcoren** [comment]
https://github.com/invoiceninja/invoiceninja/issues/5079
