### ISSUE TITLE
Enable keyboard combinations to override app defaults

### ISSUE THREAD

**Issue by greyskymedia** [invoiceninja/admin-portal#423]
**What version of Invoice Ninja are you running? v5.3.76

**What environment are you running?**
Dedicated Ubuntu

**Have you searched existing issues/requests?**
Yes

**Request**
I'm using Invoice Ninja full time now, and through use I'm finding that there are a number of enhancements that would make using the App (Mac App, specifically) a lot easier:
- In selects (dropdowns), allow us to type a name, then press down on the key board to select that thing
- Allow us to hold a keyboard key then click and drag to select text(since horizontal scrolling is enabled, and I have a Magic Mouse it's very difficult to quickly highlight text
- It'd be nice to turn off "training wheels" (tool tips)

Thanks!

**Comment by hillelcoren** [comment]
Just to note you can click enter to select an item in the dropdowns

**Comment by hillelcoren** [comment]
#2 we can add an optional setting
#3 I'd prefer to leave as is
