### ISSUE TITLE
Windows app - crash

### ISSUE THREAD

**Issue by tixsys** [invoiceninja/admin-portal#425]
Crash when opening task panel, clicking columns and clicking on dropdown.

latest version.

**Comment by hillelcoren** [comment]
Thanks for reporting this.

Do you mean you're clicking the columns button in the lower right corner of the screen on the tasks list?

Do you see problems using the tabs on Settings > Invoice Design?

**Comment by tixsys** [comment]
1. yes im clicking on bottom right cornet button. and then to dropwown ehre other columns should be listed.
2. yes. clicked on client details  - app exited by itself.

**Comment by hillelcoren** [comment]
Other users have reported this issue but we haven't been able to replicate it yet.

Which version of Windows are you using?

**Comment by hillelcoren** [comment]
I believe this is the underlying issue: https://github.com/flutter/flutter/issues/103808
