### ISSUE TITLE
Combine multiple companies in report

### ISSUE THREAD

**Issue by boka003** [invoiceninja/admin-portal#426]
Hello,

V5 / self-hosted

In new v5 option to add more companies helps a lot.

But if we start generating reports, it is possible to run a report only within one company

It would be great if we could choose more companies when creating the report

Example: show me all payments from company A and company B

**Comment by hillelcoren** [comment]
Hi,

By design all companies are completely separate.

One option may be to use the groups feature to create virtual sub-companies under one main company.

**Comment by boka003** [comment]
Hi,

If we can add 1 user to more than 1 company, that will work.

But now, 1 user can be only in 1 company?


Regards

**Comment by hillelcoren** [comment]
In v5 users can be added to multiple companies

**Comment by boka003** [comment]
I can see only select option, or is there a other way:

![image](https://user-images.githubusercontent.com/9454283/160785850-29b301af-37a0-40b2-9820-46d4831f9583.png)

**Comment by hillelcoren** [comment]
I don't understand what you're trying to accomplish.

Above you wrote "1 user can be only in 1 company" but that's the edit client screen?
