### ISSUE TITLE
Android 7.1.2 Crash

### ISSUE THREAD

**Issue by bitsnaps** [invoiceninja/admin-portal#428]
Crash on Android v7.1.2 with no error message at the startup.
NB. No google play/services installed (custom ROM).

**Comment by hillelcoren** [comment]
How are you installing the app?

**Comment by hillelcoren** [comment]
I've never heard of that site.

The app is available on the Play Store and F-Droid
- https://play.google.com/store/apps/details?id=com.invoiceninja.app
- https://f-droid.org/packages/com.invoiceninja.app/

**Comment by hillelcoren** [comment]
If you install the app from F-Droid then Google Services aren't needed
