### ISSUE TITLE
Impossible to type text in login form fields, or any text field once logged in

### ISSUE THREAD

**Issue by raphraph** [invoiceninja/admin-portal#430]
**What version of Invoice Ninja are you running?**
v5.3.60~ynh1

**What environment are you running?**
Self-hosted (Yunohost)

**Have you checked log files (storage/logs/) Please provide redacted output** no but checked browser console output

**Have you searched existing issues?** yes

**Have you reported this to Slack/forum before posting?** no but I checked if other reported this and did not find anything...

**Describe the bug**

This bug occurs in Firefox (100.0b2 but also previous versions) on Ubuntu 21.10.

When trying to log in some keyboard inputs are not working. I can copy/paste text into the fields, or type numbers from the keypad but I can't type any letters.
When typing a letter in the form field the console output shows:

`f at flt-glass-pane /editable false` with `f` being the letter I tried to type.

**Steps To Reproduce**
Try to type login information with same setup.

**Expected behavior**
I should be able to type letters.

**Screenshots**
NA

**Additional context**

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**
Yes I can reproduce the problem on the demo site in any editable textfield.

**Comment by hillelcoren** [comment]
Please let us know if you see the problem with the latest version of the app.

**Comment by raphraph** [comment]
This is the first version I try so I can't answer for previous versions.

I tried the Linux snap app but I can't login I have a server error: `Error: please check that Invoice Ninja v5 is installed on the server`

But this has nothing to do with this problem. Probably a config problem of my yunohost.

**Comment by raphraph** [comment]
The notification makes me react just in case it interests you : I juste made new tests and the bug might be due to a firefox extension or setting because the demo webapp works fine in a private firefox tab and in chrome.

I looked quickly and did not find the cause.
I will comment here if I ever find out.

**Comment by hillelcoren** [comment]
Thanks for the update!
