### ISSUE TITLE
Button to “Create invoice from tasks” went missing

### ISSUE THREAD

**Issue by itkfm** [invoiceninja/admin-portal#432]
*v5.3.79-C78*

According to my workmates the button to “Create invoice from tasks” went missing. Any ideas?

If this is on purpose: How to create an invoice from multiple tasks?

<details>
<summary>Screenshot </summary>

![image](https://user-images.githubusercontent.com/53079668/164442588-48d726ec-376a-4e62-972c-889956d67cb5.png)

</details>

**Comment by turbo124** [comment]
@hillelcoren

**Comment by itkfm** [comment]
cannot reproduce in demo, **but** demo also runs older *C77* frontend

**Comment by hillelcoren** [comment]
Thanks for reporting this!

**Comment by itkfm** [comment]
you’re welcome! (would be nice to have this released soon)
