### ISSUE TITLE
Translation: Notifications for “:count invoices sent”

### ISSUE THREAD

**Issue by itkfm** [invoiceninja/admin-portal#433]
Please help me fix this translation. What is it supposed to say? Can’t find anything broken on Transifex.

![image](https://user-images.githubusercontent.com/53079668/165563265-42b0b609-b51a-407f-bc54-4c1b4d75769b.png)

![image](https://user-images.githubusercontent.com/53079668/165563489-d021f2a0-6c0a-4fb1-b813-13c9274ae67a.png)

**Comment by hillelcoren** [comment]
Thanks for reporting this!

**Comment by itkfm** [comment]
you’re welcome
