### ISSUE TITLE
Translation: Letter

### ISSUE THREAD

**Issue by itkfm** [invoiceninja/admin-portal#435]
![image](https://user-images.githubusercontent.com/53079668/165577416-1d0ad7f6-d635-4456-a2f6-0d07a1bd6384.png)

Is this a letter as in character?
Or as in mail?
Or as in paper format (like DIN A4, DIN A5, Letter, …)

**Comment by hillelcoren** [comment]
I think Slack may be a better place for this...

http://slack.invoiceninja.com/

**Comment by hillelcoren** [comment]
I believe it's 'Letter' as in page format

**Comment by itkfm** [comment]
Is there a reason why your Slack instance’s TLS cert has not been renewed?

**Comment by itkfm** [comment]
(or whatever is behind port 443 on slack.invoiceninja.com)

**Comment by hillelcoren** [comment]
@turbo124 any thoughts?
