### ISSUE TITLE
Windows desktop app icon too small

### ISSUE THREAD

**Issue by mrkylegp** [invoiceninja/admin-portal#438]
The Windows desktop app has a really small and dark icon.

When invoiceninja is pinned to the taskbar, it's unrecognisable:

![Screenshot 2022-05-04 105655](https://user-images.githubusercontent.com/52687659/166610185-6cccee6b-0a88-4d9f-90ba-6ea77acfa9ef.png)

Before it used to be the invoiceninja envelope...

**Comment by hillelcoren** [comment]
Thanks for letting us know, we'll look into it
