### ISSUE TITLE
Self-hosted login - GUI behaviour issue  - Not showing Hosted/Self-Hosted selector by default

### ISSUE THREAD

**Issue by mrkylegp** [invoiceninja/admin-portal#440]
There is a GUI issue with the Windows Desktop App (and I believe this was occurring on Android too)

When you first open the app, it is on the login tab but there is no apparent option to log in to "self-hosted". There is no selection between Hosted and Self-hosted as seen below:

![Screenshot 2022-05-12 113936](https://user-images.githubusercontent.com/52687659/167974793-430104fa-5b4a-4744-9ccd-338a6941881a.png)

However, if you click on the login tab again, then suddenly you get the choice between hosted and self-hosted.

![Screenshot 2022-05-12 113934](https://user-images.githubusercontent.com/52687659/167974810-cf840565-0d65-4185-92e3-5e1ca0be279a.png)

It's a small thing that will confuse a lot of users looking to login to self-hosted installs, in my opinion.

The simple solution is to ensure the login box always presents the options

**Comment by hillelcoren** [comment]
Unless I'm misunderstanding the behavior looks correct to me, a selfhost system can only have one account so the option to sign up is hidden.

**Comment by mrkylegp** [comment]
> Unless I'm misunderstanding the behavior looks correct to me, a selfhost system can only have one account so the option to sign up is hidden.

@hillelcoren 
Let's say the user is self hosting. They've just installed Invoice Ninja then downloaded the desktop app, and opened it up.

By default, it doesn't show the fields to log in with self-hosted credentials so it's confusing to the user where to enter the URL, secret etc. If they just enter their username and password for their self hosted install, login isn't going to work because the default fields are for a hosted scenario (eg. not showing URL etc).

Only if you click on the "Login" tab at the top do you then get the options for either hosted login fields or self-hosted login fields.

**Comment by hillelcoren** [comment]
It seems correct to me, you can't use the app to signup to a selfhost app so the user needs to select login. 

What change are you suggesting?

**Comment by mrkylegp** [comment]
> It seems correct to me, you can't use the app to signup to a selfhost app so the user needs to select login.
> 
> What change are you suggesting?

Instead of this showing on opening the app:
![Screenshot 2022-05-12 113936](https://user-images.githubusercontent.com/52687659/167992960-04695685-1318-487d-bef1-ea1c592ed752.png)


Show this by default instead:
![Screenshot 2022-05-12 113934](https://user-images.githubusercontent.com/52687659/167992977-a6688994-8e97-421c-a278-6e399f72c63f.png)

**Comment by hillelcoren** [comment]
Thanks for the feedback, we'll consider it

**Comment by mrkylegp** [comment]
> Sorry, I didn't realize login was selected by default. In that case it's a bug.

Well it may not be technically, but it appears so.

Upon opening the app, it's asking for login credentials so this gives the user the impression that it is on the login tab. However if you click the Login tab, it turns blue (to show it's selected) and you get more login options. This is the whole reason for the confusion. Why not simply display everything as per the second image above and all confusion is eliminated.

**Comment by hillelcoren** [comment]
In the next version of the app we're adjusting the UI, it will default to login and creating an account will be a secondary option.
