### ISSUE TITLE
"Client portal" link in app does nothing

### ISSUE THREAD

**Issue by mrkylegp** [invoiceninja/admin-portal#442]
In the invoice ninja mobile app (I'm using Android) and perhaps other apps too, the "Client Portal" link under the three dots menu for an invoice for a client doesn't do anything.

In the browser this works as expected by taking you to the admin portal logged in as that client to show you what they see.

![Screenshot_20220516-204944_Invoice Ninja_1.png](https://user-images.githubusercontent.com/52687659/168577164-0b2bf33a-d280-4fa8-886d-41727c978dcc.png)

**Comment by hillelcoren** [comment]
If you select the contacts tab and then click the view portal button does it work?

**Comment by mrkylegp** [comment]
> If you select the contacts tab and then click the view portal button does it work? 

@hillelcoren 
Yes, it works when accessing the link from a client directly but not from an invoice.

**Comment by hillelcoren** [comment]
Does this problem still exist?

**Comment by mrkylegp** [comment]
> Does this problem still exist?

No, it seems to work now. Closing.
