### ISSUE TITLE
Error in translation on "Invoice Sent" in Notifications

### ISSUE THREAD

**Issue by Napsty** [invoiceninja/admin-portal#443]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30** 5.3.86

**What environment are you running?** ZIP / Self-Hosted

**Have you checked log files (storage/logs/) Please provide redacted output** N/A

**Have you searched existing issues?** Yes

**Have you reported this to Slack/forum before posting?** No

**Describe the bug**
There seems to be an error with the translation string on "Invoice Sent". Switching to a different language than English doesn't show the correct translation. 

In 5.3.86, the row is empty (here French):

![image](https://user-images.githubusercontent.com/3702203/169650763-699bb1b0-336d-40b4-abe7-5b417e31235f.png)

In 5.3.84, the row is somewhat correct, but seems to use a different translation string (German here):

 ![image](https://user-images.githubusercontent.com/3702203/169650827-a168c099-d468-4bcb-ae7f-c0d4818b3bd7.png)

**Steps To Reproduce**
- Switch language to any other language than English (even English - United Kingdom)
- Navigate to Settings -> User Details -> Notifications
- Note the missing or wrong translation between "Invoice Created" and "Invoice Viewed"

**Expected behavior**
The correct translation for "Invoice Sent" is shown.

**Comment by hillelcoren** [comment]
Thanks for reporting this issue!

In the latest version I don't see a blank value, but the value which is shown is incorrect. 

In the next version we've added a new tag for this in [Transifex](https://www.transifex.com/invoice-ninja) - invoice_sent_notification_label
