### ISSUE TITLE
Dismiss Upgrade Banner

### ISSUE THREAD

**Issue by htbrown** [invoiceninja/admin-portal#450]
**What version of Invoice Ninja are you running? ie v4.5 / v5**
v5.4.1-C85

**What environment are you running?**
Docker

**Have you searched existing issues/requests?**
Yes - I found someone [asking about it on the forum](https://forum.invoiceninja.com/t/why-do-i-have-upgrade-button-self-hosted-v5/10537) with no response but, to the best of my ability, couldn't find anything about it here.

**Screenshots**
![image](https://user-images.githubusercontent.com/28675646/174113891-4a2ba0d3-2d20-437d-874f-2a0b3e688c80.png)

**Additional context**
Upon updating Invoice Ninja today, I noticed that a green upgrade button had appeared at the top of my sidebar. While purchasing the white-label licence would definitely be something I would consider in the future should the need arise, currently I do not see the value in upgrading for a company of my size.

While I appreciate the rationale of having said upgrade button there, it would be nice if it was the kind of thing that showed up by default and could be dismissed if the upgrade isn't desired. As you mention in your README, the self-hosted version of Invoice Ninja comes with all features of your hosted Pro and Enterprise plans activated and, as other projects like Bitwarden do, having an upgrade button which sticks out as much as it does falls slightly short of this in my opinion.

Of course, this is a very minor complaint - feel free to merely close this if you disagree with me. Invoice Ninja has been a great help to me and is one of the only quality self-hosted projects for invoicing available currently. Once again, purchasing the white-label licence would definitely be a consideration if my needs were to grow in the future.

**Comment by hillelcoren** [comment]
Thanks for the feedback, we'll work to improve this.
