### ISSUE TITLE
Refresh button in the interface

### ISSUE THREAD

**Issue by mrkylegp** [invoiceninja/admin-portal#454]
Invoice ninja really needs a refresh data button in the interface or better realtime updating of data.

In the browser this isn't critical because you can refresh the page easily but on the mobile or desktop apps for invoice ninja, there is no way to refresh data. 

In a lot of mobile apps you can simply pull down to refresh data but the invoice ninja mobile app doesn't offer this. There's also no way to refresh data in the desktop app.

In order to refresh data in the desktop or mobile apps you have to close them and reopen them.

This is a suggestion for a refresh button in the interface which would refresh and recheck for updated data. Sometimes I do something on the desktop then check my mobile app and it's showing old data until I quit and reopen the app.

**Comment by hillelcoren** [comment]
Thanks for the feedback! We're open to improving this but want to make sure you're aware of the current options.

If you refresh the webpage it will load any changes, you can also click the refresh icon in the lower right corner on the table screens. The app also runs an automatic check for changes every 5 minutes. 

The mobile apps do support pull to refresh, where are you pulling?

**Comment by mrkylegp** [comment]
@hillelcoren Pull to refresh does work in the app except for in the quotes list I just discovered. I can create a separate issue for that?

**Comment by hillelcoren** [comment]
Are you seeing an error meesage?

**Comment by mrkylegp** [comment]
> Are you seeing an error message?

No, there is simply no pull down behavior on the quotes page. When I pull down, nothing happens at all.

**Comment by hillelcoren** [comment]
Thanks, we'll look into it

**Comment by hillelcoren** [comment]
I think this is tracked here: #459

**Comment by mrkylegp** [comment]
> I think this is tracked here: #459

@hillelcoren Not the same issue. This is a suggestion for a refresh button itself for web or desktop apps. Issue #459 refers to a bug with the mobile app

**Comment by hillelcoren** [comment]
As explained above there is a refresh button on all table views
