### ISSUE TITLE
Private Company Documents

### ISSUE THREAD

**Issue by o0-o** [invoiceninja/admin-portal#457]
When I set up my account, I uploaded some company documents (EIN registration, DBA paperwork, etc). After sending an invoice, I realized that all of these documents are visible to the client. Nothing in the interface indicates that this would be the case. Nothing truly confidential was in the documents, so no real harm was done, but I think the UI/UX here is misleading.

That said, I like the idea of having my W9 available in this way, but ideally, I would have some documents exposed to clients and some not.

**Comment by hillelcoren** [comment]
This is now supported
