### ISSUE TITLE
Recurring Invoices - add name

### ISSUE THREAD

**Issue by mskenderian** [invoiceninja/admin-portal#458]
**What version of Invoice Ninja are you running? ie v4.5 / v5**
v5

**What environment are you running?**
Hosted by invoiceninja

**Have you searched existing issues/requests?**
Yes

**Additional context**
I create a recurring invoices for my clients, for different services, since each service starts on a different date. Some clients have multiple recurring invoices, from the main view for recurring invoice, i wish we can name the invoices, for example Hosting, Web Site Maintenance. i would like to be able to name the recurring invoice and see it from the main view.

**Comment by hillelcoren** [comment]
This will be fixed in the next release
