### ISSUE TITLE
Pull to refresh doesn't work in mobile app if there isn't enough entries populating the list.

### ISSUE THREAD

**Issue by mrkylegp** [invoiceninja/admin-portal#459]
In the Android app (and I assume iOS), if you try to pull to refresh data when there are not enough entries, say only one or two (not requiring you to scroll to view them) then pull to refresh behaviour doesn't work.

For example if you have one active quote in the quotes section and try to pull to refresh, it won't work. This is the same for any other area of the app without enough entries. 

Doesn't work in this situation (and no animation):

![20220715_090242.jpg](https://user-images.githubusercontent.com/52687659/179115766-9dd55b1b-8dea-4d08-90a4-4e00acf6b205.jpg)

But works in this situation:
![20220715_090311.jpg](https://user-images.githubusercontent.com/52687659/179115832-570a2e64-9eea-4264-8651-8131bdaaa205.jpg)

**Comment by mrkylegp** [comment]
Any rough ETA for this to be resolved? Have to quit the app and reopen to get data to refresh sometimes while on the go.

**Comment by hillelcoren** [comment]
Sorry, we aren't able to provide ETAs for future changes
