### ISSUE TITLE
add optional setting to auto-fill a new invoice's "item" column

### ISSUE THREAD

**Issue by oliversum-ch** [invoiceninja/admin-portal#460]
When I invoice a bunch of tasks, the item column in the “new invoice” view remains empty. It would be useful to add an optional setting to make the app auto-fill that field with the project.

**Comment by hillelcoren** [comment]
Just wanted to suggest a potential workaround:

- On Settings > Custom Fields > Tasks and a new field called `Project`
- On Settings > Invoice Design > Task columns remove the `Service` field and add `Project` in it's place

The downside to this approach is you'll end up with extra UI elements (project on task edit and item on invoice edit)
