### ISSUE TITLE
Tax Rate in Expenses

### ISSUE THREAD

**Issue by Strider27** [invoiceninja/admin-portal#462]
Tax Rate is not an option in expenses unless "item tax rates" are enabled,
After reading the forums here (https://forum.invoiceninja.com/t/expenses-taxes-feature-request/5944/4)
@hillelcoren mentions that the item tax rates need to be enabled because "If you invoice an expense the app needs to be able to map the line item taxes"

This can potentially cause an issue with PO's when converted to expense and then the expense converted to invoice. How is the total tax tracked if the item tax rates are not enabled.

I believe, the tax rate should be enabled in both cases (like in v4).

- If item tax is enabled, when the expense is billed both net + item tax is mapped.
- If item tax is disabled, when the expense is billed only net is mapped (and the tax is calculated as the total on the invoice side) (maybe add a warning that the tax rate isn't passed on? if that's a worry)

This makes sense at least where we do business, if we buy a PC from a local supplier for 1000 ex VAT, we would pay 1230 (@23% Tax)
If we would then convert the expense to invoice we would want the invoice to be 1000 ex vat + 23% global VAT

**Comment by hillelcoren** [comment]
We've added a new expense tax rates option on Settings > Tax Rates

**Comment by Strider27** [comment]
> We've added a new expense tax rates option on Settings > Tax Rates 

Just a heads up, the c89 admin panel is missing the expense tax label in settings>tax settings.

![Screenshot_20220803-195631_Vivaldi Browser.jpg](https://user-images.githubusercontent.com/12703885/182687954-990a27f4-f9be-43dd-a5b2-18da666489b6.jpg)

**Comment by hillelcoren** [comment]
Thanks, this should be corrected in the next release
