### ISSUE TITLE
i18n Wrong translations

### ISSUE THREAD

**Issue by JordyHers** [invoiceninja/admin-portal#463]
Most of the translations in i18n[mixin] not available.

I can work on this issue.
Other errors already mentioned

**Comment by hillelcoren** [comment]
Sorry, I'm not sure what you mean?

Note: the translations are managed here: transifex.com/invoice-ninja

**Comment by JordyHers** [comment]
Hi again sorry @hillelcoren 
I didn't know transifex was already implemented in the project and all **localizations** were handled there. The forked version I have has translation inaccuracy. This issue can be closed.
