### ISSUE TITLE
[UX] Font Size in Desktop App

### ISSUE THREAD

**Issue by Strider27** [invoiceninja/admin-portal#468]
Any way to let us control the UI font size in the desktop app? We usually set the webversion to 80% as it is too big for me on a 24 inch monitors. But no way to set scaling in the app.

**Comment by hillelcoren** [comment]
There's an option to adjust the font size in the app on Settings > Device Settings

**Comment by Strider27** [comment]
I'm so sorry, I'm a fool, missed it somehow.

Unfortunately small seems to be too small :(
if we had a way to set the actual fontsize. But this is a minor cosmetic thing, feel free to close.
