### ISSUE TITLE
App crashes on Wayland

### ISSUE THREAD

**Issue by hmnd** [invoiceninja/admin-portal#470]
Invoice Ninja crashes when trying to launch under KDE Plasma, Wayland. Unsure if this crash was only recently introduced.
Logs:
```bash
❯ /snap/invoiceninja/current/bin/invoiceninja
flutter: ## ERROR (app_middleware - load state): State does not exist on file
(invoiceninja:844549): Gdk-CRITICAL **: 21:51:55.954: gdk_monitor_get_geometry: assertion 'GDK_IS_MONITOR (monitor)' failed
(invoiceninja:844549): Gdk-CRITICAL **: 21:51:55.954: gdk_monitor_get_workarea: assertion 'GDK_IS_MONITOR (monitor)' failed
(invoiceninja:844549): Gdk-CRITICAL **: 21:51:55.954: gdk_monitor_get_model: assertion 'GDK_IS_MONITOR (monitor)' failed
(invoiceninja:844549): Gdk-CRITICAL **: 21:51:55.954: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed
[1]    844549 segmentation fault (core dumped)  /snap/invoiceninja/current/bin/invoiceninja
```

**Comment by hillelcoren** [comment]
Hi,

Which version of the app are you using?

**Comment by hmnd** [comment]
Latest available snap, v5.0.89.

**Comment by hillelcoren** [comment]
Was the previous version working for you?

**Comment by hmnd** [comment]
Hmm is there a way to install the previous version? I just switched back to Wayland, and was already on 5.0.89.

**Comment by hillelcoren** [comment]
https://unix.stackexchange.com/a/448349

**Comment by hmnd** [comment]
Hmm it seems that only the latest version of Invoice Ninja is [published on snapcraft](https://snapcraft.io/invoiceninja) :(

**Comment by hmnd** [comment]
Any chance you could share a built snap for me to manually install?

**Comment by hillelcoren** [comment]
[bundle.zip](https://github.com/invoiceninja/admin-portal/files/9239865/bundle.zip)

**Comment by hmnd** [comment]
Thanks, that runs perfectly!
