### ISSUE TITLE
billingclient in F-Droid build

### ISSUE THREAD

**Issue by linsui** [invoiceninja/admin-portal#473]
The `in_app_purchase` [depends on](https://github.com/flutter/plugins/blob/e8a7abcd654f53d9111cb273dd24a7a7c5974b7a/packages/in_app_purchase/in_app_purchase_android/android/build.gradle#L56) `com.android.billingclient:billing:5.0.0` which is not foss. Could you please remove it from the FOSS build? Thanks!

**Comment by hillelcoren** [comment]
Sure, we'll work on it...
