### ISSUE TITLE
Can not test the app with the given credentials .

### ISSUE THREAD

**Issue by OmarAbdelazeem** [invoiceninja/admin-portal#480]
I don't have an Invoice Ninja backend and I tried to test the app with the given credentials :

Email: demo@invoiceninja.com
Password: Password0
URL: demo.invoiceninja.com

but I am facing this error :

## ERROR (app_middleware - load state): State does not exist on file
I/AssistStructure(11821): Flattened final assist data: 876 bytes, containing 1 windows, 5 views
I/flutter (11821): POST: https://demo.invoiceninja.com/api/v1/login?first_load=true&include_static=true

I/flutter (11821): ## Login error: TimeoutException after 0:01:00.000000: Future not completed
E/flutter (11821): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: TimeoutException after 0:01:00.000000: Future not completed

**Comment by hillelcoren** [comment]
Does the demo app load for you: https://demo.invoiceninja.com

**Comment by OmarAbdelazeem** [comment]
No , I cloned the project and tried to login in with this credentials (self hosted) but it failed

**Comment by hillelcoren** [comment]
I'm not sure, does the demo work for you?

**Comment by OmarAbdelazeem** [comment]
This line does not work 
https://demo.invoiceninja.com/
The cloned project work but I can't login

**Comment by hillelcoren** [comment]
I think it may be a networking issue preventing you from reaching the site
