### ISSUE TITLE
Uploading a logo into a newly created group's settings resets some (or all?) of the settings?

### ISSUE THREAD

**Issue by nekohayo** [invoiceninja/admin-portal#481]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5 at https://demo.invoiceninja.com

**What environment are you running?**
Demo SaaS environment (but in day-to-day I'm a customer of your v4 SaaS)

**Have you searched existing issues?**
Yes

**Have you reported this to Slack/forum before posting?**
No

**Steps To Reproduce**
1. Go to settings, then Group settings
2. Create a new group, go to edit its settings, enter its name, "Esthar shipping co.", hit save, enter its address as "123 Laguna way", save
3. Go to the logo tab, upload a random jpeg image. Notice the save button is grayed out, oh well, guess it auto-saves for uploading logos
4. Go back to the first tab (Details) or the 2nd tab (Address) and notice that ALL previously entered and saved data has been cleared! And this is not just a visual bug, if you exit/re-enter the group, you will see that data has indeed been cleared.
5. Pass go and collect 200$

**Expected behavior**
Do not lose data.

**Additional context**
I will accept fat cheques for this Premium Quality bug report :)

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**
Yes

**Comment by hillelcoren** [comment]
Thanks for reporting this, we'll look into it
