### ISSUE TITLE
"Learn More" button under Square links to Stripe support page

### ISSUE THREAD

**Issue by mrkylegp** [invoiceninja/admin-portal#482]
Under the Square payment gateway fees tab, there is a learn more button.

It opens a Stripe support article, not a Square one.

![Screenshot 2022-08-12 000239](https://user-images.githubusercontent.com/52687659/184151793-e115d9bc-b6f2-4fda-8eac-bd53fae80b01.png)

**Comment by hillelcoren** [comment]
Duplicate of #351
