### ISSUE TITLE
Expenses - Currency changes to US Dollar

### ISSUE THREAD

**Issue by mrkylegp** [invoiceninja/admin-portal#488]
When creating a new expense, the localisation options should be respected. I'm using AUD.

You can see that when I create a new expense, initially AUD is set as expected.

However if I go to create a new vendor then back out back to the first menu, the currency changes to US dollar.

Video demonstrating it on the android app here, but I'm sure it would affect web versions too.

https://youtube.com/shorts/3dv2UvAx8Gc?feature=share

**Comment by hillelcoren** [comment]
Thanks for reporting this!
