### ISSUE TITLE
Expenses - Dots menu does nothing when pressed 

### ISSUE THREAD

**Issue by mrkylegp** [invoiceninja/admin-portal#489]
Under the create new expense page on Android, the dots menu doesn't do anything when pressed. Redundant UI.

![Screenshot_20220901-232624.jpg](https://user-images.githubusercontent.com/52687659/187925666-1b9764be-7d7e-44f2-9237-e00031be7b82.jpg)

**Comment by hillelcoren** [comment]
Thanks, we'll make sure it's corrected
