### ISSUE TITLE
Column cut off horizontally / Columns not displayed

### ISSUE THREAD

**Issue by mrkylegp** [invoiceninja/admin-portal#493]
In the admin panel, any section, if you have too many column options selected the text and/or additional columns are cut off horizontally and there is no way to horizontally scroll. This means that if you add several columns, you can't actually see them because you can't scroll horizontally.

Need to introduce a horizontal scroll bar if the amount of columns chosen to be shown exceeds the space available in the browser (or if the user resizes the window)

**Comment by hillelcoren** [comment]
Thanks for the feedback! I'm able to scroll horizontally using two fingers on the trackpad but it would be good to add a scrollbar as well.

**Comment by mrkylegp** [comment]
@hillelcoren I'm using a desktop with keyboard and mouse. Not possible in that case.

**Comment by hillelcoren** [comment]
I've retested this, you should see a horizontal scrollbar if you move your mouse by the bottom of the table.

**Comment by mrkylegp** [comment]
> I've retested this, you should see a horizontal scrollbar if you move your mouse by the bottom of the table.

It's at the very bottom of the list...meaning that if you have 100 entries in view, you have to scroll to the bottom of the page to then use the horizontal scroll and then scroll back up to view the entry. There needs to be a sticky horizontal scrollbar so that a horizontal scrollbar is always in view when the user needs it.

Here's a vid from the invoice ninja demo which shows the issue: https://youtu.be/LwvsMasq0RI

Notice two issues here.

1. I have to scroll down in order to scroll horizontally, then scroll back up. Very counter intuitive. 
2. There are a lot of blank rows because I have chosen to display 100 per page but if there are not even 100 entries for that given page, it ends up showing blank rows. I reported this in #492
