### ISSUE TITLE
Cancel button for client settings doesn't work

### ISSUE THREAD

**Issue by mrkylegp** [invoiceninja/admin-portal#494]
The Cancel button for client settings doesn't work.

Steps to reproduce

1. Go to Clients on the left hand menu
2. Choose the dots menu for a client and click settings
3. Press the cancel button in the top right hand corner. Observe that nothing happens and invoice ninja does not return back to the client list as expected
![Screenshot 2022-09-09 184720](https://user-images.githubusercontent.com/52687659/189310718-040fb383-9502-404b-ab65-ddd6d5a1a2ef.png)

**Comment by hillelcoren** [comment]
This is by design. The main modules of the app (ie. clients, invoices) have list and edit screens, clicking cancel returns from the edit to the list. The setting screens only have an edit screen so clicking cancel will clear any changed settings.

**Comment by mrkylegp** [comment]
@hillelcoren Strange design in my opinion. You have other areas where when clicking cancel, it takes you back to the screen where you came from before. This is how I get the impression it should work. In this case it doesn't, but you're saying it clears? The button should be labelled "Clear" in that case. Also, there is no way to return back to the same spot on the client page if you click on settings for a client and want to cancel. Only way to go back to clients is by clicking clients on the left menubar which wouldn't take you back to the spot you were in on the client list.

**Comment by hillelcoren** [comment]
We're open to changing the design, just to need to figure out what's best... 

If it was labeled 'clear' people may think it will clear the form. 

You can click the client filter to return to the client screen.

**Comment by hillelcoren** [comment]
In the next release clicking back will return you to the last page of data you were on
