### ISSUE TITLE
More columns in "Reports" > "Profit and Loss"

### ISSUE THREAD

**Issue by danielkoch** [invoiceninja/admin-portal#496]
It would be nice if more columns are selectable in the settings of “Profit and Loss” report.

To be able to generate more useful reports it would be good to select columns like:

- taxes
- currency
- transactional reference

**Comment by hillelcoren** [comment]
Which columns would you'd like to see added?

**Comment by danielkoch** [comment]
Form was submitted too early 😊

**Comment by hillelcoren** [comment]
I've added currency and transactional reference but I'm not able to add taxes. The P&L report uses payments to calculate the profit but taxes are stored on the invoice.
