### ISSUE TITLE
Scroll bar should be always visible - Clients list on invoice creation

### ISSUE THREAD

**Issue by mrkylegp** [invoiceninja/admin-portal#497]
When creating an invoice with multiple contacts that overflow the size of the box, a scroll bar is not always visible.

My suggestion would be to have an always visible scroll bar if there are more contacts to view. Many browsers automatically decide to hide the vertical scrollbar when not scrolling.

This means that it's not possible to see additional contacts unless you know they exist and decide to scroll down in this contact list window.

![Screenshot 2022-09-17 105711](https://user-images.githubusercontent.com/52687659/190834363-8277b62b-8ff4-4818-baa6-7fb9f653be03.png)
![Screenshot 2022-09-17 105810](https://user-images.githubusercontent.com/52687659/190834366-fe885d23-53ca-4fd3-9fe5-69a8cabca109.png)

**Comment by hillelcoren** [comment]
Thanks for the suggestion, this has been implemented.
