### ISSUE TITLE
Unable to open fileselector for uploading company logo in desktop app

### ISSUE THREAD

**Issue by nebulade** [invoiceninja/admin-portal#498]
Server version 5.5.24
Desktop app version 5.0.73

**What environment are you running?**
Flutter bundle downloaded from website running on Archlinux

**Describe the bug**
When trying to upload a company logo, the app throws the following error in the terminal:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method checkPermissionStatus on channel flutter.baseflow.com/permissions/methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165)
<asynchronous suspension>
invoiceninja/invoiceninja#1      MethodChannelPermissionHandler.checkPermissionStatus (package:permission_handler_platform_interface/src/method_channel/method_channel_permission_handler.dart:16)
<asynchronous suspension>
invoiceninja/invoiceninja#2      pickFile (package:invoiceninja_flutter/utils/files.dart:36)
<asynchronous suspension>
invoiceninja/invoiceninja#3      _CompanyDetailsState.build.<anonymous closure>.<anonymous closure> (package:invoiceninja_flutter/ui/settings/company_details.dart:438)
<asynchronous suspension>
```

**Comment by hillelcoren** [comment]
It looks like you're using an older version of the desktop app, the latest version is 5.0.93

**Comment by nebulade** [comment]
Oh ok, I was using https://download.invoiceninja.com/linux/bundle.zip which seems to still deliver the old version then apparently. Looks like this is not even the installation method which is suggested but I would have to get snapd of sorts running. I guess I can close this then until I figure out how to install the latest.

**Comment by nebulade** [comment]
The link is mentioned in the archlinux package build https://aur.archlinux.org/packages/invoiceninja-desktop which is also outdated though. Archlinux does not really have snapd supported well, which is probably why this was stopped being maintained.

**Comment by hillelcoren** [comment]
Thanks!
