### ISSUE TITLE
On invoice detail page - Wrong Balance Due (with global percentage discount and product tax)

### ISSUE THREAD

**Issue by yvalentin** [invoiceninja/admin-portal#501]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.3.67-C77
But I have try on your demo site (v5.5.23-C93)
And the error is present too.

**What environment are you running?**
Other, On demand server with git clone deployment

**Have you checked log files (storage/logs/) Please provide redacted output**
No
**Have you searched existing issues?**
Yes
**Have you reported this to Slack/forum before posting?**
No
**Describe the bug**
If we enable product tax on setting and create a new invoice. And in this invoice we add a global discount and a product line with taxes.
The total of this invoice is not good but we have the good amount on PDF viewer
You can check the screenshot in example

**Steps To Reproduce**
- Enable setting for product tax and add a tax (ex: 20%)
- Create a new invoice with a product line and select the tax (ex: 20%)
- Add a global percentage discount (ex: 25%) 

**Screenshots**
This screenshot provide from you demo site
![http_demo invoiceninja com-2022 09 30-13_43_13](https://user-images.githubusercontent.com/1521862/193265904-fd3f329f-5200-4ac3-99ec-b6c73e0e4fbd.png)

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**
Yes

**Comment by hillelcoren** [comment]
Thanks for reporting this, it will be fixed with the next release.
