### ISSUE TITLE
Tasks status - Mobile App Issue

### ISSUE THREAD

**Issue by nexitpl** [invoiceninja/admin-portal#503]
Version 5.5.30
On Premise Server 

on iPad and iPhone tasks statuses are always “Saved” (gray background) (on the tasks list) even if I change them to any other with different color background. In the tasks details it shows ok, but on the list every task  is “Saved” 

But on the desktop app - MacOS, tasks shows proper status on the tasks list.  And that happened after a few updates back (don’t remember which one was that) 

1. Reinstalled app on iPad and it’s the same.

**Comment by hillelcoren** [comment]
We've checked in a fix which will be included with the next version of the app.
