### ISSUE TITLE
PDF Preview doesn't work in Firefox with Content Type PDF set to Save File

### ISSUE THREAD

**Issue by Morpheus0x** [invoiceninja/admin-portal#505]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.5.22-C93

**What environment are you running?**
Git Branch v5-stable

**Have you checked log files (storage/logs/) Please provide redacted output**
Not applicable

**Have you searched existing issues?**
Yes

**Have you reported this to Slack/forum before posting?**
No

**Describe the bug**
Embedded PDF preview doesn't work with specific Firefox configuration

**Steps To Reproduce**
Using Firefox Browser with the following settings:
Settings -> General -> Applications (about:preferences#general)
For Content Type `Portable Document Format (PDF)` select `Save File`
In InvoiceNinja go to `Invoices` and on any invoice click on `View PDF`.
This will result in preview PDFs being downloaded instead of being displayed.

**Expected behavior**
PDFs should still be displayed inline, regardless of content type set in browser. Only by clicking Download should the PDF actually be downloaded.

**Screenshots**
Clicking `View PDF` on any invoice results in the following:
![Screenshot from 2022-10-15 23-08-32](https://user-images.githubusercontent.com/22265595/196007652-bbb4d9d5-e578-4fd4-be80-bcac15d4e016.png)

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**
Yes

**Comment by hillelcoren** [comment]
You can correct this by enabling the alternate PDF viewer option on Settings > Account Management.

**Comment by Morpheus0x** [comment]
I do not see an option for alternate PDF viewer:
![Screenshot from 2022-10-18 13-00-49](https://user-images.githubusercontent.com/22265595/196412258-53718323-0e22-459e-a371-9db373b2840b.png)

In `Device Settings` there is the option `Use Browser PDF Viewer`, but deactivating this option doesn't change how the PDF is embedded and still results in the PDF being downloaded.
![Screenshot from 2022-10-18 12-57-11](https://user-images.githubusercontent.com/22265595/196411945-bef4f37b-8045-467c-84b3-5a104a8d7bdc.png)

**Comment by hillelcoren** [comment]
Try deselecting 'Use browser PDF viewer' on Settings > Device Settings

**Comment by Morpheus0x** [comment]
Yes, I already did that, but as I said, this doesn't resolve my issue. InvoiceNinja still uses the built-in preview and if Firefox is set to download PDFs instead of opening them in browser, the preview doesn't show up, and instead the download dialog appears.

The underlying problem I am having is most likely a Firefox bug. I set Firefox to always download PDFs because normally downloading a PDF would also show the PDF preview. This issue appeared in Firefox Version 98.0.

This issue can stay closed, however I am unsure if the `Use Browser PDF Viewer` actually does anything in Firefox...

**Comment by hillelcoren** [comment]
I think I understand the issue, the option affects the PDF preview at the bottom of the edit invoice screen but doesn't affect the view PDF screen.

**Comment by Morpheus0x** [comment]
> I think I understand the issue, the option affects the PDF preview at the bottom of the edit invoice screen but doesn't affect the view PDF screen.

Yes that's it. I was just trying the View PDF option. Editing a PDF will show a different PDF preview, which works regardless of browser settings. 

The View PDF page should also use the non-browser preview if that option is deselected.
