### ISSUE TITLE
Print Multiple Invoices at Once

### ISSUE THREAD

**Issue by tsi-dev-github** [invoiceninja/admin-portal#508]
**What version of Invoice Ninja are you running? ie v4.5 / v5**
v5

**What environment are you running?**
Hosted

**Have you searched existing issues/requests?**
Yes

**Screenshots**
![image](https://user-images.githubusercontent.com/40413876/198708068-39d90f27-9a1e-4a14-81cb-685e99eaa6fc.png)

**Additional context**
Would like to print selected invoices with 1 click instead of printing each one individually.

**Comment by hillelcoren** [comment]
@turbo124 I think we'd need to add support for this in the API, the route would combine multiple invoices into one PDF with page breaks inserted between each one.

**Comment by turbo124** [comment]
@hillelcoren 

sounds good,

i've got this loaded up

https://github.com/turbo124/invoiceninja/commit/9d09424e5eaef307ad663431018e9d1006de7470

We've just need a route to define the id of the entities and i'd return the pdf object.

**Comment by hillelcoren** [comment]
Awesome, can we use a bulk action? 

Also, I assume this may take a while if it's a few invoices. Should we do this async and email the PDF?

**Comment by turbo124** [comment]
@hillelcoren yes, we can push this as a bulk action.

Given the expectation the print dialogue is displayed, I'm not sure the friction of having the pdf emailed would be ideal?

**Comment by hillelcoren** [comment]
Good point, sounds good!
