### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by licaon-kter** [invoiceninja/admin-portal#509]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/3316607093#L846

**Comment by hillelcoren** [comment]
We've checked in a fix for this issue

**Comment by hillelcoren** [comment]
@licaon-kter can you help us understand why the app is labeled as "Non-Free Network Services"?

https://f-droid.org/en/packages/com.invoiceninja.app/

**Comment by licaon-kter** [comment]
Is the user free to change the instance?

If so, is the instance software free or open source?

**Comment by hillelcoren** [comment]
Yes. When you login to the app you can choose between logging into a hosted or selfhosted instance. You can also use the JSON import/export to transfer data/settings between hosted/selfhosted instances.

The backend software is free but released under the Elastic License so isn't considered 'open source'

https://github.com/invoiceninja/invoiceninja/blob/v5-stable/LICENSE

**Comment by licaon-kter** [comment]
Ok, then the antifeature stays I guess.

**Comment by hillelcoren** [comment]
The docs say the services needs to be free, not open source?

> This antifeature would not apply, if there is a simple configuration option that allows pointing the app to a running instance of an alternative, publicly available, self-hostable, free software server solution.

https://f-droid.org/en/docs/Anti-Features/#NonFreeNet

**Comment by hillelcoren** [comment]
I'm not trying to be funny or argumentative, just trying to understand. Our software is free to use but I understand the word 'free' has many meanings.

**Comment by licaon-kter** [comment]
You've been around for too long, you've surely read these licenses far too many times, and maybe lawyers were involved too at some point, hence my joke-y attitude to the selective reading of the text.
