### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by xeruf** [invoiceninja/admin-portal#510]
The readme is missing instructions how to package the app for the different systems for production use.

**Comment by hillelcoren** [comment]
How are you using the app? We generally don't expect people to build the app from the code for production use.

**Comment by xeruf** [comment]
I am on Arch Linux, where building from source is the standard way of using software.
I do not use snapcraft.

**Comment by hillelcoren** [comment]
You can use `flutter build linux` to create a release build for Linux

**Comment by xeruf** [comment]
Worked, thank you, would just like to resolve https://github.com/flutter/flutter/issues/115752 as well

**Comment by xeruf** [comment]
Can you look into the make parameter aspect of the issue, please? :)
