### ISSUE TITLE
Improve Task and Kanban handling

### ISSUE THREAD

**Issue by xeruf** [invoiceninja/admin-portal#514]
Some suggestions from an interested user :)

Allow reordering columns: https://notes.jorre.dev/notes/20200929113755-backwards_kanban.html
I currently only see the option to create, archive and delete, which would make reordering a pain.

Allow filtering by user without going through extra hoops (selecting user and selecting tasks again, not quite intuitive) - maybe filtering tasks by the current user by default?

**Comment by hillelcoren** [comment]
The columns can be reordered in the Kanban by dragging on them, you need to click and hold for a second.

**Comment by xeruf** [comment]
Ah, I tried to do it in the settings, where holding for a second only shows the checkboxes
