### ISSUE TITLE
Improve Assignee handling

### ISSUE THREAD

**Issue by xeruf** [invoiceninja/admin-portal#516]
![image](https://user-images.githubusercontent.com/13354331/204667380-793c5e4a-94d9-4f5f-9896-9e7f4412d02d.png)

I think it should not say "User" there, but rather something like "Assignee", to make it clear what this means.
And the Assignee of a Task should default to the Assignee of the project should default to the Assignee of the customer.

**Comment by hillelcoren** [comment]
Thanks for the feedback! I'm not sure about these suggestions.

In the screenshot above we're asking for the client, project and user to be assigned. I'm not sure changing 'User' to 'Assignee' makes this clearer.

Although for your use case the task/project/client user may all be the same I'm not sure we can assume that's the case for everyone.

**Comment by xeruf** [comment]
It is not about forcing something, but about reasonable defaults ;)
