### ISSUE TITLE
Translation Issues

### ISSUE THREAD

**Issue by xeruf** [invoiceninja/admin-portal#517]
![image](https://user-images.githubusercontent.com/13354331/204667847-f5a8020d-48eb-448e-9239-d04adc7d6698.png)

This is correct in the translation files, but somehow the first letter is incorrectly lowercased here when creating a new project.
We are running the latest version.

**Comment by hillelcoren** [comment]
Translations are managed in Transifex, the problem is most likely there.

https://transifex.com/invoice-ninja/invoice-ninja/

**Comment by xeruf** [comment]
oh it was indeed, fixed it
