### ISSUE TITLE
Translation variable not working

### ISSUE THREAD

**Issue by xeruf** [invoiceninja/admin-portal#518]
https://www.transifex.com/invoice-ninja/invoice-ninja/translate/#de/textsphp/84707554

After deleting a few invoices I got a popup literally saying `:count Rechnungen erfolgreich gelöscht`, with the variable not substituted.

Using latest 5.5.42

**Comment by paulwer** [comment]
This is also the case, when adding a task to an non-existing invoice.
![Unbenannt](https://user-images.githubusercontent.com/52678724/205851241-fa1a353b-9b74-40f6-9c79-c24f42ed4918.png)
