### ISSUE TITLE
Bigger / other display options for Transaction-Descriptions

### ISSUE THREAD

**Issue by paulwer** [invoiceninja/admin-portal#522]
Hey everyone,
I am sync Data from my bank account into the transaction section of invoiceninja. I am using the description field for saving the transaction related data. These are 3 lines for each transaction, which had some display issues when using it in this way.
 
![Unbenannt](https://user-images.githubusercontent.com/52678724/205848723-5aca284f-50c7-47c7-9f27-0f2093588fde.png)
It may be a better option to display Date and Amount in the header and the description below.
What do you think?

Extra-Note: At multiple places a date is represented with 2 dots after the month.

**Comment by hillelcoren** [comment]
Thanks for the feedback!

I'm not able to reproduce the date issue. Assuming the format is correct in the database I suggest creating a separate issue for it.
