### ISSUE TITLE
Better display files for a client

### ISSUE THREAD

**Issue by paulwer** [invoiceninja/admin-portal#523]
Hey everyone,
I am using the feature to save files for my customers. The administration in the admin-portal, because of the display in blocks and not as a list is sometimes hard, to keep track of all files. Is there an oportunity to display it as a list or to move this section down, to have more space to view?

**Comment by hillelcoren** [comment]
Thanks for the suggestion.

FYI.. one way to more easily view a client's documents is to click the client name at the top of the screen, you can then use the documents tab which is the full height of the app.

**Comment by paulwer** [comment]
Thank you very much. That helps in the first place. ❤️
I guess it would be sufficient enougth to display the files as a list or to have the option to swap the display types.
