### ISSUE TITLE
Missing text for Klarna

### ISSUE THREAD

**Issue by LarsK1** [invoiceninja/admin-portal#524]
Hi,
could you please add the string to display Klarna in the Admin UI?

**Comment by hillelcoren** [comment]
Sure, happy to. Can you please post a screenshot so I understand where it needs to be added.

**Comment by LarsK1** [comment]
![Screenshot_20221210-204322~2.png](https://user-images.githubusercontent.com/28981528/206872689-6eff4ccc-ae31-4711-848c-72c3d638c30b.png)
