### ISSUE TITLE
Date formating issue

### ISSUE THREAD

**Issue by paulwer** [invoiceninja/admin-portal#527]
![Unbenannt](https://user-images.githubusercontent.com/52678724/205848723-5aca284f-50c7-47c7-9f27-0f2093588fde.png)

As requested in #522 I've created a separate issue for this. I Guess this is caused by the frontend and not saved in a wrong way in the database.
I am using german locals.

**Comment by hillelcoren** [comment]
I haven't been able to reproduce this, can you please check the date_formats table to check if the format is correct there?

**Comment by paulwer** [comment]
when changing local to english (instead of german), this issue does not apear.

**Comment by hillelcoren** [comment]
Thanks, that's helpful to know!
