### ISSUE TITLE
Untranslated strings in German in Payment Settings

### ISSUE THREAD

**Issue by xeruf** [invoiceninja/admin-portal#529]
![image](https://user-images.githubusercontent.com/13354331/207603426-047af014-9983-4072-aed6-681662d8d3b2.png)

These aren't listed in Transifex either, maybe missing internationalization altogether?

**Comment by hillelcoren** [comment]
All translations are managed in Transifxex. 

These are new strings, there may be a delay.

**Comment by xeruf** [comment]
Ah, just adjusted them here: https://www.transifex.com/invoice-ninja/invoice-ninja/translate/#de/textsphp/444623895?q=text%3A'send+an+email+when'
