### ISSUE TITLE
Allow reordering 'running' task state

### ISSUE THREAD

**Issue by xeruf** [invoiceninja/admin-portal#531]
Due to the way we arrange our kanban (https://github.com/invoiceninja/admin-portal/issues/514), the running task state ends up behind the 'Done' tasks, which is suboptimal. I would like to be able to reorder it as well.

**Comment by hillelcoren** [comment]
I'm not sure I understand, are you able to post a screenshot?

**Comment by xeruf** [comment]
I would like 'running' to appear at the beginning of the list:
<img width="185" alt="image" src="https://user-images.githubusercontent.com/13354331/208312961-d0bbef38-fa10-47b8-8584-2ac2e10af5e8.png">

This is our task state configuration: 
<img width="483" alt="image" src="https://user-images.githubusercontent.com/13354331/208312974-cff48cd0-26bc-4e54-b5e3-a6c9fba2105d.png">

**Comment by xeruf** [comment]
Actually, I would like to have 'Running' as a Kanban bucket - thus that moving tasks in and out of it would start/stop timetracking.

**Comment by hillelcoren** [comment]
You can correct this by reversing the order of your task statuses, the columns can be dragged to reorder in the Kanban. The app expects the first status to be at the top and the last one (in your case 'Done') at the bottom.

Having a 'Running' column is an interesting idea however if you click the start/stop option in the Kanban card it would cause the task to move columns, I believe this could introduce UX issues.
