### ISSUE TITLE
Restoring Invoice fails despite success popup

### ISSUE THREAD

**Issue by xeruf** [invoiceninja/admin-portal#532]
I tried multiple times, every time it pops up with success but nothing changes.
Reloading Data or logging back in changed nothing either:
<img width="1719" alt="image" src="https://user-images.githubusercontent.com/13354331/208461158-e121adbd-acee-4712-b1bb-b89d317a115d.png">

Using latest 5.5

Kind of the opposite of https://github.com/invoiceninja/admin-portal/issues/519

**Comment by hillelcoren** [comment]
I'm not sure, I haven't been able to reproduce this.

If you can send the request/response data from the browser console it may help us track down the problem.
