### ISSUE TITLE
Time tracking across day boundary miscalculates

### ISSUE THREAD

**Issue by xeruf** [invoiceninja/admin-portal#533]
<img width="699" alt="image" src="https://user-images.githubusercontent.com/13354331/208656646-5e685580-a803-4f6a-bdfa-fda79b700c46.png">

It defaults to negative hours - but it works if one corrects the duration.
If end<start then it should assume a move across to the next day.

**Comment by hillelcoren** [comment]
Note: you can configure the app to support setting the end date on Settings > Task Settings

**Comment by xeruf** [comment]
I guess that would work too, but I don't think it should be necessary, putting an overflowing time onto the next day is something the software can easily assume for me ;)
