### ISSUE TITLE
add task based items to invoices using the mobile app

### ISSUE THREAD

**Issue by bradleydiggs** [invoiceninja/admin-portal#541]
Currently, with v5, you can use the "show tasks table" setting to add service based "task" items to invoices without having to first create a task from the task menu, and then apply that to an invoice.

This feature has not made it to the mobile app yet, meaning that you can add new items with the "plus" button in **_Invoice>Edit>Items_** on the fly to a new or existing invoice (without first creating a product or a task from their respective menus), however, these new invoice items will always be entered as "products" when using the mobile app, as there is currently no way to enter them as "task" based items (the exception would be going the long way around, creating a task first and then pulling it into the invoice, which is really only good for recurring tasks).

So - this request is for a way to add a service based "task" item to an invoice without having to create a task for it in advance, just like you can with the desktop and web app versions using the "show tasks table" setting.

From [this forum post.](https://forum.invoiceninja.com/t/add-task-based-item-to-invoice-using-mobile-app/12395)

**Comment by hillelcoren** [comment]
In the next release the app will use the selected tab to determine which type of line item to add. If you switch to the tasks tab the new line item will be set as a task.
