### ISSUE TITLE
New Payment missing Amount field.

### ISSUE THREAD

**Issue by mskenderian** [invoiceninja/admin-portal#543]
On iOS version, when creating a new payment, we are able to enter an Amount. 

On web version we dont have the field Amount, sometimes clients overpay or pay before invoice has been generated.

**Comment by hillelcoren** [comment]
You should be able to correct this by enabling the "apply payments later" option on Settings > Payment Settings in the web app. 

Note: it sounds like you may be using an older version of the iOS app.

**Comment by mskenderian** [comment]
Yes that fixed it. Thank you.

I am using latest that is available in the app store (v5.0.105)
