### ISSUE TITLE
Missing invoices in some areas of admin portal

### ISSUE THREAD

**Issue by brackenhill-mob** [invoiceninja/admin-portal#544]
I've got a weird error in v5.5.55.

Recent recurring invoices for one client are no longer appearing in the Invoices screen (the one that appears when you click on Invoices in the left had pane). However they are visible if I open the client screen where they are all marked as sent (and our accounts dept has received a copy of the email and the notification from IN). They also show up in the Dashboard overview (Upcoming Invoices) correctly too.

They are also shown in the activity log.

I created these recurring invoices in v5.5.53.

Is there a SQL command I can run to repair/fix the database?

**Comment by hillelcoren** [comment]
I think it's more likely the problem is with the frontend than the database.

**Comment by brackenhill-mob** [comment]
I think you are right. If I search for the missing invoices using a wildcard (ie "DC*") from the Invoices pane, they appear.

**Comment by brackenhill-mob** [comment]
And I might have an idea what triggered this. We originally had this recurring invoice with the R prefix which we then dropped. All the "missing" invoices are the ones generated since we dropped the R prefix.

**Comment by hillelcoren** [comment]
Is it possible they aren't missing but are simply not showing in the list where you expect based on the table sorting?

**Comment by brackenhill-mob** [comment]
You Genius. I hadn't realised that that pane was indexed by invoice number - I'd assumed that it was by date. With the original, default invoice numbering system that we used, the invoice number correlated with the date. But now each client has its own 2 letter designator followed by the latest invoice number for that client, that correlation is broken.
