### ISSUE TITLE
Client info deleted when logo uploaded

### ISSUE THREAD

**Issue by Slopz** [invoiceninja/admin-portal#546]
## Setup
- Version: v5.5.57-W105
- Environment: Docker

## Checklist
- Can you replicate the issue on our v5 demo site https://demo.invoiceninja.com pr https://react.invoicing.co/demo?
- **Yes**
- Have you searched existing issues?
- **Yes**
- Have you reported this to Slack/forum before posting?
- **No**

## Describe the bug

Client info such as name and email get cleared when a logo is uploaded under client settings.

[video replicating the issue over at https://demo.invoiceninja.com](http://link.nbbn.cloud/auPnO)

### Steps To Reproduce

1. Create client
2. Fill in client info
3. Open client settings
4. Upload logo/picture under "Company Details"
5. Client info such as name and email is gone

### Expected Behavior
Nothing should happen to client info once a picture/logo is uploaded under Company Details > Logo

**Comment by hillelcoren** [comment]
@turbo124 I think this may be a backend issue. When the frontend saves the logo it sends a PUT request to the client route with the logo but no data. If the contacts property isn't specified in the request I don't think it should be affected.

**Comment by turbo124** [comment]
@hillelcoren thanks, i've patched this one now.

The issue i could reproduce here was if the user is filling in company details in the settings tab, and also tries to upload the logo, the company details section is wiped also.

**Comment by hillelcoren** [comment]
@turbo124 I've added a warning to prevent this
