### ISSUE TITLE
Show Email Footer switch not working

### ISSUE THREAD

**Issue by charlygott** [invoiceninja/admin-portal#548]
## Setup
- Version: 5.5.62
- Environment: Docker

## Checklist

- [x] Can you replicate the issue on our v5 demo site https://demo.invoiceninja.com pr https://react.invoicing.co/demo?
- [ ] Have you searched existing issues?
- [ ] Have you reported this to Slack/forum before posting?

## Describe the bug
"Show Email Footer" switch is not working

### Steps To Reproduce
- Go to Settings > Email Settings
- Try to toggle the "Show Email Footer" switch

### Expected Behavior
The switch should toggle on or off

**Comment by hillelcoren** [comment]
Thanks for reporting this!
