### ISSUE TITLE
Mac app just keeps spinning

### ISSUE THREAD

**Issue by waynepaulward** [invoiceninja/admin-portal#549]
Mac app just keeps spinning
where can I clear down the app 
I tried removing and reinstall 
where is app settings 

wayne

**Comment by hillelcoren** [comment]
Sorry for the trouble, it may help to reinstall the app

**Comment by waynepaulward** [comment]
I removed and reinstalled Its just the sameIt seems it must leave files behind im thinking Im just asking where the directory it created to hold the config so i can delete this Wayne Sent from my iPhoneOn 27 Jan 2023, at 07:00, Hillel Coren ***@***.***> wrote:﻿
Sorry for the trouble, it may help to reinstall the app

**Comment by hillelcoren** [comment]
I'm not sure where the folder is on macOS.

If you see the about button in the bottom left corner you can click about and then long press the version to see an option to logout.

**Comment by waynepaulward** [comment]
If i could only get that far!When i open its just a spinning ball and it just sits spinning so cant click no buttons Wayne Sent from my iPhoneOn 27 Jan 2023, at 10:56, Hillel Coren ***@***.***> wrote:﻿
I'm not sure where the folder is on macOS.
If you see the about button in the bottom left corner you can click about and then long press the version to see an option to logout.

**Comment by hillelcoren** [comment]
I found the app data, I believe it's located at:

`~/Library/Containers/com.invoiceninja.app/Data/Documents/`

**Comment by waynepaulward** [comment]
Yes that got me in but there is more it still see the old url i put in where can i clear that Sent from my iPhoneOn 27 Jan 2023, at 11:19, Hillel Coren ***@***.***> wrote:﻿
I found the app data, I believe it's located at:
~/Library/Containers/com.invoiceninja.app/Data/Documents/

**Comment by waynepaulward** [comment]
I removed the files in that directory which then let me open the app again and i can get inside and see buttons but the url is still fixed in a config file - so one more file somewhere…Wayne Sent from my iPhoneOn 27 Jan 2023, at 11:43, Wayne Ward ***@***.***> wrote:﻿Yes that got me in but there is more it still see the old url i put in where can i clear that Sent from my iPhoneOn 27 Jan 2023, at 11:19, Hillel Coren ***@***.***> wrote:﻿
I found the app data, I believe it's located at:
~/Library/Containers/com.invoiceninja.app/Data/Documents/

**Comment by waynepaulward** [comment]
Fixed it! I removed the files in the directory you said then removed app and reinstalled!! Fixed thank you 🙏 Wayne Sent from my iPhoneOn 27 Jan 2023, at 11:43, Wayne Ward ***@***.***> wrote:﻿Yes that got me in but there is more it still see the old url i put in where can i clear that Sent from my iPhoneOn 27 Jan 2023, at 11:19, Hillel Coren ***@***.***> wrote:﻿
I found the app data, I believe it's located at:
~/Library/Containers/com.invoiceninja.app/Data/Documents/
