### ISSUE TITLE
Feature Request - Set client password for portal manually

### ISSUE THREAD

**Issue by mrkylegp** [invoiceninja/admin-portal#550]
In v4 it was possible to set the client password for the portal manually.

I understand the client sets their own password when they first visit the portal but it would be nice to be able to change their password manually via the admin portal.

I have a client who currently can't access their email temporarily so I would like to set a password for them so they can log into the client portal to retrieve their invoice. However they have never created a password and since they don't have access to their email address temporarily, they seemingly can't set a password or log in.

**Comment by hillelcoren** [comment]
@turbo124 does the backend support this?
