### ISSUE TITLE
Tax Report calculating incorrectly when discount is applied

### ISSUE THREAD

**Issue by lukeh182** [invoiceninja/admin-portal#554]
## Setup
- Version:  v.5.5.70
- Environment:  ZIP

## Checklist
- Can you replicate the issue on our v5 demo site https://demo.invoiceninja.com or https://react.invoicing.co/demo? YES
- Have you searched existing issues? YES
- Have you reported this to Slack/forum before posting? NO
- Have you inspected the logs in storage/logs/laravel.log for any errors? YES

## Describe the bug
 When a discount is applied to an invoice, the “Invoice Tax” or “Payment Tax” report displays an incorrect tax amount. Opening the invoice displays the correct tax amount. When pulling a tax report it displays the tax amount with the discount also applied to the tax. Example: Invoice > Item $100, Discount 10%, Subtotal $90, Tax Rate 10% $9, Total $99 (all is correct) Report > Invoice Tax > Invoice Amount $99 > Tax Amount $8.10 (incorrect)

### Steps To Reproduce
 Simply create an invoice with a discount applied and add sales tax, then run a tax report.

### Expected Behavior
 Sales tax of invoices should match the sales tax of the reports.

## Additional context
 I’ve noticed tax discrepancies in the past (previous versions) and never investigated the issue. I updated to most recent prior to posting this just to be sure it wasn’t corrected.

### Logs
 Logs are all related to sending auto bill. 
![3BA49F5C-3131-4B41-BE27-91837A70F708](https://user-images.githubusercontent.com/52144967/218124977-442356dc-2ea9-410f-af48-c92439c11f3d.jpeg)
![7B60E374-9CB0-4A26-9F37-DF04929AC965](https://user-images.githubusercontent.com/52144967/218124998-0062b737-0d43-4bf5-8332-a4225dc28b50.jpeg)

**Comment by hillelcoren** [comment]
Thanks for reporting this! We've checked in a fix.
