### ISSUE TITLE
Larger Description box

### ISSUE THREAD

**Issue by fmattheu** [invoiceninja/admin-portal#555]
A taller description box would work for me.  I’d appreciate a wider description box too. Maybe the “time-tracker” box doesn’t need to be full-width.  At least not for me. 

I’ve included a sample of a past task below to show how much text I put in a description box.  I always need to scroll up and down to see if I’ve captured all of my work performed.

Thank you for your consideration!

**Sample Text that I pit in Description Box**

Client Name

Phone consult to clarify tasks needed

Created three new services, according to instructions:
bridal, evening gown, and standard alteration
appointments with distinct prices and times available.

Found images for evening gowns and standard
appointment displays.

Created a page named Appointments with three
appointment type options.

Disabled old Summer 2022 classes popup.

Troubleshooting appointment confirmation process.

Canceled appointment. 

Communication will Jamie to
discuss future client meetings.

**Comment by fmattheu** [comment]
I don't see it? My web-based version is not wider nor expanding?

**Comment by hillelcoren** [comment]
If you're using the latest version of the app there's a new "Show task item description" option on Settings > Task Settings
