### ISSUE TITLE
Missing webhooks

### ISSUE THREAD

**Issue by LarsK1** [invoiceninja/admin-portal#556]
Hi,
the new webhooks are missing. Could you please add them here and in Zapier as well?

Lars

**Comment by hillelcoren** [comment]
We'll add all events in the admin portal. 

Which specific events do you plan to use in Zapier?

**Comment by LarsK1** [comment]
I personally would love to see the sent events as they would fully automate my accounting. But the rest seems important as well...

**Comment by hillelcoren** [comment]
We deployed a new version of Zapier today, the new events will be included with the next release.
