### ISSUE TITLE
Reports -> Expense | Number Column missing

### ISSUE THREAD

**Issue by shrippen** [invoiceninja/admin-portal#557]
## Setup
- Version: 5.5.70
- Environment: Docker

## Checklist
- Can you replicate the issue on our v5 demo site https://demo.invoiceninja.com or https://react.invoicing.co/demo? Yes
- Have you searched existing issues? Yes
- Have you reported this to Slack/forum before posting? No
- Have you inspected the logs in storage/logs/laravel.log for any errors? No

## Describe the bug
On the Reports Page when using the Expense Report there is no Number Column to select from. This seems like an oversight.

### Steps To Reproduce
Open reports page, select expense report. Click on Columns upper right corner. Try to find number column.

### Expected Behavior
A number column like in the invoice report on the reports page.

**Comment by hillelcoren** [comment]
Thanks for reporting this, we'll make sure it's corrected.
