### ISSUE TITLE
Bug: Invoice Lines are not visible after removing task entries

### ISSUE THREAD

**Issue by paulwer** [invoiceninja/admin-portal#558]
How to reproduce:
if both normale invoice_lines and the task-imported lines are present, both gets displayed within the invoice (as exspected)
BUF, when I remove the last existing enntry of the time-imported lines the select of which line i would like to edit is hidded and i cannot change back to the normal invoice_lines. even, when they are still available, after a page-refresh.

**Comment by hillelcoren** [comment]
Thanks for reporting this, we'll make sure it's corrected.

Note: I think you can workaround the issue by enabling the "Show Tasks Table" option on Settings > Task Settings.

**Comment by paulwer** [comment]
Thank you, this can be closed afterwards.
