### ISSUE TITLE
Currency conversion on dashboard completed payments is incorrect.

### ISSUE THREAD

**Issue by sandro-sikic** [invoiceninja/admin-portal#562]
## Setup
- Version: v5.5.102-C113
- Environment: Docker

## Checklist
- ✅ Can you replicate the issue on our v5 demo site https://demo.invoiceninja.com or https://react.invoicing.co/demo? 
- ✅ Have you searched existing issues? 
- ❌ Have you reported this to Slack/forum before posting? 
- ❌ Have you inspected the logs in storage/logs/laravel.log for any errors?

## Requirements
- Company with non default currency
- Invoice with that company with value in settings -> exchage rate != 1.00
- Payment for that invoice

## Describe the bug
Dashboard page, Completed payments show wrong values when filter is set to all currencies. This also affects graphs with payments information.

### Steps To Reproduce
- Create a company with non default currency
- Create a invoice and set a value in exchange rate to 0.0001
- Create a payment for said invoice
- Go to dashboard and check values of Completed payments

### Expected Behavior
- It's expected to convert the payment value to the set exchange rate in the invoice.

**Comment by sandro-sikic** [comment]
Hi, 

Payment exchange rate does not affect dashboard statistics.
Active invoices and Outstanding invoices are calculated correctly.

Let me know if you need more information, glad to help.

**Comment by hillelcoren** [comment]
I'm having trouble reproducing this., if an exchange rate is set on the payment it correctly adjusts the amount shown on the dashboard.

**Comment by sandro-sikic** [comment]
Here are some screenshoots where you can see the issue.

The exchange rate is approx 7.5:1

In the screenshoot with the total sum of all currencies it should be approx **~35.210,00€** instead of **166.099,70€**
![Screenshot 2023-05-31 211816](https://github.com/invoiceninja/admin-portal/assets/38315243/86cbc46b-eab3-4774-a731-972de93a8d91)
It seems like it **sums the total values without conversion.**

Here are the the seperate currencies.
![Screenshot 2023-05-31 211845](https://github.com/invoiceninja/admin-portal/assets/38315243/00089fc1-929d-430a-9fe6-f950d53bd7c4)

![Screenshot 2023-05-31 211912](https://github.com/invoiceninja/admin-portal/assets/38315243/433fda37-b8e3-4428-bdc3-ec23e4f44980)

It is also affecting graphs.
![image](https://github.com/invoiceninja/admin-portal/assets/38315243/5f825cf4-e38b-492d-a9dc-58b4c0e5349f)


To reproduce you would need 2 invoices in different currencies with their exchange rates set.

**Comment by hillelcoren** [comment]
Can you confirm that you've set the payment exchange rate. Invoices have their own exchange rate field which don't affect the payments.

**Comment by hillelcoren** [comment]
I think I see the issue. Both invoices and payments can have their exchange rate set. Currently if the exchange is unset the app uses the current rate. If you view the payment dashboard where the invoices have an exchange rate but the payment do not the app will use the current rate. We can change it to use the invoice rate (if set) which I believe will solve your problem.
