### ISSUE TITLE
[Feature Request] Additional report for "Task Item"

### ISSUE THREAD

**Issue by danielkoch** [invoiceninja/admin-portal#565]
It would be useful to get more granulated report possibilities if it come to reporting on task-level.

Use case: I have a task with time entries and I’m using this to record times for several month. Now I want to create a report f.e. on quarter year basis. Currently the reports are not “dividable” by the time entries.

I created simple example data. My wish is to get only one time entry (January):
*Tasks*
![Tasks](https://user-images.githubusercontent.com/142055/232453823-5a990ce5-71dc-423e-bcd1-fd71e941cd30.png)

*Report*
![Tasks](https://user-images.githubusercontent.com/142055/232453881-618ab257-62d7-4260-9a52-767d220584b2.png)

According to @hillelcoren a new report item for "Task items" is needed to solve this.

**Comment by danielkoch** [comment]
@hillelcoren: Very nice! Is there any release date for the desktop app planned?

**Comment by hillelcoren** [comment]
The Linux desktop app was just released, the Windows and macOS apps will be updated in the next few weeks.
