### ISSUE TITLE
Android App  On VS Code

### ISSUE THREAD

**Issue by NirajKothari132** [invoiceninja/admin-portal#566]
I am trying to Build android apk  there it showing me the Error

**Comment by hillelcoren** [comment]
What error are you seeing?

**Comment by NirajKothari132** [comment]
android Method is not found

**Comment by hillelcoren** [comment]
I'm not sure, I haven't seen that error.

Out of curiosity, why are you building the app?

**Comment by hillelcoren** [comment]
Why are you building the app rather than use the app from the store, are you planning on reselling it?

**Comment by NirajKothari132** [comment]
No i am not planning on reselling , we want to use on local server so on our pc it is giving issue

**Comment by hillelcoren** [comment]
Sorry, I don't have an answer. This may help if you're able to build the app.

https://stackoverflow.com/a/65730723/497368

**Comment by NirajKothari132** [comment]
we just want to test

**Comment by NirajKothari132** [comment]
we just want to test
