### ISSUE TITLE
Implementation of micro-optimizations

### ISSUE THREAD

**Issue by isabelaortiz** [invoiceninja/admin-portal#571]
There are some micro-optimizations you could apply in the code that will make the app perform in a better way and have less memory consuption. For example there are several iterator-based loops that could be replaced by index-based loops. This way, you are not creating a new object in each iteration, which reduces memory consuption. 
Also, you should not create objects inside the loops. This is not a good practice because every time the loop iterates again, a new object is created and therefore a lot of memory is being used unnecessarily.

**Comment by hillelcoren** [comment]
I'm reluctant to spend time implementing these sorts of changes. My belief is the performance gains are so negligible that they aren't worth the effort (especially considering our time could instead be spent adding features). That said, I'd be happy to be proven wrong if you can show there is a measurable benefit using benchmarks.
