### ISSUE TITLE
Implementation of Flutter_Cache_Manager

### ISSUE THREAD

**Issue by isabelaortiz** [invoiceninja/admin-portal#572]
I believe you could benefit from implementing the flutter_cache_manager. One case where you could use this is for the management and download of pdf files for the invoices. For example, you could cache this file to prevent the app from downloading this multiple times. This would require a large amount of cache storage because these files could be very large, but this helps the user experience when trying to retrieve these files. You are currently generating this file every time it is needed, and it is not being saved. The implementation of this code just requires the instance of the cache manager, convert the pdf file to a MultipartFile object and put this file inside the cache using the putFile method.

**Comment by hillelcoren** [comment]
This comes down to tradeoffs. The PDFs are generated (and cached) by the server, the app is just downloading it. Once the PDF is generated I don't believe it's being repeatedly viewed by the user. If they do view it again it's usually when changing it which would make the cached version less useful.
