### ISSUE TITLE
Smooth Scrollable List in Credits View

### ISSUE THREAD

**Issue by na-rodriguezp** [invoiceninja/admin-portal#573]
By looking at the credit list, I realized that the hole list has to be drawed again everytime a scroll is done by the user. This was noted by activating the Highlight Repaints option from the Flutter Inspector tab in the IDE. 
To solve this you could implement a smooth scrollable list, so there is much less component drawing. This would help improving performance in some devices and make UX better.

**Comment by hillelcoren** [comment]
Similar to the other issues you've created, I'm not sure if this change is solving a real problem or a theoretical one. We have't heard any reports from users that the scrolling isn't smooth enough.
