### ISSUE TITLE
Bug on android app 

### ISSUE THREAD

**Issue by nakpilse** [invoiceninja/admin-portal#577]
After failed update of v5.5.104-W144 Self-hosted.

When logging in thru android app i get this error.

Error :: '[id, VolejRejNm, company_key, Co8hH19k8BS63nsvNZriLyajpHQUaQgg, update_produc...' to 'CompanyEntity' failed due to: Deserializing '' to 'TaxDataEntity' failed due to: type '_OneByteString' is not a subtype of type 'Iterable<Object?>' in type cast

Any idea what causes this error?

**Comment by hillelcoren** [comment]
Hi,

Updating the backend app to the latest version should fix the error.

Alternatively, you can comment out this line of code as a workaround:

https://github.com/invoiceninja/invoiceninja/blob/v5-stable/app/Transformers/CompanyTransformer.php#L197

**Comment by nakpilse** [comment]
Issue is now fixed, I just upated manually thru extracting latest version zip.

**Comment by hillelcoren** [comment]
Glad to hear it, thanks for the update!
