### ISSUE TITLE
Mac app not loading

### ISSUE THREAD

**Issue by NPCtom** [invoiceninja/admin-portal#579]
Hi there,
I am having issues with the Invoice Ninja desktop app. It doesn't seem to be working at all even after multiple reinstalls.

I have also deleted the Inovice Ninja files in the Application Support directory.

Do you have any troubleshooting tips I could try?

Thank you very much for the assistance.

OS: 14.0 Beta (23A5257q)

<img width="1490" alt="Screenshot 2023-06-12 at 2 06 29 AM" src="https://github.com/invoiceninja/admin-portal/assets/44740840/592b52b8-3175-4a7d-a6ef-a605fca5f945">

**Comment by hillelcoren** [comment]
Hi, 

Try deleting the contents of this folder and then launching the app.

`~/Library/Containers/com.invoiceninja.app/Data/Documents/`

**Comment by NPCtom** [comment]
Same result. There was a single file named `invoiceninja__ui_state.json`

**Comment by hillelcoren** [comment]
Maybe you also need to reinstall?

https://github.com/invoiceninja/admin-portal/issues/549#issuecomment-1406343349

**Comment by NPCtom** [comment]
Removed the app and reinstalled, still the same behaviour

**Comment by hillelcoren** [comment]
Are you able to get to the login screen?

**Comment by NPCtom** [comment]
No I'm unable to get to any screen. It's just the loading symbol and the about icon does not appear on the bottom left either.

**Comment by hillelcoren** [comment]
I'm not sure, these steps seemed to help for the other user.

We can look into making the logout option visible in this case in the next release.

**Comment by hillelcoren** [comment]
In the next release of the macOS app you'll be able to click the about icon in the lower left corner and then long-press the app version to access a logout option.

**Comment by NPCtom** [comment]
Thanks, the logout option worked.

Would you happen to know what this error means upon login:
```
Error :: '[id, VolejRejNm, user_id, VolejRejNm, assigned_user_id, , product_key, Spotif...' to 'ProductEntity' failed due to: Deserializing '1' to 'String' failed due to: type '_Smi' is not a subtype of type 'String' in type cast
```

**Comment by hillelcoren** [comment]
You should be able to fix this by either updating to the latest version of the backend app or commenting out this line:

https://github.com/invoiceninja/invoiceninja/blob/v5-stable/app/Transformers/CompanyTransformer.php#L197

**Comment by NPCtom** [comment]
Thanks, that's awesome.
