### ISSUE TITLE
Customize email html markup

### ISSUE THREAD

**Issue by jkurelek** [invoiceninja/admin-portal#58]
On both the iOS and Android apps, when customizing an email before sending, the body of the email contains html markup which makes it difficult to edit.

This is from Android app

![Screenshot_20190410-092540](https://user-images.githubusercontent.com/5564064/55887970-895a9c80-5b7c-11e9-8306-fa5a57f112b2.png)

**Comment by esarbanis** [comment]
There are some rich text editors that could be used or be inspired by in [this issue](https://github.com/flutter/flutter/issues/12675) in flutter.

**Comment by LiamKarlMitchell** [comment]
Similar with settings pages for custom header/footer privacy policy, terms, custom css custom js.
A better editor would be good there.

**Comment by hillelcoren** [comment]
FYI.. we plan to use this editor once it supports HTML

https://github.com/superlistapp/super_editor/tree/main/super_editor

**Comment by lonix1** [comment]
Maybe this should have that new upstream `flutter` tag?
BTW I upvoted as we discussed earlier. And I encourage others here to upvote the [relevant issue](https://github.com/superlistapp/super_editor/issues/1) so it gets more attention. Looks like a nice editor.
