### ISSUE TITLE
Unable to build with latest flutter

### ISSUE THREAD

**Issue by xeruf** [invoiceninja/admin-portal#584]
As is standard on Arch:
```sh
❯ flutter --version
Flutter 3.10.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 796c8ef792 (2 weeks ago) • 2023-06-13 15:51:02 -0700
Engine • revision 45f6e00911
Tools • Dart 3.0.5 • DevTools 2.23.1

❯ flutter build linux
Resolving dependencies... 
The lower bound of "sdk: '>=2.9.0 <3.0.0'" must be 2.12.0'
or higher to enable null safety.

The current Dart SDK (3.0.5) only supports null safety.

For details, see https://dart.dev/null-safety
```
I am really struggling to find a working version, as many older versions also complain...

**Comment by hillelcoren** [comment]
The app should build with 3.7.x. 3.10.x requires the code to implement null safety which hasn't been handled yet.

**Comment by xeruf** [comment]
Yep, realized that as well after hours of tinkering. Please mention that in the readme!

**Comment by hillelcoren** [comment]
Out of curiosity, why are you building the app from source?

**Comment by hillelcoren** [comment]
@xeruf how are you using the app? From past experience people building the app from source are often attempting to resell it, please confirm whether or not that's the case.
