### ISSUE TITLE
Feature request: Report of not invoiced hours per client or in total

### ISSUE THREAD

**Issue by andihuber** [invoiceninja/admin-portal#587]
It is difficult to have an overview of how many hours from tasks are not invoiced. If we could see somewhere how many hours in total are not invoiced and have a report also of open hours per client this would be very helpful. In whatever form (here an example).

![overview](https://github.com/invoiceninja/admin-portal/assets/16149664/39d51e9b-8bd1-4a29-9129-e6ec4f0ef07c)

**It would be great if i can get the following reports:**

- Hours from tasks which are not invoiced of chosen client
- Hours from tasks which are not invoiced in total (where i can see open hours per client)

A good place to display the sum of the time of already finished tasks or open tasks could be in tasks module. 

Because there these filter options already exist (filter bar, filter if active / archived, filter by status):

![b82d78b711ba162d424a14226e3bb0f0037d2804](https://github.com/invoiceninja/admin-portal/assets/16149664/3a06a4e8-8fe6-4fe7-929b-6ac8ab13daa1)

**Comment by andihuber** [comment]
Thank you for looking into this. I just try to find out how can i now achieve this filtered results (is it in Reports or Tasks module?). 

And what can i filter?

- Hours from tasks which are not invoiced of chosen client
- Hours from tasks which are not invoiced in total (where i can see open hours per client)


I tried to find out that reading your code, but i am not really a programmer. so i could not find it out :-). 

Thank you, BR Andreas

**Comment by hillelcoren** [comment]
A new task item report has been added in the latest release.

From the screenshot it looks like you're using the macOS app, it hasn't been updated yet.

**Comment by andihuber** [comment]
Ok, thank you for the hint. I tried in online-version. But also there i am not sure if i am filtering it correct. Also i have 2 entries here which for my understanding are the same, one in English, one in German. But they have different results. See here:

<img width="2229" alt="Bildschirmfoto 2023-11-06 um 17 37 13" src="https://github.com/invoiceninja/admin-portal/assets/16149664/aba36aee-f080-4cb9-9203-233753f43328">

Or is "Task" (="Aufgabe" in German) and "Task item" not the same?

**Comment by hillelcoren** [comment]
The task and task item reports are different.

If a task has two time segments it would appear as one row in the first report but two rows in the second report.

**Comment by andihuber** [comment]
Sorry @hillelcoren but i have to come back to this again.

Thanks for clarification of the difference of task and task item. That is now clear.

But i still can not filter the tasks / task items which are not invoiced. Then i use Task Item" and "Status" then i see all tasks, i can filter then by date. But not if the task was being invoiced or not. But that would be the important information for me as written initially. Or am I just being a bit stupid and can not find the correct fields? :-)

When i choose "Task Item" and "Invoice" then i again have no option to filter the not invoiced tasks.

<img width="899" alt="Bildschirmfoto 2023-11-16 um 11 18 06" src="https://github.com/invoiceninja/admin-portal/assets/16149664/6e9f42a8-92ea-4b71-a796-4f46214a6a1a">

**Comment by hillelcoren** [comment]
You can add the "Is invoiced" column to the report to filter by it
