### ISSUE TITLE
[Android] [Feature Request] Update to targetSdk 33

### ISSUE THREAD

**Issue by sebastien46** [invoiceninja/admin-portal#589]
Starting from August 31st 2023 onwards, the Google Play Store won't accept app updates for apps with targetSdk inferior to 33:

[https://support.google.com/googleplay/android-developer/answer/11926878](https://support.google.com/googleplay/android-developer/answer/11926878)

**Comment by hillelcoren** [comment]
Hi,

Why did you create this issue along with others like it?

https://github.com/yairm210/Unciv/issues/9840
https://github.com/billthefarmer/specie/issues/5

**Comment by sebastien46** [comment]
Because FOSS needs to reach as many people as possible, and these apps being phased out of the Play Store would hinder their visibility.

**Comment by sebastien46** [comment]
Fixed in [5.0.125](https://github.com/invoiceninja/admin-portal/releases/tag/v5.0.125).

**Comment by hillelcoren** [comment]
Thanks for identifying and closing the issue
