### ISSUE TITLE
translate & changelog info android app [ com.invoiceninja.app ]

### ISSUE THREAD

**Issue by jindam-vani** [invoiceninja/admin-portal#592]
* please provide translation instructions on README
* changelogs of android app, seperate [ i know existence of info in fastlane ]

**Comment by hillelcoren** [comment]
Hi,

Do you mean add a link to https://transifex.com?

The new features can been seen in the app itself by clicking 'New' at the top of the settings menu. 

How are you using the app? I just want to confirm you aren't attempting to resell it.

**Comment by hillelcoren** [comment]
That would violate the app's license: 

https://invoiceninja.github.io/en/legal/license
