### ISSUE TITLE
HandshakeException: Handshake error in client

### ISSUE THREAD

**Issue by nexitpl** [invoiceninja/admin-portal#593]
## Setup
- Version: 5.6.23
- Environment: Self Hosted (WhiteLabel)

When I Try to view Invoice PDF :

MacOS APP:

HandshakeException: Handshake error in client (OS Error: 
	WRONG_VERSION_NUMBER(tls_record.cc:242))

Browser:
XMLHttpRequest error.

Please help.

**Comment by hillelcoren** [comment]
- Are you able to access your account using the web app with HTTPS?
- Have you setup an SSL certificate?
