### ISSUE TITLE
Redirect to Client tab

### ISSUE THREAD

**Issue by ErminMerdanovic** [invoiceninja/admin-portal#594]
## Setup
- Version: v5.7.5-C123
- Environment: Shared Hosting (i am the owner of the shared host Machine)

## Checklist
- Can you replicate the issue on our v5 demo site https://demo.invoiceninja.com or https://react.invoicing.co/demo?
Yes
- Have you searched existing issues?
Yes
- Have you reported this to Slack/forum before posting?
No
- Have you inspected the logs in storage/logs/laravel.log for any errors?
Yes

## Describe the bug
I'm experiencing an issue where upon refreshing the page, I'm consistently redirected to the clients tab. I've tested this behavior on both Chrome and Edge browsers, and it even occurs on the demo page. 

### Steps To Reproduce
Open any tab other than the client tab, then refresh the page, and you will be redirected to the client tab.

### Expected Behavior
Normally, the expected behavior is to return to the last page or tab that was open before the refresh.

**Comment by opxdelwin** [comment]
Hi, I'm new to this project but looks this is an issue on flutter interface and not react interface (both web). From the address bar, it seems Navigator 2.0 hasn't been implemented... I'd be happy to help, @hillelcoren!

**Comment by hillelcoren** [comment]
I believe this issue should be resolved in the next release.

Thanks for the offer to help but we don't plan to change to Navigator 2.0.

**Comment by hillelcoren** [comment]
Note: enabling and then disabling the cache option on Settings > Device Settings should fix this problem.
