### ISSUE TITLE
ability to hide dashboard page from enterprise users

### ISSUE THREAD

**Issue by rbmfg** [invoiceninja/admin-portal#595]
**What version of Invoice Ninja are you running? ie v4.5 / v5**
v5**

**What environment are you running?**
Shared Hosting

**Have you searched existing issues/requests?**
yes

**Screenshots**
If applicable, add screenshots to help explain your request/question.

**Additional context**
We are a small shop with one invoice ninja user other than the admin and I would like to hide the overall company financials from this user while letting them have access to edit and view all invoices. I know they can tally totals themselves via the invoices, but I don't want the info splashed in their faces every time they log in. in V4 this was standard not to see the dashboard page.

**Comment by turbo124** [comment]
![image](https://github.com/invoiceninja/admin-portal/assets/5827962/7a498c92-3086-4ca8-9c16-0bc6da60e5d3)

I see the side bar disappears, but on login, the dashboard appears by default

**Comment by taidhong** [comment]
In my test, the dashboard icon is still in the sidebar. When do you think this can be merged?

**Comment by hillelcoren** [comment]
Can you confirm that you've disabled the dashboard option in the user's permissions?

We'll correct the dashboard being shown on login in the next update to the Flutter app.
