### ISSUE TITLE
Currency field for converting currencies in recurring expense is not connected to any database table and created expense has an empty currency field there

### ISSUE THREAD

**Issue by dleidert** [invoiceninja/admin-portal#596]
## Setup
- Version: v5.7.6
- Environment: Docker

## Checklist
- Can you replicate the issue on our v5 demo site https://demo.invoiceninja.com or https://react.invoicing.co/demo?
Yes

- Have you searched existing issues?
Yes

- Have you reported this to Slack/forum before posting?
No

- Have you inspected the logs in storage/logs/laravel.log for any errors?
Yes

## Describe the bug
When one creates a recurring expense and enables "Convert currency", then the currency field is not connected to a database table. If one deletes the content (defaults to "US Dollar") or starts typing, then no list pops up. Also, the created expense has an empty currency field in the "Convert currency" section.

### Steps To Reproduce
Create a recurring expense. Enable "Convert currency". Delete the value. The field is empty. Add back "US Dollar" and complete the data. Wait for invoiceninja creating an expense. Check the currency field in the "Convert currency" section. It is empty.

### Expected Behavior
a) The currency field should open a pop-up list with available currencies.
b) The created  expense should have the selected currency set in the "Convert currency" section.

## Additional context
n/a

### Screenshots
n/a (please let me know if you need any)

### Logs
Nothing relevant in the log.

**Comment by hillelcoren** [comment]
Thanks for the video! Can you pleas try clicking the 'X' to clear the value and then search for a new value.

**Comment by dleidert** [comment]
@hillelcoren Same result. I just checked with version 5.7.8. There is no difference in removing the value using the "x" or by marking and deleting it.

**Comment by hillelcoren** [comment]
Do other currency fields in the app work, ie. when editing a client?

**Comment by dleidert** [comment]
@hillelcoren Yes. I'm using the app for some time now. I haven't spotted any other currency fields that don't work.

**Comment by dleidert** [comment]
JFTR: <https://demo.invoiceninja.com/> shows the same (buggy) behavior. So, you should be able to reproduce that.

**Comment by hillelcoren** [comment]
Thanks for reporting this, it should be fix in the next update of the Flutter app
