### ISSUE TITLE
Remove references to "privacy shield"

### ISSUE THREAD

**Issue by licaon-kter** [invoiceninja/admin-portal#603]
invalid link: https://invoiceninja.com/privacy-shield/

seen here: https://play.google.com/store/apps/details?id=com.invoiceninja.app

re: https://en.wikipedia.org/wiki/EU%E2%80%93US_Privacy_Shield

**Comment by hillelcoren** [comment]
I can't find the link on the page, can you please post a screenshot showing where it is?

**Comment by licaon-kter** [comment]
Play, press "About this app ->", scroll down

**Comment by hillelcoren** [comment]
Got it, thanks!
