### ISSUE TITLE
Feature request - direct Copy Link

### ISSUE THREAD

**Issue by dali-dbr** [invoiceninja/admin-portal#605]
It would be nice to have a **copy link** of quote/invoices... directly from the main view

![image](https://github.com/invoiceninja/admin-portal/assets/6317229/5023e466-4c00-4396-852e-a04bc3166436)

![image](https://github.com/invoiceninja/admin-portal/assets/6317229/5243eac1-ceaf-41d6-9c27-6779084d022a)

Thank you

Br,
kd

**Comment by dali-dbr** [comment]
Directly copy the link to the clipboard or get a popup with the link, something like Onedrive does.

![image](https://github.com/invoiceninja/admin-portal/assets/6317229/538cd361-d8b8-4152-bc9d-e142918533b5)

**Comment by shubham3246** [comment]
hey @dali-dbr i wanted to know more about the issue, can you share your discord or slack.

**Comment by hillelcoren** [comment]
In the latest version you can click the button by the contact name to copy the portal link.

**Comment by dali-dbr** [comment]
Perfect, thank you!
