### ISSUE TITLE
Email Templates and Reminders

### ISSUE THREAD

**Issue by JackDAce** [invoiceninja/admin-portal#606]
## Setup
- Version: v5.7.46-W138
- Environment: Shared Hosting

## Interface
- Flutter: [X]
- React: []
- Both: []

## Checklist
- Can you replicate the issue on our v5 demo site https://demo.invoiceninja.com or https://react.invoicing.co/demo? Yes, put < html ></ html > then click Design. the loading will get stuck.
- Have you searched existing issues?
- Have you reported this to Slack/forum before posting?
- Have you inspected the logs in storage/logs/laravel.log for any errors? Yes, no errors.

## Describe the bug
All working with my v5.7.15. However, upon updating to the latest version, I can no longer send invoice/quote emails when clicking the "Send Email" button.  I tried to check my Laravel log and my PHP log (with DEBUG=True in my env) for any possible errors but can't find anything. Out of curiosity, I tried to remove my customized template and just put a normal div tag, and the abnormal behavior is gone. I also would like to add that this abnormal behavior only happens when I'm using Invoice Ninja via the Desktop and Browser. I never experienced the problem on the mobile app.

### Steps To Reproduce
Yes, put < html ></ html > then click Design. the loading will get stuck.

### Expected Behavior
To accept HTML tags for email customization under Templates and Reminders.

### Logs

```

```

**Comment by hillelcoren** [comment]
Can you please share an email template we can use to reproduce the problem?

**Comment by JackDAce** [comment]
Hi @hillelcoren , 

Please see the sample template.

```
<html>
<body>
<h1>Dear $contact.first_name,</h1>
<p>A new invoice with reference # $number has been generated, kindly see attached file. For any concern(s), feel free to reach out.</p>
</body>
</html>
```

**Comment by hillelcoren** [comment]
Thanks for the sample!

Is "Enable email markdown" enabled on Settings > Account Management/does disabling the option help?

**Comment by JackDAce** [comment]
Thanks for the quick workaround solution!

I disabled "Enable email markdown" and everything is working now.
