### ISSUE TITLE
Linking expenses to a transaction: Possibility to select currency-converted expenses

### ISSUE THREAD

**Issue by CodeShakingSheep** [invoiceninja/admin-portal#609]
**What version of Invoice Ninja are you running?**
v5

**What environment are you running?**
Self-hosted on Debian

**Have you searched existing issues/requests?**
Yes

**Additional context**
I have a transaction in € and an expense originally issued in $ but converted to € (based on an exchange rate). Unfortunately, I cannot select this expense for the transaction. I can only select it if I change the expense's currency to € before. I want to be able to select the converted expense right away without the need to change the currency.

Also, there is a small bug. When I change back the currency after linking the expense to the transaction, in the transaction view my expense is displayed with 29€.
![image](https://github.com/invoiceninja/invoiceninja/assets/19874562/206f8b96-c334-480f-9275-8721f8e09d3e)

This is not correct as the transaction was issued with $29 and converted to 26.53€.
![image](https://github.com/invoiceninja/invoiceninja/assets/19874562/bb01e318-4e2c-4d9c-a0d4-87b7fa6c9557)

**Comment by CodeShakingSheep** [comment]
@hillelcoren Thanks a lot for fixing this. I just realized that I accidentally opened this issue in the wrong repository. It happened in the web app. Never tried this in the Desktop or mobile app. So, I assume it needs to be fixed int the webapp repository too. Sorry for the confusion.

**Comment by hillelcoren** [comment]
The screenshot above is for the Flutter app, the web/desktop/mobile code is shared across all platforms.
