### ISSUE TITLE
Profit loss report is doesn't reflect converted currencies

### ISSUE THREAD

**Issue by fwilkecom** [invoiceninja/admin-portal#620]
### Setup
Version: v5.7.62-C145
Environment: self hosted - checked against demo platform as well

### Checklist
Can you replicate the issue on our v5 demo site https://demo.invoiceninja.com/ or https://react.invoicing.co/demo? Y
Have you searched existing issues? Y
Have you reported this to Slack/forum before posting? N
Have you inspected the logs in storage/logs/laravel.log for any errors? N
### Describe the bug
My currency is set as EUR

For some customers I have to create invoices in USD. So I set the customer's currency to USD.
I can create invoices in USD and I can insert the payment. Within the payment I set "Convert currency" and ensure that the correct convert rate is set.
In the payments list - after adding "Converted amount" column - I can see the payment value in EUR.
To have a report for tax authority I want to create a "profit and loss" report. I need all inbound and outbound payments to be shown in EUR but it is mixed in EUR and USD.

###Steps To  Reproduce
Own Currency ist set to EUR
Create customer and 
set the customer's currency to USD
Create invoice for the customer of i.e. 100$
Insert Payment for the invoice and enable "convert currency" option and set convert rate. Converted amount in EUR is shown.
Payments list shows converted amount in EUR if column is added.
Open Reports and chose "Profit and loss".
You will see profit and loss for each invoice currency but no full amount in EUR.
Report is not usable for me.

### Expected Behavior
The Report should show all payments in EUR

### Additional context
Screenshot showing report with several currencies (from demo platform)
![image](https://github.com/invoiceninja/admin-portal/assets/113901581/ced6b823-bbde-4c81-a609-64c69c59167a)

**Comment by hillelcoren** [comment]
We've added a "Converted Amount" column to the report to support this.
