### ISSUE TITLE
When amending or changing text in template before sending email it no longer sends the amended text

### ISSUE THREAD

**Issue by eagles051387** [invoiceninja/admin-portal#622]
Version 5.7.63-W146
Issue also is present on web based version as well

This is on a shared hosting setup

When amending or changing text in template before sending email it no longer sends the amended text. Prior to this update, this was working with out issue and I could amend what was being sent to add additional information and what ever I want.

This no longer seems to be the case. 

Screenshot attached.

![Screenshot 2023-12-27 174233](https://github.com/invoiceninja/invoiceninja/assets/359984/ece51c9f-9ea2-40ae-87c7-109acbc93a7a)

**Comment by eagles051387** [comment]
I can confirm this is still an issue on 5.8.1 and 5.8.2  has this been fixed?

**Comment by hillelcoren** [comment]
The should be fixed in the web app, the other apps haven't been updated yet.

**Comment by eagles051387** [comment]
what are the time lines for the desktop app having this issue fixed?

**Comment by hillelcoren** [comment]
We've submitted the new app to the Microsoft store, it should be available soon.
