### ISSUE TITLE
Transactions still showing newlines

### ISSUE THREAD

**Issue by LarsK1** [invoiceninja/admin-portal#625]
Hi,
the ui still shows newline-breaks
![image](https://github.com/invoiceninja/admin-portal/assets/28981528/ee402e45-0afe-4e67-ae81-997082b8b338)

Same for the react ui

**Comment by hillelcoren** [comment]
I've checked in a fix for the Flutter app.

Issues for the React app are tracked here: https://github.com/invoiceninja/ui/issues

**Comment by LarsK1** [comment]
Hi @hillelcoren ,
the issue is still showing. Just updated to the lastest release. Same image as in the original bug report

**Comment by hillelcoren** [comment]
Which version do you see in the about dialog?

**Comment by LarsK1** [comment]
v5.8.23-C154

**Comment by hillelcoren** [comment]
Thanks, I see the issue
