### ISSUE TITLE
Long list of options, when trying to change the status:

### ISSUE THREAD

**Issue by theoryshaw** [invoiceninja/admin-portal#626]
This seems like a bug...

When trying to change the status:

![2024-02-01_13-49-13_chromeinvoicing co__Invoice_Ninja_-_Google_Chromechrome](https://github.com/invoiceninja/invoiceninja/assets/507113/c0978e8e-4574-4dfa-8669-3eaedf1ebe60)

**Comment by hillelcoren** [comment]
It looks like duplicate statuses exist in your account, if you delete them on Settings > Task Settings it should resolve this issue.

**Comment by turbo124** [comment]
Check your database, do you see duplicate Task Statuses in the task status table?

**Comment by theoryshaw** [comment]
That was it! thanks.
