### ISSUE TITLE
Incorrect Frequency in Recurring Expenses Report

### ISSUE THREAD

**Issue by brockcaldwell** [invoiceninja/admin-portal#628]
## Setup
- Version: v5.0.30
- Environment: Docker

## Interface
- Flutter: [x]
- React: []
- Both: []

## Checklist
- Can you replicate the issue on our v5 demo site https://demo.invoiceninja.com or https://react.invoicing.co/demo?
Yes, on https://demo.invoiceninja.com

- Have you searched existing issues?
Yes

- Have you reported this to Slack/forum before posting?
No

- Have you inspected the logs in storage/logs/laravel.log for any errors?
Yes- nothing

## Describe the bug
Viewing the Recurring Expense report lists all expense frequencies as monthly. No other value will display there.

### Steps To Reproduce
1. Add a new Recurring Expense with Frequency = "Annually" (or anything besides monthly)
2. Load the Recurring Expense report
3. Notice how the record is displayed with Frequency = "Monthly", even though that is the incorrect value.

### Expected Behavior
Display the proper Frequency value for the record.

## Additional context
N/a

### Screenshots
N/a

### Logs
N/a

**Comment by hillelcoren** [comment]
Thanks for reporting this!

**Comment by brockcaldwell** [comment]
Thanks for the quick action! I also just noticed something else. On the Recurring Expenses Report, it shows the "Start Date" as the current date. In the code you just updated, it looks like you changed the variable from "invoice" to "expense." Does the same need to happen for the "start_date" on the line below? (I can open a separate issue, if needed.)

**Comment by hillelcoren** [comment]
Thank you, fixed!

**Comment by brockcaldwell** [comment]
Hi Hillel,

Appreciate the work you did on this, but it appears the issue is still there after updating. Another user is reporting the same issue on the hosted version:
https://github.com/invoiceninja/invoiceninja/pull/9266

**Comment by hillelcoren** [comment]
Which version of the app are you using? The hosted platform is running an older version of the app.

**Comment by hillelcoren** [comment]
You need to update the macOS app to the latest version.

**Comment by brockcaldwell** [comment]
Gotcha-

I just updated the server to v5.8.27 & updated in the Mac App Store and it is working (both in browser and app)!

Thanks so much!
