### ISSUE TITLE
Number filter ordering

### ISSUE THREAD

**Issue by K-MeLeOn** [invoiceninja/admin-portal#629]
## Setup
- Version: v4.5.25 / v5.8.23
- Environment: Kubernetes (docker image)

## Interface
- Flutter: []
- React: [x]
- Both: []

## Checklist
- [x] Can you replicate the issue on our v5 demo site https://demo.invoiceninja.com or https://react.invoicing.co/demo? 
- [x] Have you searched existing issues?
- [x] Have you reported this to Slack/forum before posting?
- [x] Have you inspected the logs in storage/logs/laravel.log for any errors?

## Describe the bug

Bad ordering on number without "0".

### Steps To Reproduce

- Add any item who can be ordered in the UI like invoice
- Add three of this item with number 64, 65, 640
- Order the column by clicking on the column name
- Got the order `64, 640, 65`

### Expected Behavior

- Got the order `64, 65, 640`

### Screenshots

![20240212_113711](https://github.com/invoiceninja/invoiceninja/assets/47109782/bca7b0bb-1a85-431e-8a4e-fd71387bdacf)

**Comment by hillelcoren** [comment]
Can you please post a screenshot showing where you see this issue in the Flutter app?

**Comment by K-MeLeOn** [comment]
> Can you please post a screenshot showing where you see this issue in the Flutter app?

Oops, bad checkbox checked ! Sorry for the trouble !
But in React the error is present yes

**Comment by hillelcoren** [comment]
The change in the API should correct the React app.
