### ISSUE TITLE
Missing fields in edit client with flutter that we have in react

### ISSUE THREAD

**Issue by mwa85** [invoiceninja/admin-portal#632]
Hi,

Running docker - v5.8.24-W155 and there is missing some fields in flutter/admin that we have in the react/ui

- Valid VAT Number
- Add to Invoices

![Screenshot 2024-02-15 163805](https://github.com/invoiceninja/admin-portal/assets/20386463/3a98eab3-c4a7-47cf-a2ba-0719dd76bd3f)

**Comment by hillelcoren** [comment]
Hi,

Thanks for reporting this! 

The "Add to invoice" option is shown in the Flutter app if the client has more than one contact.

I'm looking into the has_valid_vat_number field.
