### ISSUE TITLE
Strange UI/UX Settings display

### ISSUE THREAD

**Issue by alexgauvin** [invoiceninja/admin-portal#638]
I want to point out what seems to me as a UI/UX issue.

In Flutter, I recently found that all settings options were listed in a long list and wasn't able to have the usual display of settings listed by categories (company details, User details, ...)

It took me a while to find that there is a small button just left of search box strangely called [NEW] (see screenshot below), which toggles between settings listing by categories or all settings (which btw I can't understand the filter used for this display).

![Screenshot_1](https://github.com/invoiceninja/admin-portal/assets/5897903/5e224c6f-8c1a-4e20-b417-70ac98c1f128)

My point is that the purpose of this button should be more obvious and should not be called NEW as it doesn't make any sense to me.

And though I like the possibility that offers this toggle, the All settings listing should be listed in alphabetic order, or give the user to filter the listing with some options.

Thanks

**Comment by hillelcoren** [comment]
Thanks for pointing this out, I think the solution is to exit the new option when clicking settings in the left navigation. 

We're constantly adding new settings to the app, the purpose of this option is to enable people to easily find the recently added option when updating.
