### ISSUE TITLE
Feature Request - Being able to select date and range for Invoice Report and not just Payment Tax

### ISSUE THREAD

**Issue by Braunson** [invoiceninja/admin-portal#648]
**What version of Invoice Ninja are you running?** Hosted Enterprise Customer

**Have you searched existing issues/requests?** Yes

**Additional context**

When selecting the report `Payment Tax` we are able to select a date (payment or invoice) and range however for the report type `Invoice`, this is not an option. I'm requesting it be an option.

**Comment by hillelcoren** [comment]
The invoice report doesn't include the payment data.

**Comment by Braunson** [comment]
Any way we can get this added for paid invoices?

The goal is to get the invoice data for say last year based on the payment date (date + range filters) because I need the columns Tax and Net for each invoice along with the rest of the invoice data needed.

**Comment by hillelcoren** [comment]
The challenge is a single invoice may have more than one payment. 

Why not use the payment report but filter by the invoice date?

**Comment by Braunson** [comment]
The reason is they don't have the net and tax amounts.

**Comment by hillelcoren** [comment]
Ok, I believe that's being tracked in a separate issue
