### ISSUE TITLE
Drop-down- or push-up-menus are partwise out of sight

### ISSUE THREAD

**Issue by n1smithy** [invoiceninja/admin-portal#652]
## Setup
- Version: v5.8.54-L157
- Environment: Docker with mariaDB
- 
## Interface
- Flutter: [X]
- React: []
- Both: []

## Checklist
- Can you replicate the issue on our v5 demo site https://demo.invoiceninja.com or https://react.invoicing.co/demo? YES
- Have you searched existing issues? YES
- Have you reported this to Slack/forum before posting? NO
- Have you inspected the logs in storage/logs/laravel.log for any errors? NO

## Describe the bug
When a drop-down-menu is at the edge of the window, it won't be shown by it's complete size. The menu is cropped at the window-border. So the last/hidden items are not shown or clickable.

### Steps To Reproduce
Have a drop-down-menu directly near a window-border of the browser- or the app-window, the opened drop-down

### Expected Behavior
The drop-down-menu should be opened heading to the inner side of the window or even overlapping the window-border and not being cropped.

## Additional context
–

### Screenshots
![Bildschirmfoto vom 2024-05-13 14-37-42](https://github.com/invoiceninja/invoiceninja/assets/140073251/68a445b3-a8e4-41c6-8341-a3977b68e851)

### Logs
No logs, sirs and madames.

**Comment by hillelcoren** [comment]
Thanks for reporting this, once this issue is resolved (https://github.com/flutter/flutter/issues/101620) this will be corrected.

**Comment by shrawank039** [comment]
Hi,
May I try fixing this?

**Comment by hillelcoren** [comment]
@shrawank039 thanks for the offer!

I'm not sure, the proper solution for this will need to be implemented in Flutter itself.

**Comment by shrawank039** [comment]
I could try minimally fixing this without changing any major existing code. 
I went through this https://github.com/flutter/flutter/issues/101620 it's already a 2-year-old issue, and waiting for the official team to fix this is not a good idea. 
This is a major issue in UX because a small-screen user can never see the entire list of content in the autocomplete.

**Comment by hillelcoren** [comment]
Ok, if you can find a reasonable solution we could merge it. 

Thanks again!

**Comment by shrawank039** [comment]
Created a PR. 
Let me know if this needs any changes.

I tried not to change any current code. so in the future, if Flutter fixes this, then we only have to delete a few lines to revert this.

Thanks.
