### ISSUE TITLE
Missing setting

### ISSUE THREAD

**Issue by LarsK1** [invoiceninja/admin-portal#655]
Hi,
we added a new option in the last PR. Could you please add that option as well? (merge_e_invoice_to_pdf)
https://github.com/invoiceninja/invoiceninja/blob/643f8a64c3bb3a41baa9ff27dda20fc08cba562a/app/Jobs/Entity/CreateRawPdf.php#L116

**Comment by hillelcoren** [comment]
Hi,

Happy to add this but can you please provide more details, what change is needed in the frontend?

**Comment by LarsK1** [comment]
Hi,
you would need to add a new bool toogle which changes the client property "merge_e_invoice_to_pdf".

**Comment by hillelcoren** [comment]
Ok, thanks. What does this do?

**Comment by LarsK1** [comment]
It's an toggle to enable the merging of the einvoice to the pdf-file. So embedding the xml in the pdf.

**Comment by hillelcoren** [comment]
Got it, thanks!
