### ISSUE TITLE
404 when exporting Vendor list

### ISSUE THREAD

**Issue by lettucewrap4** [invoiceninja/admin-portal#658]
## Setup

Hosted

## Interface
- Flutter: []
- React: []
- Both: []

## Checklist
- Can you replicate the issue on our v5 demo site https://demo.invoiceninja.com or https://react.invoicing.co/demo?
- Have you searched existing issues?
- Have you reported this to Slack/forum before posting?
- Have you inspected the logs in storage/logs/laravel.log for any errors?

## Describe the bug

See screenshot

![image](https://github.com/invoiceninja/invoiceninja/assets/171772175/95e63f6a-a6e1-4492-a5e4-d64fce93c0bc)

**Comment by hillelcoren** [comment]
This issue should be resolved in the latest version of the app.

**Comment by lettucewrap4** [comment]
> This issue should be resolved in the latest version of the app.

Hmm, I'm using https://invoicing.co/ -- this isn't the latest?

**Comment by hillelcoren** [comment]
Correct, the latest release hasn't been deployed to invoicing.co yet. 

You can install the desktop app to access it.

https://invoiceninja.com/apps

**Comment by lettucewrap4** [comment]
Ah, you know ... json works, csv doesn't. Perhaps only json was fixed.

**Comment by hillelcoren** [comment]
It's possible the fix hasn't been released yet, it should be changed from Vendor to Vendors.

As a workaround it should work in the new web app: https://app.invoicing.co
