### ISSUE TITLE
Bulk update creates white screen (in desktop app)

### ISSUE THREAD

**Issue by dylanh724** [invoiceninja/admin-portal#659]
## Setup

Hosted with you

## Describe the bug

I show 100 rows, select all 100, bulk edit, I immediately get a white screen.

This feature doesn't exist in the web version, it seems, so only the desktop on Win11.

It's not frozen or "thinking" - just white with 0% cpu usage.

### Steps To Reproduce

1. Show 100 rows
2. Select 100 rows
3. Bulk edit

### Expected Behavior

Bulk edit screen would appear. 

### Screenshots

![image](https://github.com/invoiceninja/invoiceninja/assets/8840024/5bb94728-bd28-414f-abe3-49895407f4c7)

### Logs

Unfortunately, `storage/logs/` wasn't a very helpful tip for finding the logs here. I repro it every time 100% from customers db.

**Comment by hillelcoren** [comment]
Thanks for reporting this!

Does it make a difference how many rows you select?

**Comment by dylanh724** [comment]
> Thanks for reporting this!
> 
> Does it make a difference how many rows you select?

Just repro'd now with only 1, so any #

**Comment by hillelcoren** [comment]
I haven't been able to reproduce this.

Do you see the problem using the demo or anything else you can think of?

https://demo.invoiceninja.com
