### ISSUE TITLE
Import mapping 95% fails to auto-map

### ISSUE THREAD

**Issue by dylanh724** [invoiceninja/admin-portal#661]
## Setup

Using your hosted windows store app.

## Describe the bug

If I create a new customer from within invoice ninja, fill all the fields, export then import back in (**using Invoice ninja's own known column names**), only the following maps in a customer test:

1. Contact - First Name
2. Contact - Last Name
3. Contact - Email 

See screenshots below.

### Steps To Reproduce

1. Create a new customer with all info (see example screenshot below).
2. Export the customers.
3. Import it right back in -> **Nearly all auto-maps fail**

### Expected Behavior

It should attempt to auto-map:
* 100% should auto-map if a known named column
* Should at least _attempt_ to automap non-known fields using dominant keywords

## Additional context

I've been having blocking and unexpected import issues: This auto-map bug amplifies frustrations a thousandfold since I have to remap each iteration test.

This is just the customer example: Staff can QA test the others that surely have the same issues. **This issue is not _just_ for customers -- this is only a small sample/example.**

### Screenshots

![image](https://github.com/invoiceninja/invoiceninja/assets/8840024/68f9dbf8-2a23-4c8c-a566-bf7514369c4b)

![image](https://github.com/invoiceninja/invoiceninja/assets/8840024/ebaeb874-ae58-4869-858a-1b96e465956a)

![image](https://github.com/invoiceninja/invoiceninja/assets/8840024/1da8f116-74fe-4b77-9ad1-f6153b304882)

### Logs

```
// Please add comments for how to find files in hosted desktop winstore app -- no clue
```

**Comment by hillelcoren** [comment]
Hi,

Based on the column names this doesn't look like this is an export from the app?

**Comment by dylanh724** [comment]
> Hi,
> 
> Based on the column names this doesn't look like this is an export from the app?

☕ Oh wow, I mapped the wrong one and just autopiloted it using the wrong one -- apologies. Let me close this ticket for now.  I did try this before in the past and the result is essentially the same, but I never had time to report it until now.
