### ISSUE TITLE
Exporting vendors results in 404 error

### ISSUE THREAD

**Issue by dylanh724** [invoiceninja/admin-portal#662]
## Setup

Your hosted site

## Repro

1. Open Windows Store app
2. Export vendors
3. 404 err popup (screenshot below)

### Screenshots

![image](https://github.com/invoiceninja/invoiceninja/assets/8840024/0f00ad3f-afe4-4a82-82fb-4018a0b952ac)

(As a temp workaround, json works, but will likely be inconsistent with your other exports)

**Comment by dylanh724** [comment]
Actually... The json doesn't work either. 

You'll get an email inconsistent with others (different subject, vague info, no attachment), and provides a download button (doesn't let you know what kind of report it is).

You click download, and you download an html file rather than json file. 

It's a spiral of bugs - feels like an old flow accidentally left live.

**Comment by dylanh724** [comment]
![Screenshot_20240625_103158_K-9 Mail.jpg](https://github.com/invoiceninja/admin-portal/assets/8840024/462d74cf-4906-4dd7-9e63-624a00318bed)

**Comment by hillelcoren** [comment]
A fix for the 404 error has been checked in and will be included with the next Windows release.

Please create a separate issue if there are any other changes you'd like to see made.
