### ISSUE TITLE
why app not running on my system ,after completing all the process

### ISSUE THREAD

**Issue by RITIKKUMAWAT009** [invoiceninja/admin-portal#664]
You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

../../../AppData/Local/Pub/Cache/hosted/pub.dev/charts_flutter-0.12.0/lib/src/behaviors/legend/legend_entry_layout.dart:134:45: Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../../Downloads/flutter_windows_3.19.2-stable/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText2'.
      color ??= Theme.of(context).textTheme.bodyText2!.color;
                                            ^^^^^^^^^
lib/utils/markdown.dart:411:24: Error: Too few positional arguments: 1 required, 0 given.
        LinkAttribution(url: Uri.parse(element.attributes['href']!)),
                       ^
../../../AppData/Local/Pub/Cache/git/super_editor-2dc374209104f367a5de640576f860fcaf66ca3d/super_editor/lib/src/default_editor/attributions.dart:217:9: Context: Found this candidate, but the arguments don't match.
  const LinkAttribution(this.url);
        ^^^^^^^^^^^^^^^
lib/utils/super_editor/toolbar.dart:406:44: Error: Too few positional arguments: 1 required, 0 given.
    final linkAttribution = LinkAttribution(url: Uri.parse(url));
                                           ^
../../../AppData/Local/Pub/Cache/git/super_editor-2dc374209104f367a5de640576f860fcaf66ca3d/super_editor/lib/src/default_editor/attributions.dart:217:9: Context: Found this candidate, but the arguments don't match.
  const LinkAttribution(this.url);
        ^^^^^^^^^^^^^^^
Target kernel_snapshot_program failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\Lenovo\Downloads\flutter_windows_3.19.2-stable\flutter\packages\flutter_tools\gradle\src\main\groovy\flutter.groovy' line: 1682   

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\Lenovo\Downloads\flutter_windows_3.19.2-stable\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 37s
Running Gradle task 'assembleDebug'...                             98.6s
Error: Gradle task assembleDebug failed with exit code 1

**Comment by hillelcoren** [comment]
Hi, 

Is there a reason you're building the app rather than downloading from the app store?

**Comment by RITIKKUMAWAT009** [comment]
I want to know more about open source, so I am building the app instead of downloading it.

**Comment by hillelcoren** [comment]
Maybe you're using the wrong version of Flutter, the app is currently built with 3.19.6

https://github.com/invoiceninja/admin-portal/blob/master/lib/flutter_version.dart#L2
