### ISSUE TITLE
Duplicating/cloning quotes into quotes turns tasks into products

### ISSUE THREAD

**Issue by n1smithy** [invoiceninja/admin-portal#672]
## Setup
- Version: v5.10.9-L160
- Environment: Docker

## Interface
- Flutter: [x]
- React: [?]
- Both: []

## Checklist
- Can you replicate the issue on our v5 demo site https://demo.invoiceninja.com or https://react.invoicing.co/demo?
YES
- Have you searched existing issues?
YES
- Have you reported this to Slack/forum before posting?
NO
- Have you inspected the logs in storage/logs/laravel.log for any errors?
NO

## Describe the bug
As described above

### Steps To Reproduce
Save a quote which has one or more tasks. Clone it into another qoute. The new quote has only products but with the former tasks as products now.

### Expected Behavior
Tasks should stay tasks after cloning.

**Comment by hillelcoren** [comment]
When cloning, the app currently clears the references to the task/expense to prevent more than one line item from being linked to the same task/expense. 

@turbo124 do you have thoughts on this, should it be changed/how does the backend handle it?

**Comment by turbo124** [comment]
I think the issue here is the type_id may be getting changed from "2" to "1" ? the task_id/expense_id should definitely be cleared. by the type_id's should not change.

**Comment by hillelcoren** [comment]
That make sense, I'll look into it
