### ISSUE TITLE
Expenses always being set on "Paid" - invoicing.co

### ISSUE THREAD

**Issue by Abelonic** [invoiceninja/admin-portal#674]
Hi, 

everytime I create an expense with a future date it automatically sets the status on "paid". Why? 

Please help.

**Comment by Abelonic** [comment]
Hi, can someone help with this please. I still have not heard back from anyone. thank you

**Comment by hillelcoren** [comment]
We'll look into this for the next release.

If you can provide screenshots, including your expense settings, it may be helpful

**Comment by Abelonic** [comment]
hello, 

please find attached the requested screenshot. 

Thank you.

![Screenshot from 2024-07-31 18-40-55](https://github.com/user-attachments/assets/088b9a1b-83a8-467c-bb6e-ffd53acb6312)

**Comment by Abelonic** [comment]
Hi, any updates on this?

**Comment by hillelcoren** [comment]
I haven't been able to reproduce, can you please post a screenshot of the edit expense screen?

**Comment by Abelonic** [comment]
Hi, I did already before your msg. Please have a look.

**Comment by hillelcoren** [comment]
I see the expense settings, I'm asking for a screenshot of an individual expense.

**Comment by Abelonic** [comment]
Hi, 

as mentioned before, they are all set on not paid as I had to chage the website to set them all as "not paid". However please see the attachment. thx

![Screenshot 2024-08-05 101514](https://github.com/user-attachments/assets/e305d63c-fda4-4bef-bc3d-aaa63db4fa72)

**Comment by hillelcoren** [comment]
Can you share a screen recording showing the problem occur?

**Comment by Abelonic** [comment]
Hi Hillen, it is really very simple. When I create a new expense and adda a future date, after when I click on save, it sets the status of the expens on paid in the overview list. I am running in meetings now.

**Comment by hillelcoren** [comment]
Please share screenshots of the edit expense screen before/after you create a new expense.

**Comment by Abelonic** [comment]
[recording.zip](https://github.com/user-attachments/files/16493042/recording.zip)

please let me know if this help. thx

**Comment by hillelcoren** [comment]
Please see my last comment

**Comment by Abelonic** [comment]
![Screenshot 2024-08-05 103539](https://github.com/user-attachments/assets/5d203d83-eace-423c-9243-28a3c9b94ba8)

**Comment by hillelcoren** [comment]
That's the expense view screen, please share screenshots of the expense EDIT screen before/after you create a new expense.

**Comment by hillelcoren** [comment]
Also, which version of the app are you using?

**Comment by Abelonic** [comment]
![Screenshot 2024-08-05 104351](https://github.com/user-attachments/assets/dd988549-29e9-44e5-9c51-c145a8dcb962)

https://invoicing.co/

**Comment by hillelcoren** [comment]
Thanks, what version do you see in the about dialog?

**Comment by Abelonic** [comment]
v5.10.17-C161

**Comment by hillelcoren** [comment]
If the date is set today the problem doesn't occur?

**Comment by Abelonic** [comment]
The problem always occurs! It sets whatever date it shows automatically on paidBest regards/ Mit freundlichen Grüßen,
 
Mag. Aleksandra Belonic
Senior Financial Manager
EOX IT Services GmbH
A-1090 Wien,
 Thurngasse 8/4, Österreich / Austria
+43 676 8889 2 ***@***.***
Web: https://eox.at
HG Wien – FN/Reg. No. 312068z – UID/VAT No. ATU64265057
 
https://eurodatacube.com https://cloudless.eox.at https://maps.eox.at https://race.esa.int
-------- Original message --------From: Hillel Coren ***@***.***> Date: 05/08/2024  10:55  (GMT+01:00) To: invoiceninja/admin-portal ***@***.***> Cc: Abelonic ***@***.***>, Author ***@***.***> Subject: Re: [invoiceninja/admin-portal] Expenses always being set on "Paid" - invoicing.co (Issue #674) 
If the date is set today the problem doesn't occur?

**Comment by Abelonic** [comment]
is it ok like this or do you need anything else?

**Comment by Abelonic** [comment]
Is this ok with you`?

**Comment by Abelonic** [comment]
I can see that my comments disappear. Is the screenshot ok with you? Yout need anythin else?

**Comment by hillelcoren** [comment]
Thanks, I’ll continue to look into this when I’m back in the office.

**Comment by Abelonic** [comment]
Thank you.Best regards/ Mit freundlichen Grüßen,
 
Mag. Aleksandra Belonic
Senior Financial Manager
EOX IT Services GmbH
A-1090 Wien,
 Thurngasse 8/4, Österreich / Austria
+43 676 8889 2 ***@***.***
Web: https://eox.at
HG Wien – FN/Reg. No. 312068z – UID/VAT No. ATU64265057
 
https://eurodatacube.com https://cloudless.eox.at https://maps.eox.at https://race.esa.int
-------- Original message --------From: Hillel Coren ***@***.***> Date: 06/08/2024  10:38  (GMT+01:00) To: invoiceninja/admin-portal ***@***.***> Cc: Abelonic ***@***.***>, Author ***@***.***> Subject: Re: [invoiceninja/admin-portal] Expenses always being set on "Paid" - invoicing.co (Issue #674) 
Thanks, I’ll continue to look into this when I’m back in the office.

**Comment by Abelonic** [comment]
Hi, I am not sure what is happening, but its seems all my comments are gone. Not sure if you have commented anything since our last communication. Please update me. Thx

**Comment by n1smithy** [comment]
I had the same issue. The solution is to go into the expense-settings and switch the should-be-marked-as-paid-switch to ON again. Then delete your favourite payment-method, so this field is empty. After that you switch back to OFF. For me it worked, now generally created expenses are not marked as "paid" but as "logged".

**Comment by hillelcoren** [comment]
@n1smithy thanks for your suggestion, it would explain the problem.

It's a bug, I'll make sure it's corrected.

**Comment by Abelonic** [comment]
thank you very much.


*Best regards/ Mit freundlichen Grüßen,*


*Mag. Aleksandra Belonic*

Senior Financial Manager

EOX IT Services GmbH
A-1090 Wien, Thurngasse 8
<https://www.google.com/maps/search/A-1090+Wien,+Thurngasse+8?entry=gmail&source=g>/4,
Österreich / Austria
+43 676 8889 2 666, ***@***.***

Web: https://eox.at

HG Wien – FN/Reg. No. 312068z – UID/VAT No. ATU64265057



https://eurodatacube.com https://cloudless.eox.at https://maps.eox.at
https://race.esa.int


Am Do., 15. Aug. 2024 um 15:52 Uhr schrieb Hillel Coren <
***@***.***>:
