### ISSUE TITLE
Customer vs Client @ create invoice screen

### ISSUE THREAD

**Issue by datformatie** [invoiceninja/admin-portal#677]
when creating an invoice a field labelled "Customer" is presented that allows you to select a Client form the "Clients" list.

<img width="519" alt="Screenshot 2024-07-29 at 13 29 50" src="https://github.com/user-attachments/assets/1e7622f7-3113-4f7a-be2b-98131657dde8">

the documentation show "Client" instead of "Customer"

<img width="443" alt="Screenshot 2024-07-29 at 13 35 04" src="https://github.com/user-attachments/assets/2eb3e5da-431f-44f9-8570-10131f429e12">

**Comment by hillelcoren** [comment]
Can you please post a screenshot of Settings > Localization

**Comment by datformatie** [comment]
<img width="703" alt="Screenshot 2024-07-30 at 09 28 45" src="https://github.com/user-attachments/assets/877736c0-1e7d-4d91-863c-03cfde1f4111">

**Comment by hillelcoren** [comment]
Thanks, if you change to standard English it should correct it.

Alternatively you can update the UK English translation in Transifex.

**Comment by datformatie** [comment]
not familiar with Transifex (yet...), when we change things there are these global changes? i.e. for everybody using English - United Kingdom or just for our instance... and how can we customize our instance (f.e. to customize menu labels in admin screen)

**Comment by hillelcoren** [comment]
Here's the link: https://app.transifex.com/invoice-ninja/invoice-ninja/

- The changes in Transifex are global
- The app doesn't support customizing labels in the admin portal

**Comment by datformatie** [comment]
understood, and what about the Flutter web access (i.e not app)

**Comment by datformatie** [comment]
ps: switched to English => no result

**Comment by datformatie** [comment]
<img width="625" alt="Screenshot 2024-07-30 at 09 47 06" src="https://github.com/user-attachments/assets/51818921-24b8-4604-b547-96ae1789f7df">
<img width="707" alt="Screenshot 2024-07-30 at 09 46 52" src="https://github.com/user-attachments/assets/e7230de5-eab0-4e47-8cef-82ad7f5834bd">

**Comment by hillelcoren** [comment]
Not sure, I can't reproduce. Maybe try logging out the back in.

**Comment by datformatie** [comment]
noop, tried via  Desktop web App and via Flutter admin after artisan optimize, cache:clear, browser history clear=> still "Customer"

**Comment by hillelcoren** [comment]
Can you reproduce it in the demo?

https://demo.invoiceninja.com

**Comment by datformatie** [comment]
cannot reproduce as these is no way to change language in localization (and its v5.10.13...)

**Comment by datformatie** [comment]
<img width="755" alt="Screenshot 2024-07-30 at 14 36 56" src="https://github.com/user-attachments/assets/b2949a6d-30f1-46df-b5d7-d58b7fa09879">

**Comment by datformatie** [comment]
update: when setting Localization AND User Details language::=English => "Customer" changes into "Client"...
ps:
_The term localization is generally associated with U.S. English, while localisation is tied to British English and International English_

**Comment by hillelcoren** [comment]
Thanks for updating, this seems like the correct design
