### ISSUE TITLE
Selection button cannot be activated

### ISSUE THREAD

**Issue by ThomasKujawa** [invoiceninja/admin-portal#679]
## Setup
v5.10.20-W160

## Interface
Windows Desktop

## Checklist
- https://demo.invoiceninja.com yes
- https://react.invoicing.co/demo Buttons "Certificate not set" and "Passphrase not set" do not exist.
- Have you searched existing issues? yes
- Have you reported this to Slack/forum before posting? yes
- Have you inspected the logs in storage/logs/laravel.log for any errors? yes

## Describe the bug
After activating the e-Invoice, the two buttons cannot be activated.

### Steps To Reproduce
1. go to Settings.
2. go to E-Invoice settings.
3. activate Enable E-Invoice.
4. try to check the boxes.
 
### Expected Behavior
If no password has been entered or no certificate has been uploaded, I would like to use the selection.

## Additional context
see Slack channel

### Screenshots
see Slack channel

### Logs
`[2024-08-10 20:01:12] production.ERROR: Undefined array key 0 {"userId":1,"exception":"[object] (ErrorException(code: 0): Undefined array key 0 at /www/htdocs/w01b8983/rechnungv5/vendor/horstoeko/zugferd/src/ZugferdDocumentBuilder.php:274)
[stacktrace]
#0 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Undefined array...', '/www/htdocs/w01...', 274)
invoiceninja/invoiceninja#1 /www/htdocs/w01b8983/rechnungv5/vendor/horstoeko/zugferd/src/ZugferdDocumentBuilder.php(274): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}(2, 'Undefined array...', '/www/htdocs/w01...', 274)
invoiceninja/invoiceninja#2 /www/htdocs/w01b8983/rechnungv5/app/Services/EDocument/Standards/ZugferdEDokument.php(232): horstoeko\\zugferd\\ZugferdDocumentBuilder->setDocumentSummation(91.1, 91.1, 91.1, 0.0, 0.0, 91.1, Array, 0.0, 0.0)
invoiceninja/invoiceninja#3 /www/htdocs/w01b8983/rechnungv5/app/Jobs/EDocument/CreateEDocument.php(88): App\\Services\\EDocument\\Standards\\ZugferdEDokument->run()
invoiceninja/invoiceninja#4 /www/htdocs/w01b8983/rechnungv5/app/Services/Invoice/InvoiceService.php(209): App\\Jobs\\EDocument\\CreateEDocument->handle()
invoiceninja/invoiceninja#5 /www/htdocs/w01b8983/rechnungv5/app/Services/Invoice/InvoiceService.php(214): App\\Services\\Invoice\\InvoiceService->getEInvoice(NULL)
invoiceninja/invoiceninja#6 /www/htdocs/w01b8983/rechnungv5/app/Services/Email/EmailDefaults.php(331): App\\Services\\Invoice\\InvoiceService->getEDocument()
invoiceninja/invoiceninja#7 /www/htdocs/w01b8983/rechnungv5/app/Services/Email/EmailDefaults.php(77): App\\Services\\Email\\EmailDefaults->setAttachments()
invoiceninja/invoiceninja#8 /www/htdocs/w01b8983/rechnungv5/app/Services/Email/Email.php(234): App\\Services\\Email\\EmailDefaults->run()
invoiceninja/invoiceninja#9 /www/htdocs/w01b8983/rechnungv5/app/Services/Email/Email.php(108): App\\Services\\Email\\Email->setDefaults()
invoiceninja/invoiceninja#10 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Services\\Email\\Email->handle()
invoiceninja/invoiceninja#11 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
invoiceninja/invoiceninja#12 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
invoiceninja/invoiceninja#13 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
invoiceninja/invoiceninja#14 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
invoiceninja/invoiceninja#15 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call(Array)
invoiceninja/invoiceninja#16 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(App\\Services\\Email\\Email))
invoiceninja/invoiceninja#17 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Services\\Email\\Email))
invoiceninja/invoiceninja#18 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
invoiceninja/invoiceninja#19 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(124): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\Services\\Email\\Email), false)
invoiceninja/invoiceninja#20 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}(Object(App\\Services\\Email\\Email))
invoiceninja/invoiceninja#21 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Services\\Email\\Email))
invoiceninja/invoiceninja#22 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
invoiceninja/invoiceninja#23 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(71): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\\Queue\\Jobs\\SyncJob), Object(App\\Services\\Email\\Email))
invoiceninja/invoiceninja#24 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(102): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\SyncJob), Array)
invoiceninja/invoiceninja#25 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(76): Illuminate\\Queue\\Jobs\\Job->fire()
invoiceninja/invoiceninja#26 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(56): Illuminate\\Queue\\SyncQueue->executeJob(Object(App\\Services\\Email\\Email), '', NULL)
invoiceninja/invoiceninja#27 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(254): Illuminate\\Queue\\SyncQueue->push(Object(App\\Services\\Email\\Email))
invoiceninja/invoiceninja#28 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(230): Illuminate\\Bus\\Dispatcher->pushCommandToQueue(Object(Illuminate\\Queue\\SyncQueue), Object(App\\Services\\Email\\Email))
invoiceninja/invoiceninja#29 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(77): Illuminate\\Bus\\Dispatcher->dispatchToQueue(Object(App\\Services\\Email\\Email))
invoiceninja/invoiceninja#30 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php(193): Illuminate\\Bus\\Dispatcher->dispatch(Object(App\\Services\\Email\\Email))
invoiceninja/invoiceninja#31 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php(19): Illuminate\\Foundation\\Bus\\PendingDispatch->__destruct()
invoiceninja/invoiceninja#32 /www/htdocs/w01b8983/rechnungv5/app/Http/Controllers/EmailController.php(89): App\\Services\\Email\\Email::dispatch(Object(App\\Services\\Email\\EmailObject), Object(App\\Models\\Company))
invoiceninja/invoiceninja#33 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(257): App\\Http\\Controllers\\EmailController->App\\Http\\Controllers\\{closure}(Object(App\\Models\\InvoiceInvitation), 0)
invoiceninja/invoiceninja#34 /www/htdocs/w01b8983/rechnungv5/app/Http/Controllers/EmailController.php(81): Illuminate\\Support\\Collection->each(Object(Closure))
invoiceninja/invoiceninja#35 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\EmailController->send(Object(App\\Http\\Requests\\Email\\SendEmailRequest))
invoiceninja/invoiceninja#36 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction('send', Array)
invoiceninja/invoiceninja#37 /www/htdocs/w01b8983/rechnungv5/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/Routing/TracingControllerDispatcherTracing.php(21): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\EmailController), 'send')
invoiceninja/invoiceninja#38 /www/htdocs/w01b8983/rechnungv5/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/Routing/TracingRoutingDispatcher.php(18): Sentry\\Laravel\\Tracing\\Routing\\TracingControllerDispatcherTracing->Sentry\\Laravel\\Tracing\\Routing\\{closure}()
invoiceninja/invoiceninja#39 /www/htdocs/w01b8983/rechnungv5/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/Routing/TracingControllerDispatcherTracing.php(20): Sentry\\Laravel\\Tracing\\Routing\\TracingRoutingDispatcher->wrapRouteDispatch(Object(Closure), Object(Illuminate\\Routing\\Route))
invoiceninja/invoiceninja#40 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Sentry\\Laravel\\Tracing\\Routing\\TracingControllerDispatcherTracing->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\EmailController), 'send')
invoiceninja/invoiceninja#41 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Routing/Route.php(206): Illuminate\\Routing\\Route->runController()
invoiceninja/invoiceninja#42 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Routing/Router.php(808): Illuminate\\Routing\\Route->run()
invoiceninja/invoiceninja#43 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
invoiceninja/invoiceninja#44 /www/htdocs/w01b8983/rechnungv5/app/Http/Middleware/UserVerified.php(40): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
invoiceninja/invoiceninja#45 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\UserVerified->handle(Object(Illuminate\\Http\\Request), Object(Closure))
invoiceninja/invoiceninja#46 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(124): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
invoiceninja/invoiceninja#47 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(89): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequestUsingNamedLimiter(Object(Illuminate\\Http\\Request), Object(Closure), 'api', Object(Closure))
invoiceninja/invoiceninja#48 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'api')
invoiceninja/invoiceninja#49 /www/htdocs/w01b8983/rechnungv5/app/Http/Middleware/QueryLogging.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
invoiceninja/invoiceninja#50 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\QueryLogging->handle(Object(Illuminate\\Http\\Request), Object(Closure))
invoiceninja/invoiceninja#51 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
invoiceninja/invoiceninja#52 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
invoiceninja/invoiceninja#53 /www/htdocs/w01b8983/rechnungv5/app/Http/Middleware/Locale.php(95): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
invoiceninja/invoiceninja#54 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\Locale->handle(Object(Illuminate\\Http\\Request), Object(Closure))
invoiceninja/invoiceninja#55 /www/htdocs/w01b8983/rechnungv5/app/Http/Middleware/TokenAuth.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
invoiceninja/invoiceninja#56 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\TokenAuth->handle(Object(Illuminate\\Http\\Request), Object(Closure))
invoiceninja/invoiceninja#57 /www/htdocs/w01b8983/rechnungv5/app/Http/Middleware/SetDb.php(40): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
invoiceninja/invoiceninja#58 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\SetDb->handle(Object(Illuminate\\Http\\Request), Object(Closure))
invoiceninja/invoiceninja#59 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
invoiceninja/invoiceninja#60 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
invoiceninja/invoiceninja#61 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Routing/Router.php(786): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
invoiceninja/invoiceninja#62 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Routing/Router.php(750): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
invoiceninja/invoiceninja#63 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Routing/Router.php(739): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
invoiceninja/invoiceninja#64 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(201): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
invoiceninja/invoiceninja#65 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
invoiceninja/invoiceninja#66 /www/htdocs/w01b8983/rechnungv5/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Http/FlushEventsMiddleware.php(13): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
invoiceninja/invoiceninja#67 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Sentry\\Laravel\\Http\\FlushEventsMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
invoiceninja/invoiceninja#68 /www/htdocs/w01b8983/rechnungv5/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Http/SetRequestIpMiddleware.php(45): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
invoiceninja/invoiceninja#69 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Sentry\\Laravel\\Http\\SetRequestIpMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
invoiceninja/invoiceninja#70 /www/htdocs/w01b8983/rechnungv5/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Http/SetRequestMiddleware.php(31): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
invoiceninja/invoiceninja#71 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Sentry\\Laravel\\Http\\SetRequestMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
invoiceninja/invoiceninja#72 /www/htdocs/w01b8983/rechnungv5/vendor/livewire/livewire/src/Features/SupportDisablingBackButtonCache/DisableBackButtonCacheMiddleware.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
invoiceninja/invoiceninja#73 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Livewire\\Features\\SupportDisablingBackButtonCache\\DisableBackButtonCacheMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
invoiceninja/invoiceninja#74 /www/htdocs/w01b8983/rechnungv5/app/Http/Middleware/Cors.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
invoiceninja/invoiceninja#75 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\Cors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
invoiceninja/invoiceninja#76 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
invoiceninja/invoiceninja#77 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
invoiceninja/invoiceninja#78 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
invoiceninja/invoiceninja#79 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
invoiceninja/invoiceninja#80 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
invoiceninja/invoiceninja#81 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
invoiceninja/invoiceninja#82 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
invoiceninja/invoiceninja#83 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
invoiceninja/invoiceninja#84 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
invoiceninja/invoiceninja#85 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
invoiceninja/invoiceninja#86 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
invoiceninja/invoiceninja#87 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
invoiceninja/invoiceninja#88 /www/htdocs/w01b8983/rechnungv5/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/Middleware.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
invoiceninja/invoiceninja#89 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Sentry\\Laravel\\Tracing\\Middleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
invoiceninja/invoiceninja#90 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
invoiceninja/invoiceninja#91 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
invoiceninja/invoiceninja#92 /www/htdocs/w01b8983/rechnungv5/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
invoiceninja/invoiceninja#93 /www/htdocs/w01b8983/rechnungv5/public/index.php(56): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
invoiceninja/invoiceninja#94 {main}
"} `

**Comment by hillelcoren** [comment]
I was helping you on Slack, sorry I think I misunderstood your question.

They aren't checkboxes, they're status indicators. Once you set a certificate/password they'll turn green.
