### ISSUE TITLE
iOS-keyboard: wrong layout when editing contact-surename

### ISSUE THREAD

**Issue by n1smithy** [invoiceninja/admin-portal#688]
Greetings!

When editing the surename of a contact of a client, the keyboard-layout seems to be set for telephone-numbers but not for names or similar strings. So it's not possible to write a hyphen or stuff.

Greets!

**Comment by hillelcoren** [comment]
Thanks for reporting this, we'll look into it.

**Comment by hillelcoren** [comment]
I'm not able to reproduce this, can you please post a screenshot?

**Comment by n1smithy** [comment]
Sure that!
Name, keyboard set to ABC:
![Name ABC](https://github.com/user-attachments/assets/ec53e025-7ba1-4d26-8acb-84e7ebf1b59b)


Name, keyboard set to 123:
![Name 123](https://github.com/user-attachments/assets/449f682a-940a-4141-9578-ff9d9cbfa5b0)

Surename and ABC:
![Surename ABC](https://github.com/user-attachments/assets/03a84d00-47ee-4268-b6c6-c72b934525a6)

Surename and 123:
![Surename 123](https://github.com/user-attachments/assets/45359d5d-d604-4cef-978e-bd8d3c2f4337)

It's an iPhone X with latest firmware (16.7.10).

**Comment by hillelcoren** [comment]
Thanks, I understand now.

We're using a keyboard optimized for names but it looks like we'll need to change it.

https://api.flutter.dev/flutter/services/TextInputType/name-constant.html
