### ISSUE TITLE
Wrong file name of invoices and quotes PDF from app (snap)

### ISSUE THREAD

**Issue by vslonska** [invoiceninja/admin-portal#689]
Hello,

When I download a quote or an invoice from the web, I have a file named Devis_NUMBER.pdf (in French because my install is in french).

When I download it from the snap app on Linux, I have Devis_Devis_NUMBER.pdf or Facture_Invoice.pdf

So with a duplicate of the type of the file (Quote or Invoice) and in two languages.

Thanks,

**Comment by hillelcoren** [comment]
This issue will be resolved in the next version of the Snap release.

Alternatively, you can download the latest release now as a Flatpak.

https://flathub.org/apps/com.invoiceninja.InvoiceNinja
