### ISSUE TITLE
Error in mobile when click PDF view "Invalid argument(s): No host specified in URI "

### ISSUE THREAD

**Issue by samsong** [invoiceninja/admin-portal#698]
## Setup
- Version: v5.10.29-A171
- Environment: self shared host php

## Interface
- Flutter: []
- React: []
- Both: []
- 
Android mobile app latest version

## Checklist
- Can you replicate the issue on our v5 demo site https://demo.invoiceninja.com or https://react.invoicing.co/demo?
- Have you searched existing issues?
- Have you reported this to Slack/forum before posting?
- Have you inspected the logs in storage/logs/laravel.log for any errors?

Yes. Will provide server logs soon.

## Describe the bug
Error when view PDF button click on invoice

### Steps To Reproduce
Open a invoice. Click view PDF

### Expected Behavior
Pdf should load without error 

### Logs
Error message

Invalid argument(s): No host specified in URI mywebsiteurl.com/client/invoice/DTwp8R8QTAyEExxJdcXFZ1ACmATy0NVC/download?t=1731406806740

#0      _HttpClient._openUrl (dart:_http/http_impl.dart:2752)
invoiceninja/invoiceninja#1      _HttpClient.openUrl (dart:_http/http_impl.dart:2623)
invoiceninja/invoiceninja#2      IOClient.send (package:http/src/io_client.dart:63)
invoiceninja/invoiceninja#3      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
invoiceninja/invoiceninja#4      BaseClient.get (package:http/src/base_client.dart:27)
invoiceninja/invoiceninja#5      WebClient.get (package:invoiceninja_flutter/data/web_client.dart:50)
invoiceninja/invoiceninja#6      _loadPDF (package:invoiceninja_flutter/ui/invoice/invoice_pdf.dart:330)
invoiceninja/invoiceninja#7      _InvoicePdfViewState.loadPdf (package:invoiceninja_flutter/ui/invoice/invoice_pdf.dart:80)
invoiceninja/invoiceninja#8      _InvoicePdfViewState.didChangeDependencies (package:invoiceninja_flutter/ui/invoice/invoice_pdf.dart:65)
invoiceninja/invoiceninja#9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5629)
invoiceninja/invoiceninja#10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
invoiceninja/invoiceninja#11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
invoiceninja/invoiceninja#14     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
invoiceninja/invoiceninja#15     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
invoiceninja/invoiceninja#16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
invoiceninja/invoiceninja#17     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
invoiceninja/invoiceninja#18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
invoiceninja/invoiceninja#19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
invoiceninja/invoiceninja#22     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
invoiceninja/invoiceninja#23     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
invoiceninja/invoiceninja#24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
invoiceninja/invoiceninja#25     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
invoiceninja/invoiceninja#26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
invoiceninja/invoiceninja#27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
invoiceninja/invoiceninja#30     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
invoiceninja/invoiceninja#31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
invoiceninja/invoiceninja#32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
invoiceninja/invoiceninja#33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#34     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
invoiceninja/invoiceninja#36     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
invoiceninja/invoiceninja#37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
invoiceninja/invoiceninja#38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
invoiceninja/invoiceninja#39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#41     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
invoiceninja/invoiceninja#42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#43     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
invoiceninja/invoiceninja#45     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
invoiceninja/invoiceninja#46     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
invoiceninja/invoiceninja#47     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
invoiceninja/invoiceninja#48     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#49     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#50     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
invoiceninja/invoiceninja#51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#52     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#53     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
invoiceninja/invoiceninja#54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#55     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
invoiceninja/invoiceninja#57     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
invoiceninja/invoiceninja#58     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
invoiceninja/invoiceninja#59     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
invoiceninja/invoiceninja#60     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
invoiceninja/invoiceninja#61     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
invoiceninja/invoiceninja#62     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#63     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#64     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
invoiceninja/invoiceninja#65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#66     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
invoiceninja/invoiceninja#68     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
invoiceninja/invoiceninja#69     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
invoiceninja/invoiceninja#70     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
invoiceninja/invoiceninja#71     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
invoiceninja/invoiceninja#72     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
invoiceninja/invoiceninja#73     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#74     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#75     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
invoiceninja/invoiceninja#76     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#77     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
invoiceninja/invoiceninja#79     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
invoiceninja/invoiceninja#80     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
invoiceninja/invoiceninja#81     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
invoiceninja/invoiceninja#82     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
invoiceninja/invoiceninja#83     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
invoiceninja/invoiceninja#84     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#85     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
invoiceninja/invoiceninja#87     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
invoiceninja/invoiceninja#88     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
invoiceninja/invoiceninja#89     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
invoiceninja/invoiceninja#90     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
invoiceninja/invoiceninja#91     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
invoiceninja/invoiceninja#92     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#93     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#94     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
invoiceninja/invoiceninja#95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#96     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
invoiceninja/invoiceninja#98     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
invoiceninja/invoiceninja#99     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
invoiceninja/invoiceninja#100    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
invoiceninja/invoiceninja#101    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
invoiceninja/invoiceninja#102    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
invoiceninja/invoiceninja#103    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#104    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#105    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
invoiceninja/invoiceninja#106    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#107    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
invoiceninja/invoiceninja#109    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
invoiceninja/invoiceninja#110    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
invoiceninja/invoiceninja#111    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
invoiceninja/invoiceninja#112    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
invoiceninja/invoiceninja#113    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
invoiceninja/invoiceninja#114    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#115    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#116    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
invoiceninja/invoiceninja#117    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
invoiceninja/invoiceninja#118    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
invoiceninja/invoiceninja#119    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
invoiceninja/invoiceninja#120    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
invoiceninja/invoiceninja#121    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
invoiceninja/invoiceninja#122    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#123    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
invoiceninja/invoiceninja#125    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
invoiceninja/invoiceninja#126    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
invoiceninja/invoiceninja#127    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
invoiceninja/invoiceninja#128    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#129    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#130    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
invoiceninja/invoiceninja#131    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
invoiceninja/invoiceninja#132    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
invoiceninja/invoiceninja#133    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
invoiceninja/invoiceninja#134    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
invoiceninja/invoiceninja#135    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
invoiceninja/invoiceninja#136    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#137    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#138    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
invoiceninja/invoiceninja#139    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#140    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#141    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
invoiceninja/invoiceninja#142    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
invoiceninja/invoiceninja#143    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
invoiceninja/invoiceninja#144    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
invoiceninja/invoiceninja#145    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#146    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#147    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
invoiceninja/invoiceninja#148    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#149    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#150    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
invoiceninja/invoiceninja#151    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
invoiceninja/invoiceninja#152    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
invoiceninja/invoiceninja#153    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
invoiceninja/invoiceninja#154    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
invoiceninja/invoiceninja#155    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
invoiceninja/invoiceninja#156    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#157    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#158    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
invoiceninja/invoiceninja#159    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
invoiceninja/invoiceninja#160    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
invoiceninja/invoiceninja#161    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
invoiceninja/invoiceninja#162    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#163    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#164    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
invoiceninja/invoiceninja#165    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
invoiceninja/invoiceninja#166    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
invoiceninja/invoiceninja#167    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
invoiceninja/invoiceninja#168    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#169    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#170    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
invoiceninja/invoiceninja#171    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
invoiceninja/invoiceninja#172    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
invoiceninja/invoiceninja#173    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
invoiceninja/invoiceninja#174    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
invoiceninja/invoiceninja#175    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
invoiceninja/invoiceninja#176    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#177    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#178    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
invoiceninja/invoiceninja#179    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
invoiceninja/invoiceninja#180    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
invoiceninja/invoiceninja#181    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
invoiceninja/invoiceninja#182    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#183    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#184    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
invoiceninja/invoiceninja#185    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
invoiceninja/invoiceninja#186    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
invoiceninja/invoiceninja#187    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
invoiceninja/invoiceninja#188    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#189    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#190    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
invoiceninja/invoiceninja#191    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#192    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#193    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
invoiceninja/invoiceninja#194    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
invoiceninja/invoiceninja#195    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
invoiceninja/invoiceninja#196    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
invoiceninja/invoiceninja#197    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#198    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#199    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
invoiceninja/invoiceninja#200    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
invoiceninja/invoiceninja#201    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
invoiceninja/invoiceninja#202    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
invoiceninja/invoiceninja#203    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#204    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#205    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
invoiceninja/invoiceninja#206    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
invoiceninja/invoiceninja#207    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
invoiceninja/invoiceninja#208    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
invoiceninja/invoiceninja#209    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
invoiceninja/invoiceninja#210    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
invoiceninja/invoiceninja#211    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#212    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#213    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
invoiceninja/invoiceninja#214    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
invoiceninja/invoiceninja#215    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
invoiceninja/invoiceninja#216    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
invoiceninja/invoiceninja#217    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
invoiceninja/invoiceninja#218    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
invoiceninja/invoiceninja#219    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#220    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#221    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
invoiceninja/invoiceninja#222    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
invoiceninja/invoiceninja#223    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
invoiceninja/invoiceninja#224    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
invoiceninja/invoiceninja#225    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
invoiceninja/invoiceninja#226    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
invoiceninja/invoiceninja#227    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#228    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#229    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
invoiceninja/invoiceninja#230    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#231    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#232    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
invoiceninja/invoiceninja#233    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
invoiceninja/invoiceninja#234    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
invoiceninja/invoiceninja#235    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
invoiceninja/invoiceninja#236    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
invoiceninja/invoiceninja#237    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
invoiceninja/invoiceninja#238    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
invoiceninja/invoiceninja#239    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
invoiceninja/invoiceninja#240    ComponentElement._firstBuild (package:fl

**Comment by samsong** [comment]
Hi team. Checked & this issue only appears on mobile app android.
on website with chrome browser "view pdf" same button works OK. PDF is shown. Download PDF also works.

I'll see if I can get the laravel log but hopefully the above error message clarifies for you.

**Comment by hillelcoren** [comment]
Does it work using the desktop app?

https://invoiceninja.com/apps

**Comment by hillelcoren** [comment]
Ok, please let us know if it works in the desktop app

I also suggest trying to switch to/from wifi or celular data

**Comment by samsong** [comment]
Following also confirmed not working in mobile:

* Click "view portal" from invoice nothing happens
* 
^ but click on client from invoice & click view portal works.
^ Copy link button works & the link pasted into browser loads successfully 

* View pdf in web browser does not work.
* Returns a random series of characters and "open" button which may just be chrome browser.

Download pdf in web browser works.

**Comment by hillelcoren** [comment]
Please reply to my last comment

**Comment by samsong** [comment]
@hillelcoren tested today windows app from app store
v5.10.43-W171

Same issue confirmed exists in windows app.
- view invoice -> click "view portal" nothing happens
- view invoice -> click "view pdf" - error message same as mobile

view PDF from standard website works fine.

![invoice-ninja_windows_error_view-invoice_click-view-pdf](https://github.com/user-attachments/assets/563147cd-b6c3-4260-8f71-26ce29ba74ab)

**Comment by samsong** [comment]
I found the issue.
I had set the "domain url" in client portal. as:   mydomain.com

This is what causes the error.
For some reason invoice ninja is trying to resolve the URL without "http" or "https"

You must manually type domain url with prefix https://

then it seems to work.

I suggest this be logged as a bug. The app should be able to handle a user omitting http/https since it can also be a configuration feature which HTTP protocal is served to customer.

**Comment by samsong** [comment]
![Screenshot_1](https://github.com/user-attachments/assets/a47c1807-4219-4890-a303-606dda308871)

**Comment by samsong** [comment]
on a separate matter, after I removed domain url, second time opening invoice ninja windows app I get black screen, blank white box
![Screenshot_2](https://github.com/user-attachments/assets/67ddbfe4-bf0e-45da-b65c-fedde6edb376)

**Comment by hillelcoren** [comment]
Are you able to login to the mobile app?

**Comment by samsong** [comment]
yes I can access mobile app still, but desktop app was total blank. no response no clickable anywhere.
i uninstalled it as there was no workaround to reset or unlock it or clear cache etc.

I'm happy to keep using the website based app & mobile apps.
but at least we've clarified the fault is the client portal url.

**Comment by hillelcoren** [comment]
Feel free to create a separate issue to track the problem

**Comment by samsong** [comment]
Ok but can you reopen & assign this issue as a bug also.
entering the client portal "domain url" without HTTP causes the mobile & desktop apps to break as detailed in the above symptom.
so this thread should be open as bug.
cheers

**Comment by hillelcoren** [comment]
I suggest creating a new issue clearly explaining the actual problem which links to this issue

**Comment by xeruf** [comment]
thanks :) looks like the backlinks are not removed but it's a good step regardless
