### ISSUE TITLE
Show public and private notes of a client on Invoice-, Quotes- and other document-editors

### ISSUE THREAD

**Issue by n1smithy** [invoiceninja/admin-portal#700]
Hi @ all,

it would be a big help if private and public notes of a client would be visible in the entity-editor.

I – as an example – note the distance to the customer's place as a private note into the client-details. So I don't have always to research the kilometers. But it's a pitty to have to close the editor just to see that info.

Thanks!

**Comment by hillelcoren** [comment]
I believe the info should already be there, can you please post a screenshot?

**Comment by n1smithy** [comment]
Hello, @hillelcoren,

private notes are set, but not shown when creating an invoice.
Screenshots below:
![Private Notes yes](https://github.com/user-attachments/assets/290210a7-d8f6-4073-a99c-05dfabbc522e)
![Private Notes no](https://github.com/user-attachments/assets/c2c6acc3-6de9-4dcd-a259-55ad01b3a951)
