### ISSUE TITLE
Payment made notification email "view payment" button link does not link to payment directly

### ISSUE THREAD

**Issue by mrkylegp** [invoiceninja/admin-portal#701]
v5.10.58-W171

When an admin receives the notification email of a payment and you click the "view payment" button, it simply opens the base invoice ninja URL and not the payment directly in the admin portal as expected.

![image](https://github.com/user-attachments/assets/4c02d06c-376e-41a6-9ffa-2af24efb3963)

**Comment by hillelcoren** [comment]
Hi,

Are you using the Flutter or React web apps?

**Comment by mrkylegp** [comment]
> Hi,
> 
> Are you using the Flutter or React web apps?

Flutter

**Comment by hillelcoren** [comment]
To have the link open the item directly you'll need to use the React web app.
